import type { FactionUnitOptions } from "./types";

// Generated by scripts/sync-unit-options.mjs. Do not edit by hand.
export const chaosChaosSpaceMarines: FactionUnitOptions = {
  "catalogue": "Chaos - Chaos Space Marines",
  "rules": {
    "Anti-": "Weapons with **[ANTI-KEYWORD X+]** in their profile are known as Anti weapons. Each time an attack is made with such a weapon against a target with the keyword after the word ‘Anti-’, an unmodified Wound roll of ‘x+’ scores a Critical Wound.",
    "Blast": "Weapons with **[BLAST]** in their profile are known as Blast weapons, and they make a random number of attacks. Each time you determine how many attacks are made with a Blast weapon, add 1 to the result for every five models that were in the target unit when you selected it as the target (rounding down). Blast weapons can never be used to make attacks against a unit that is within Engagement Range of one or more units from the attacking model’s army (including its own unit).",
    "Devastating Wounds": "Weapons with **[DEVASTATING WOUNDS]** in their profile are known as Devastating Wounds weapons. Each time an attack is made with such a weapon, if that attack scores a Critical Wound, no saving throw of any kind can be made against that attack (including invulnerable saving throws). Such attacks are only allocated to models after all other attacks made by the attacking unit have been allocated and resolved. After that attack is allocated and after any modifiers are applied, it inflicts a number of mortal wounds on the target equal to the Damage characteristic of that attack, instead of inflicting damage normally.",
    "Extra Attacks": "Weapons with **[EXTRA ATTACKS]** in their profile are known as Extra Attacks weapons. Each time the bearer of one or more Extra Attacks weapons fights, it makes attacks with each of the Extra Attacks melee weapons it is equipped with and it makes attacks with one of the melee weapons it is equipped with that does not have the [EXTRA ATTACKS] ability (if any). The number of attacks made with an Extra Attacks weapon cannot be modified by other rules, unless that weapon’s name is explicitly specified in that rule.",
    "Hazardous": "Weapons with **[HAZARDOUS]** in their profile are known as Hazardous weapons. Each time a unit is selected to shoot or fight, after that unit has resolved all of its attacks, for each Hazardous weapon that targets were selected for when resolving those attacks, that unit must take one Hazardous test. To do so, roll one D6: on a 1, that test is failed. For each failed test you must resolve the following sequence (resolve each failed test one at a time): \n\n■ If possible, select one model in that unit that has lost one or more wounds and is equipped with one or more Hazardous weapons. \n■ Otherwise, if possible, select one model in that unit (excluding **^^Character^^** models) equipped with one or more Hazardous weapons. \n■ Otherwise, select one **^^Character^^** model in that unit equipped with one or more Hazardous weapons. \n\nIf a model was selected, that unit suffers 3 mortal wounds and when allocating those mortal wounds, they must be allocated to the selected model. \n\nIf a unit from a player’s army is selected as the target of the Fire Overwatch Stratagem in their opponent’s Charge phase, any mortal wounds inflicted by Hazardous tests are allocated after the charging unit has ended its Charge move.",
    "Heavy": "Weapons with **[HEAVY]** in their profile are known as Heavy weapons. Each time an attack is made with such a weapon, if the attacking model’s unit Remained Stationary this turn, add 1 to that attack’s Hit roll.",
    "Ignores Cover": "Weapons with **[IGNORES COVER]** in their profile are known as Ignores Cover weapons. Each time an attack is made with such a weapon, the target cannot have the Benefit of Cover against that attack.",
    "Indirect Fire": "Weapons with **[INDIRECT FIRE]** in their profile are known as Indirect Fire weapons, and attacks can be made with them even if the target is not visible to the attacking model. These attacks can destroy enemy models in a target unit even though none may have been visible to the attacking unit when you selected that target.\n\n\nIf no models in a target unit are visible to the attacking unit when you select that target, then each time a model in the attacking unit makes an attack against that target using an Indirect Fire weapon, subtract 1 from that attack’s Hit roll, an unmodified Hit roll of 1-3 always fails, and the target has the Benefit of Cover against that attack. Weapons with the **[TORRENT]** ability cannot be fired using the **[INDIRECT FIRE]** ability.",
    "Lance": "Weapons with **[LANCE]** in their profile are known as Lance weapons. Each time an attack is made with such a weapon, if the bearer made a Charge move this turn, add 1 to that attack’s Wound roll.",
    "Melta": "Weapons with **[MELTA X]** in their profile are known as Melta weapons. Each time an attack made with such a weapon targets a unit within half that weapon’s range, that attack’s Damage characteristic is increased by the amount denoted by ‘x’.",
    "Pistol": "Weapons with **[PISTOL]** in their profile are known as Pistols. If a unit contains any models equipped with Pistols, that unit is eligible to shoot in its controlling player’s Shooting phase even while it is within Engagement Range of one or more enemy units. When such a unit is selected to shoot, it can only resolve attacks using its Pistols and can only target one of the enemy units it is within Engagement Range of. In such circumstances, a Pistol can target an enemy unit even if other friendly units are within Engagement Range of the same enemy unit. \n\nIf a model is equipped with one or more Pistols, unless it is a **^^Monster^^** or **^^Vehicle^^** model, it can either shoot with its Pistols or with all of its other ranged weapons. Declare whether such a model will shoot with its Pistols or its other ranged weapons before selecting targets.",
    "Precision": "Weapons with **[PRECISION]** in their profile are known as Precision weapons. Each time an attack made with such a weapon successfully wounds an Attached unit, if a Character model in that unit is visible to the attacking model, the attacking model’s player can choose to have that attack allocated to that Character model instead of following the normal attack sequence.",
    "Psychic": "Some weapons and abilities can only be used by **^^Psykers^^**. Such weapons and abilities are tagged with the word 'Psychic'. If a Psychic weapon or ability causes any unit to suffer one or more wounds, each of those wounds is considered to have been inflicted by a Psychic Attack.",
    "Rapid Fire": "Weapons with **[RAPID FIRE X]** in their profile are known as Rapid Fire weapons. Each time such a weapon targets a unit within half that weapon’s range, the Attacks characteristic of that weapon is increased by the amount denoted by ‘x’.",
    "Sustained Hits": "Weapons with **[SUSTAINED HITS X]** in their profile are known as Sustained Hits weapons. Each time an attack is made with such a weapon, if a Critical Hit is rolled, that attack scores a number of additional hits on the target as denoted by ‘x’",
    "Torrent": "Weapons with **[TORRENT]** in their profile are known as Torrent weapons. Each time an attack is made with such a weapon, that attack automatically hits the target.",
    "Twin-linked": "Weapons with **[TWIN-LINKED]** in their profile are known as Twin-linked weapons. Each time an attack is made with such a weapon, you can re-roll that attack’s Wound roll."
  },
  "units": {
    "76b4-a2c4-208e-ceb9": {
      "name": "Abaddon the Despoiler",
      "weapons": [
        {
          "name": "Talon of Horus",
          "profiles": [
            {
              "id": "5d4-40e6-b003-921d",
              "name": "Talon of Horus",
              "type": "ranged",
              "range": "24\"",
              "attacks": "4",
              "skill": "2+",
              "strength": 5,
              "ap": -1,
              "damage": "2",
              "keywords": "Sustained Hits 1"
            },
            {
              "id": "f7e1-1185-d5e-1ed0",
              "name": "Talon of Horus",
              "type": "melee",
              "range": "Melee",
              "attacks": "14",
              "skill": "2+",
              "strength": 7,
              "ap": -3,
              "damage": "1",
              "keywords": "Devastating Wounds"
            }
          ],
          "rules": [
            "Sustained Hits",
            "Devastating Wounds"
          ]
        },
        {
          "name": "Drach'nyen",
          "profiles": [
            {
              "id": "f89d-b352-387c-1f29",
              "name": "Drach'nyen",
              "type": "melee",
              "range": "Melee",
              "attacks": "8",
              "skill": "2+",
              "strength": 14,
              "ap": -4,
              "damage": "3",
              "keywords": "Devastating Wounds"
            }
          ],
          "rules": [
            "Devastating Wounds"
          ]
        }
      ]
    },
    "e981-27ae-112f-aa9a": {
      "name": "Chaos Rhino",
      "weapons": [
        {
          "name": "Combi-weapon",
          "profiles": [
            {
              "id": "3a24-7f6b-db11-6cf",
              "name": "Combi-weapon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Anti-INFANTRY 4+, Devastating Wounds, Rapid Fire 1"
            }
          ],
          "rules": [
            "Anti-",
            "Rapid Fire",
            "Devastating Wounds"
          ]
        },
        {
          "name": "Armoured tracks",
          "profiles": [
            {
              "id": "e7ef-8415-2391-4c1",
              "name": "Armoured tracks",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "4+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Havoc launcher",
          "profiles": [
            {
              "id": "6691-69f0-ca72-827d",
              "name": "Havoc launcher",
              "type": "ranged",
              "range": "48\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        }
      ]
    },
    "203d-c50f-a438-4982": {
      "name": "Chaos Terminator Squad",
      "weapons": [
        {
          "name": "Combi-weapon",
          "profiles": [
            {
              "id": "e3ad-464f-639e-be38",
              "name": "Combi-weapon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Anti-INFANTRY 4+, Devastating Wounds, Rapid Fire 1"
            }
          ],
          "rules": [
            "Anti-",
            "Rapid Fire",
            "Devastating Wounds"
          ]
        },
        {
          "name": "Power fist",
          "profiles": [
            {
              "id": "6660-1717-d600-bb61",
              "name": "Power fist",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Heavy flamer",
          "profiles": [
            {
              "id": "5885-e209-121a-e76b",
              "name": "Heavy flamer",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 5,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Reaper autocannon",
          "profiles": [
            {
              "id": "c6bf-73a0-b685-6977",
              "name": "Reaper autocannon",
              "type": "ranged",
              "range": "36\"",
              "attacks": "4",
              "skill": "3+",
              "strength": 7,
              "ap": -1,
              "damage": "1",
              "keywords": "Devastating Wounds, Sustained Hits 1"
            }
          ],
          "rules": [
            "Devastating Wounds",
            "Sustained Hits"
          ]
        },
        {
          "name": "Paired accursed weapons",
          "profiles": [
            {
              "id": "ae4b-feea-b2aa-871b",
              "name": "Paired accursed weapons",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "3+",
              "strength": 5,
              "ap": -2,
              "damage": "1",
              "keywords": "Twin-linked"
            }
          ],
          "rules": [
            "Twin-linked"
          ]
        }
      ]
    },
    "45b-19f6-38d2-703f": {
      "name": "Forgefiend",
      "weapons": [
        {
          "name": "Ectoplasma cannon",
          "profiles": [
            {
              "id": "4334-a89f-4620-2546",
              "name": "Ectoplasma cannon",
              "type": "ranged",
              "range": "36\"",
              "attacks": "D3",
              "skill": "3+",
              "strength": 10,
              "ap": -3,
              "damage": "3",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        },
        {
          "name": "Hades autocannon",
          "profiles": [
            {
              "id": "2c4b-5059-9578-8124",
              "name": "Hades autocannon",
              "type": "ranged",
              "range": "36\"",
              "attacks": "6",
              "skill": "3+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Armoured limbs",
          "profiles": [
            {
              "id": "f35d-7a13-92ea-ae2",
              "name": "Armoured limbs",
              "type": "melee",
              "range": "Melee",
              "attacks": "2",
              "skill": "3+",
              "strength": 6,
              "ap": 0,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Forgefiend jaws",
          "profiles": [
            {
              "id": "b6ae-ab11-3efe-a55a",
              "name": "Forgefiend jaws",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "3+",
              "strength": 7,
              "ap": 0,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "946c-d784-c8be-f21": {
      "name": "Havocs",
      "weapons": [
        {
          "name": "Power fist",
          "profiles": [
            {
              "id": "4199-c4ef-a7c6-aad1",
              "name": "Power fist",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Meltagun",
          "profiles": [
            {
              "id": "764a-68b9-164b-6651",
              "name": "Meltagun",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Havoc autocannon",
          "profiles": [
            {
              "id": "3a7-579e-445e-da32",
              "name": "Havoc autocannon",
              "type": "ranged",
              "range": "48\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 9,
              "ap": -1,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "c1cb-1e20-a75d-6eb2",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Havoc lascannon",
          "profiles": [
            {
              "id": "b618-2df3-c7b8-6921",
              "name": "Havoc lascannon",
              "type": "ranged",
              "range": "48\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 12,
              "ap": -3,
              "damage": "D6+1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Havoc missile launcher",
          "profiles": [
            {
              "id": "84c7-80eb-3a7c-5fed",
              "name": "Havoc missile launcher - frag",
              "type": "ranged",
              "range": "48\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast"
            },
            {
              "id": "7450-c34d-1993-6953",
              "name": "Havoc missile launcher - krak",
              "type": "ranged",
              "range": "48\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -2,
              "damage": "D6",
              "keywords": "-"
            }
          ],
          "rules": [
            "Blast"
          ]
        },
        {
          "name": "Havoc reaper chaincannon",
          "profiles": [
            {
              "id": "45d-e1eb-ac6c-11c",
              "name": "Havoc reaper chaincannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "8",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Havoc heavy bolter",
          "profiles": [
            {
              "id": "7556-9e9e-d22f-77c7",
              "name": "Havoc heavy bolter",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 5,
              "ap": -1,
              "damage": "2",
              "keywords": "Sustained Hits 1"
            }
          ],
          "rules": [
            "Sustained Hits"
          ]
        }
      ]
    },
    "615-e6bf-cfd2-9384": {
      "name": "Legionaries",
      "weapons": [
        {
          "name": "Accursed weapon",
          "profiles": [
            {
              "id": "ef75-c544-6241-1281",
              "name": "Accursed weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 5,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "aee9-ca1-a640-8f06",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Balefire tome",
          "profiles": [
            {
              "id": "9e8b-b8a6-753f-8321",
              "name": "Balefire tome",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 5,
              "ap": -1,
              "damage": "1",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Flamer",
          "profiles": [
            {
              "id": "e0b3-e2cc-5b69-87d2",
              "name": "Flamer",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Havoc autocannon",
          "profiles": [
            {
              "id": "1999-9bf-85e8-e231",
              "name": "Havoc autocannon",
              "type": "ranged",
              "range": "48\"",
              "attacks": "2",
              "skill": "4+",
              "strength": 9,
              "ap": -1,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Heavy bolter",
          "profiles": [
            {
              "id": "c699-3635-2050-d4f5",
              "name": "Heavy bolter",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "4+",
              "strength": 5,
              "ap": -1,
              "damage": "2",
              "keywords": "Heavy, Sustained Hits 1"
            }
          ],
          "rules": [
            "Heavy",
            "Sustained Hits"
          ]
        },
        {
          "name": "Lascannon",
          "profiles": [
            {
              "id": "b171-d132-74bd-4b7f",
              "name": "Lascannon",
              "type": "ranged",
              "range": "48\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 12,
              "ap": -3,
              "damage": "D6+1",
              "keywords": "Heavy"
            }
          ],
          "rules": [
            "Heavy"
          ]
        },
        {
          "name": "Missile launcher",
          "profiles": [
            {
              "id": "fac3-a91f-aad6-8513",
              "name": "Missile launcher - frag",
              "type": "ranged",
              "range": "48\"",
              "attacks": "D6",
              "skill": "4+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast, Heavy"
            },
            {
              "id": "f69b-59bf-5557-4440",
              "name": "Missile launcher - krak",
              "type": "ranged",
              "range": "48\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 9,
              "ap": -2,
              "damage": "D6",
              "keywords": "Heavy"
            }
          ],
          "rules": [
            "Blast",
            "Heavy"
          ]
        },
        {
          "name": "Reaper chaincannon",
          "profiles": [
            {
              "id": "8d01-550a-5c47-2a35",
              "name": "Reaper chaincannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "8",
              "skill": "4+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Heavy"
            }
          ],
          "rules": [
            "Heavy"
          ]
        },
        {
          "name": "Meltagun",
          "profiles": [
            {
              "id": "764a-68b9-164b-6651",
              "name": "Meltagun",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        }
      ]
    },
    "46e1-2159-7c26-9105": {
      "name": "Lord Discordant on Helstalker",
      "weapons": [
        {
          "name": "Bladed limbs",
          "profiles": [
            {
              "id": "b975-8164-a186-58c9",
              "name": "Bladed limbs",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 6,
              "ap": -1,
              "damage": "2",
              "keywords": "Extra Attacks"
            }
          ],
          "rules": [
            "Extra Attacks"
          ]
        },
        {
          "name": "Impaler chainglaive",
          "profiles": [
            {
              "id": "19c4-726a-471b-fa10",
              "name": "Impaler chainglaive",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 8,
              "ap": -3,
              "damage": "3",
              "keywords": "Lance"
            }
          ],
          "rules": [
            "Lance"
          ]
        },
        {
          "name": "Helstalker autocannon",
          "profiles": [
            {
              "id": "b347-fe10-f8cc-dcf4",
              "name": "Helstalker autocannon",
              "type": "ranged",
              "range": "48\"",
              "attacks": "3",
              "skill": "2+",
              "strength": 9,
              "ap": -1,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Baleflamer",
          "profiles": [
            {
              "id": "d2ef-b5d7-632d-a4ea",
              "name": "Baleflamer",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6+3",
              "skill": "N/A",
              "strength": 6,
              "ap": -1,
              "damage": "2",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Techno-virus injector",
          "profiles": [
            {
              "id": "60ce-5a91-a3f1-f79a",
              "name": "Techno-virus injector",
              "type": "melee",
              "range": "Melee",
              "attacks": "1",
              "skill": "3+",
              "strength": 3,
              "ap": -3,
              "damage": "2",
              "keywords": "Anti-VEHICLE 2+, Extra Attacks"
            }
          ],
          "rules": [
            "Extra Attacks",
            "Anti-"
          ]
        },
        {
          "name": "Magma cutter",
          "profiles": [
            {
              "id": "4c65-757-a60a-8f27",
              "name": "Magma cutter",
              "type": "ranged",
              "range": "6\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Bolt pistol",
          "profiles": [
            {
              "id": "2ff9-d27-c553-65c2",
              "name": "Bolt pistol",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "2+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        }
      ]
    },
    "da34-7071-8658-a453": {
      "name": "Master of Executions",
      "weapons": [
        {
          "name": "Axe of dismemberment",
          "profiles": [
            {
              "id": "b8af-fca3-362d-e30e",
              "name": "Axe of dismemberment",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 7,
              "ap": -2,
              "damage": "2",
              "keywords": "Devastating Wounds, Precision"
            }
          ],
          "rules": [
            "Devastating Wounds",
            "Precision"
          ]
        }
      ]
    },
    "287f-7d48-59cf-dc1e": {
      "name": "Master of Possession",
      "weapons": [
        {
          "name": "Rite of Possession",
          "profiles": [
            {
              "id": "c5b8-326c-cf2b-6798",
              "name": "Rite of Possession - witchfire",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": -3,
              "damage": "2",
              "keywords": "Anti-PSYKER 2+, Pistol, Precision, Psychic"
            },
            {
              "id": "5cb7-b494-5863-78ae",
              "name": "Rite of Possession - focused witchfire",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 6,
              "ap": -3,
              "damage": "3",
              "keywords": "Anti-PSYKER 2+, Hazardous, Pistol, Precision, Psychic"
            }
          ],
          "rules": [
            "Anti-",
            "Pistol",
            "Psychic",
            "Precision",
            "Hazardous"
          ]
        },
        {
          "name": "Staff of possession",
          "profiles": [
            {
              "id": "8998-93d9-a72c-b078",
              "name": "Staff of possession",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 6,
              "ap": -1,
              "damage": "D3",
              "keywords": "Anti-PSYKER 2+, Psychic"
            }
          ],
          "rules": [
            "Anti-",
            "Psychic"
          ]
        }
      ]
    },
    "2311-fa63-364-22a3": {
      "name": "Obliterators",
      "weapons": [
        {
          "name": "Crushing fists",
          "profiles": [
            {
              "id": "8588-852d-f3c8-5341",
              "name": "Crushing fists",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 9,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Fleshmetal guns",
          "profiles": [
            {
              "id": "32b3-2969-c4ec-b229",
              "name": "Fleshmetal guns - focused malice",
              "type": "ranged",
              "range": "18\"",
              "attacks": "D3",
              "skill": "3+",
              "strength": 12,
              "ap": -3,
              "damage": "4",
              "keywords": "Melta 2"
            },
            {
              "id": "3b9a-a07-e5c0-e5b4",
              "name": "Fleshmetal guns - ruinous salvo",
              "type": "ranged",
              "range": "24\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "2",
              "keywords": "Blast"
            },
            {
              "id": "5490-a3a2-1958-3615",
              "name": "Fleshmetal guns - warp hail",
              "type": "ranged",
              "range": "24\"",
              "attacks": "D6+3",
              "skill": "3+",
              "strength": 5,
              "ap": -1,
              "damage": "1",
              "keywords": "Sustained Hits 1"
            }
          ],
          "rules": [
            "Melta",
            "Blast",
            "Sustained Hits"
          ]
        }
      ]
    },
    "8dc5-4dcb-d77f-7d23": {
      "name": "Traitor Guardsmen Squad",
      "weapons": [
        {
          "name": "Chainsword",
          "profiles": [
            {
              "id": "30d8-5a7c-29b5-7fba",
              "name": "Chainsword",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "4+",
              "strength": 3,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Power weapon",
          "profiles": [
            {
              "id": "2639-ff92-f51c-17c4",
              "name": "Power weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "2",
              "skill": "4+",
              "strength": 4,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "93b1-211f-5577-222e",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "1",
              "skill": "4+",
              "strength": 3,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Corrupted pistol",
          "profiles": [
            {
              "id": "e495-1581-6df6-3b57",
              "name": "Corrupted pistol",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        },
        {
          "name": "Boltgun",
          "profiles": [
            {
              "id": "ed14-ca67-9004-7353",
              "name": "Boltgun",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 1"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Lasgun",
          "profiles": [
            {
              "id": "ed2c-62b7-e4d-e2fe",
              "name": "Lasgun",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 3,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 1"
            }
          ],
          "rules": []
        },
        {
          "name": "Flamer",
          "profiles": [
            {
              "id": "32dc-74b6-a239-d55d",
              "name": "Flamer",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Plasma gun",
          "profiles": [
            {
              "id": "73fa-10e-5e5b-b486",
              "name": "Plasma gun - standard",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 7,
              "ap": -2,
              "damage": "1",
              "keywords": "Rapid Fire 1"
            },
            {
              "id": "6f5d-6839-50d5-a577",
              "name": "Plasma gun - supercharge",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 8,
              "ap": -3,
              "damage": "2",
              "keywords": "Hazardous, Rapid Fire 1"
            }
          ],
          "rules": [
            "Rapid Fire",
            "Hazardous"
          ]
        },
        {
          "name": "Meltagun",
          "profiles": [
            {
              "id": "7ccb-e7f2-6c93-98e8",
              "name": "Meltagun",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Cultist sniper rifle",
          "profiles": [
            {
              "id": "68cd-53e6-b7fb-eb4",
              "name": "Cultist sniper rifle",
              "type": "ranged",
              "range": "36\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 4,
              "ap": -2,
              "damage": "2",
              "keywords": "Heavy, Precision"
            }
          ],
          "rules": [
            "Heavy",
            "Precision"
          ]
        },
        {
          "name": "Cultist grenade launcher",
          "profiles": [
            {
              "id": "ea8-a8b-39f3-3c4",
              "name": "Cultist grenade launcher - frag",
              "type": "ranged",
              "range": "24\"",
              "attacks": "D3",
              "skill": "4+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast"
            },
            {
              "id": "d64a-2151-c768-8e64",
              "name": "Cultist grenade launcher - krak",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 9,
              "ap": -2,
              "damage": "D3",
              "keywords": "-"
            }
          ],
          "rules": [
            "Blast"
          ]
        }
      ]
    },
    "3e98-7689-8bf0-96e0": {
      "name": "Venomcrawler",
      "weapons": [
        {
          "name": "Excruciator cannon",
          "profiles": [
            {
              "id": "1181-649c-fc2c-b1b2",
              "name": "Excruciator cannon",
              "type": "ranged",
              "range": "36\"",
              "attacks": "6",
              "skill": "3+",
              "strength": 6,
              "ap": -1,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Soulflayer tendrils and claws",
          "profiles": [
            {
              "id": "45c-1e82-d00b-c93c",
              "name": "Soulflayer tendrils and claws",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "3+",
              "strength": 6,
              "ap": -1,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "753d-4e02-eda3-4809": {
      "name": "War Dog Brigand",
      "weapons": [
        {
          "name": "Diabolus heavy stubber",
          "profiles": [
            {
              "id": "a4fb-4101-1b27-d2db",
              "name": "Diabolus heavy stubber",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 3"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Havoc multi-launcher",
          "profiles": [
            {
              "id": "a50f-8e7c-ff7f-9854",
              "name": "Havoc multi-launcher",
              "type": "ranged",
              "range": "48\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast, Indirect Fire"
            }
          ],
          "rules": [
            "Blast",
            "Indirect Fire"
          ]
        },
        {
          "name": "Armoured feet",
          "profiles": [
            {
              "id": "432a-109c-aeaa-84d2",
              "name": "Armoured feet",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Avenger chaincannon",
          "profiles": [
            {
              "id": "2ba6-4ed1-9dbe-cece",
              "name": "Avenger chaincannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "12",
              "skill": "3+",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Daemonbreath spear",
          "profiles": [
            {
              "id": "cae9-9335-5429-9523",
              "name": "Daemonbreath spear",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 12,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 4"
            }
          ],
          "rules": [
            "Melta"
          ]
        }
      ]
    },
    "e96b-ac98-7fd2-a155": {
      "name": "War Dog Karnivore",
      "weapons": [
        {
          "name": "Reaper chaintalon",
          "profiles": [
            {
              "id": "9a2a-73c8-7c8c-f19b",
              "name": "Reaper chaintalon",
              "type": "melee",
              "range": "Melee",
              "attacks": "12",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "1",
              "keywords": "Sustained Hits 1"
            }
          ],
          "rules": [
            "Sustained Hits"
          ]
        },
        {
          "name": "Slaughterclaw",
          "profiles": [
            {
              "id": "70ef-396b-bb23-6560",
              "name": "Slaughterclaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "3+",
              "strength": 12,
              "ap": -3,
              "damage": "D6+2",
              "keywords": "Sustained Hits 1"
            }
          ],
          "rules": [
            "Sustained Hits"
          ]
        },
        {
          "name": "Diabolus heavy stubber",
          "profiles": [
            {
              "id": "a4fb-4101-1b27-d2db",
              "name": "Diabolus heavy stubber",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 3"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Havoc multi-launcher",
          "profiles": [
            {
              "id": "a50f-8e7c-ff7f-9854",
              "name": "Havoc multi-launcher",
              "type": "ranged",
              "range": "48\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast, Indirect Fire"
            }
          ],
          "rules": [
            "Blast",
            "Indirect Fire"
          ]
        }
      ]
    },
    "440-a22a-eac1-b107": {
      "name": "Warpsmith",
      "weapons": [
        {
          "name": "Flamer tendril",
          "profiles": [
            {
              "id": "e28c-aac4-a480-5128",
              "name": "Flamer tendril",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 3,
              "ap": 0,
              "damage": "1",
              "keywords": "Ignores Cover, Pistol, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Pistol",
            "Torrent"
          ]
        },
        {
          "name": "Forge weapon",
          "profiles": [
            {
              "id": "7333-4e83-2db0-c04f",
              "name": "Forge weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 6,
              "ap": -2,
              "damage": "2",
              "keywords": "Anti-VEHICLE 4+"
            }
          ],
          "rules": [
            "Anti-"
          ]
        },
        {
          "name": "Melta tendril",
          "profiles": [
            {
              "id": "e6c4-817b-33ad-a7a3",
              "name": "Melta tendril",
              "type": "ranged",
              "range": "6\"",
              "attacks": "1",
              "skill": "2+",
              "strength": 8,
              "ap": -4,
              "damage": "D3",
              "keywords": "Melta 1, Pistol"
            }
          ],
          "rules": [
            "Pistol",
            "Melta"
          ]
        },
        {
          "name": "Plasma pistol",
          "profiles": [
            {
              "id": "229b-efc2-e2f5-5e56",
              "name": "Plasma pistol - standard",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "2+",
              "strength": 7,
              "ap": -2,
              "damage": "1",
              "keywords": "Pistol"
            },
            {
              "id": "cf81-8980-5b7b-8b84",
              "name": "Plasma pistol - supercharge",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "2+",
              "strength": 8,
              "ap": -3,
              "damage": "2",
              "keywords": "Hazardous, Pistol"
            }
          ],
          "rules": [
            "Hazardous",
            "Pistol"
          ]
        }
      ]
    }
  }
};
