import type { FactionUnitOptions } from "./types";
import { chaosChaosSpaceMarines } from "./chaos-chaos-space-marines";
import { imperiumAdeptusAstartesUltramarines } from "./imperium-adeptus-astartes-ultramarines";
import { imperiumAdeptusCustodes } from "./imperium-adeptus-custodes";
import { imperiumGreyKnights } from "./imperium-grey-knights";
import { xenosOrks } from "./xenos-orks";

// Generated by scripts/sync-unit-options.mjs. Do not edit by hand.
export const factionOptions: FactionUnitOptions[] = [
  chaosChaosSpaceMarines,
  imperiumAdeptusAstartesUltramarines,
  imperiumAdeptusCustodes,
  imperiumGreyKnights,
  xenosOrks,
];
