import type { FactionUnitOptions } from "./types";

// Generated by scripts/sync-unit-options.mjs. Do not edit by hand.
export const imperiumAdeptusAstartesUltramarines: FactionUnitOptions = {
  "catalogue": "Imperium - Adeptus Astartes - Ultramarines",
  "rules": {
    "Anti-": "Weapons with **[ANTI-KEYWORD X+]** in their profile are known as Anti weapons. Each time an attack is made with such a weapon against a target with the keyword after the word ‘Anti-’, an unmodified Wound roll of ‘x+’ scores a Critical Wound.",
    "Assault": "Weapons with **[ASSAULT]** in their profile are known as Assault weapons. If a unit that Advanced this turn contains any models equipped with Assault weapons, it is still eligible to shoot in this turn’s Shooting phase. When such a unit is selected to shoot, you can only resolve attacks using Assault weapons its models are equipped with.",
    "Blast": "Weapons with **[BLAST]** in their profile are known as Blast weapons, and they make a random number of attacks. Each time you determine how many attacks are made with a Blast weapon, add 1 to the result for every five models that were in the target unit when you selected it as the target (rounding down). Blast weapons can never be used to make attacks against a unit that is within Engagement Range of one or more units from the attacking model’s army (including its own unit).",
    "Devastating Wounds": "Weapons with **[DEVASTATING WOUNDS]** in their profile are known as Devastating Wounds weapons. Each time an attack is made with such a weapon, if that attack scores a Critical Wound, no saving throw of any kind can be made against that attack (including invulnerable saving throws). Such attacks are only allocated to models after all other attacks made by the attacking unit have been allocated and resolved. After that attack is allocated and after any modifiers are applied, it inflicts a number of mortal wounds on the target equal to the Damage characteristic of that attack, instead of inflicting damage normally.",
    "Extra Attacks": "Weapons with **[EXTRA ATTACKS]** in their profile are known as Extra Attacks weapons. Each time the bearer of one or more Extra Attacks weapons fights, it makes attacks with each of the Extra Attacks melee weapons it is equipped with and it makes attacks with one of the melee weapons it is equipped with that does not have the [EXTRA ATTACKS] ability (if any). The number of attacks made with an Extra Attacks weapon cannot be modified by other rules, unless that weapon’s name is explicitly specified in that rule.",
    "Hazardous": "Weapons with **[HAZARDOUS]** in their profile are known as Hazardous weapons. Each time a unit is selected to shoot or fight, after that unit has resolved all of its attacks, for each Hazardous weapon that targets were selected for when resolving those attacks, that unit must take one Hazardous test. To do so, roll one D6: on a 1, that test is failed. For each failed test you must resolve the following sequence (resolve each failed test one at a time): \n\n■ If possible, select one model in that unit that has lost one or more wounds and is equipped with one or more Hazardous weapons. \n■ Otherwise, if possible, select one model in that unit (excluding **^^Character^^** models) equipped with one or more Hazardous weapons. \n■ Otherwise, select one **^^Character^^** model in that unit equipped with one or more Hazardous weapons. \n\nIf a model was selected, that unit suffers 3 mortal wounds and when allocating those mortal wounds, they must be allocated to the selected model. \n\nIf a unit from a player’s army is selected as the target of the Fire Overwatch Stratagem in their opponent’s Charge phase, any mortal wounds inflicted by Hazardous tests are allocated after the charging unit has ended its Charge move.",
    "Heavy": "Weapons with **[HEAVY]** in their profile are known as Heavy weapons. Each time an attack is made with such a weapon, if the attacking model’s unit Remained Stationary this turn, add 1 to that attack’s Hit roll.",
    "Ignores Cover": "Weapons with **[IGNORES COVER]** in their profile are known as Ignores Cover weapons. Each time an attack is made with such a weapon, the target cannot have the Benefit of Cover against that attack.",
    "Melta": "Weapons with **[MELTA X]** in their profile are known as Melta weapons. Each time an attack made with such a weapon targets a unit within half that weapon’s range, that attack’s Damage characteristic is increased by the amount denoted by ‘x’.",
    "One Shot": "The bearer can only shoot with this weapon once per battle.",
    "Pistol": "Weapons with **[PISTOL]** in their profile are known as Pistols. If a unit contains any models equipped with Pistols, that unit is eligible to shoot in its controlling player’s Shooting phase even while it is within Engagement Range of one or more enemy units. When such a unit is selected to shoot, it can only resolve attacks using its Pistols and can only target one of the enemy units it is within Engagement Range of. In such circumstances, a Pistol can target an enemy unit even if other friendly units are within Engagement Range of the same enemy unit. \n\nIf a model is equipped with one or more Pistols, unless it is a **^^Monster^^** or **^^Vehicle^^** model, it can either shoot with its Pistols or with all of its other ranged weapons. Declare whether such a model will shoot with its Pistols or its other ranged weapons before selecting targets.",
    "Precision": "Weapons with **[PRECISION]** in their profile are known as Precision weapons. Each time an attack made with such a weapon successfully wounds an Attached unit, if a Character model in that unit is visible to the attacking model, the attacking model’s player can choose to have that attack allocated to that Character model instead of following the normal attack sequence.",
    "Rapid Fire": "Weapons with **[RAPID FIRE X]** in their profile are known as Rapid Fire weapons. Each time such a weapon targets a unit within half that weapon’s range, the Attacks characteristic of that weapon is increased by the amount denoted by ‘x’.",
    "Sustained Hits": "Weapons with **[SUSTAINED HITS X]** in their profile are known as Sustained Hits weapons. Each time an attack is made with such a weapon, if a Critical Hit is rolled, that attack scores a number of additional hits on the target as denoted by ‘x’",
    "Torrent": "Weapons with **[TORRENT]** in their profile are known as Torrent weapons. Each time an attack is made with such a weapon, that attack automatically hits the target.",
    "Twin-linked": "Weapons with **[TWIN-LINKED]** in their profile are known as Twin-linked weapons. Each time an attack is made with such a weapon, you can re-roll that attack’s Wound roll."
  },
  "units": {
    "129d-2da5-66f3-f4ec": {
      "name": "Aggressor Squad",
      "weapons": [
        {
          "name": "Auto Boltstorm Gauntlets",
          "profiles": [
            {
              "id": "250d-7b42-6542-8539",
              "name": "Auto Boltstorm Gauntlets",
              "type": "ranged",
              "range": "18\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Twin-linked"
            }
          ],
          "rules": [
            "Twin-linked"
          ]
        },
        {
          "name": "Fragstorm grenade launcher",
          "profiles": [
            {
              "id": "b2-9e09-20e1-6b64",
              "name": "Fragstorm grenade launcher",
              "type": "ranged",
              "range": "18\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        },
        {
          "name": "Flamestorm Gauntlets",
          "profiles": [
            {
              "id": "dcee-66cc-b8c2-b464",
              "name": "Flamestorm Gauntlets",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6+1",
              "skill": "N/A",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent, Twin-linked"
            }
          ],
          "rules": [
            "Torrent",
            "Ignores Cover",
            "Twin-linked"
          ]
        },
        {
          "name": "Twin power fist",
          "profiles": [
            {
              "id": "a776-4966-6429-2c97",
              "name": "Twin power fist",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "2",
              "keywords": "Twin-linked"
            }
          ],
          "rules": [
            "Twin-linked"
          ]
        }
      ]
    },
    "8a9d-11f-fad-bd0f": {
      "name": "Apothecary",
      "weapons": [
        {
          "name": "Reductor Pistol",
          "profiles": [
            {
              "id": "46d1-c07b-d1bb-4778",
              "name": "Reductor Pistol",
              "type": "ranged",
              "range": "3\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 4,
              "ap": -4,
              "damage": "2",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        },
        {
          "name": "Absolvor bolt pistol",
          "profiles": [
            {
              "id": "cb64-ddb1-cbc3-3621",
              "name": "Absolvor bolt pistol",
              "type": "ranged",
              "range": "18\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 5,
              "ap": -1,
              "damage": "2",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "7e7a-203c-a2ac-163f",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "7314-3c4a-36ab-a594": {
      "name": "Armiger Helverin",
      "weapons": [
        {
          "name": "Armiger autocannon",
          "profiles": [
            {
              "id": "3d6c-b927-b515-c0d8",
              "name": "Armiger autocannon",
              "type": "ranged",
              "range": "48\"",
              "attacks": "4",
              "skill": "3+",
              "strength": 9,
              "ap": -1,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Meltagun",
          "profiles": [
            {
              "id": "4b6f-2df5-d7b6-34dd",
              "name": "Meltagun",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Questoris heavy stubber",
          "profiles": [
            {
              "id": "3b13-7770-1d2b-9e66",
              "name": "Questoris heavy stubber",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Rapid Fire 3"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Armoured feet",
          "profiles": [
            {
              "id": "b6b7-cce0-ad60-bdf4",
              "name": "Armoured feet",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "5bbd-c5d3-58d7-e391": {
      "name": "Armiger Warglaive",
      "weapons": [
        {
          "name": "Reaper chain-cleaver",
          "profiles": [
            {
              "id": "3a79-406d-aaa7-ed6c",
              "name": "Reaper chain-cleaver - strike",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 10,
              "ap": -3,
              "damage": "3",
              "keywords": "-"
            },
            {
              "id": "5e11-8d35-b7a7-ba38",
              "name": "Reaper chain-cleaver - sweep",
              "type": "melee",
              "range": "Melee",
              "attacks": "8",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Thermal spear",
          "profiles": [
            {
              "id": "38d-4520-1309-4074",
              "name": "Thermal spear",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 12,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 4"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Meltagun",
          "profiles": [
            {
              "id": "4b6f-2df5-d7b6-34dd",
              "name": "Meltagun",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Questoris heavy stubber",
          "profiles": [
            {
              "id": "3b13-7770-1d2b-9e66",
              "name": "Questoris heavy stubber",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Rapid Fire 3"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        }
      ]
    },
    "d6c3-e9d2-430d-6c2f": {
      "name": "Eliminator Squad",
      "weapons": [
        {
          "name": "Instigator Bolt Carbine",
          "profiles": [
            {
              "id": "ffe3-a16e-ce0a-98a4",
              "name": "Instigator Bolt Carbine",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 4,
              "ap": -2,
              "damage": "2",
              "keywords": "Precision"
            }
          ],
          "rules": [
            "Precision"
          ]
        },
        {
          "name": "Bolt Sniper Rifle",
          "profiles": [
            {
              "id": "fb52-d382-545d-d0ee",
              "name": "Bolt Sniper Rifle",
              "type": "ranged",
              "range": "36\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 5,
              "ap": -2,
              "damage": "3",
              "keywords": "Heavy, Precision"
            }
          ],
          "rules": [
            "Precision",
            "Heavy"
          ]
        },
        {
          "name": "Las fusil",
          "profiles": [
            {
              "id": "b2aa-30c5-6209-acf6",
              "name": "Las fusil",
              "type": "ranged",
              "range": "36\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -3,
              "damage": "D6",
              "keywords": "Heavy"
            }
          ],
          "rules": [
            "Heavy"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "5047-1299-63ca-db8a",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Bolt pistol",
          "profiles": [
            {
              "id": "d093-797a-4c76-eea3",
              "name": "Bolt pistol",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        }
      ]
    },
    "7102-b3a4-9bfc-1b84": {
      "name": "Hellblaster Squad",
      "weapons": [
        {
          "name": "Bolt pistol",
          "profiles": [
            {
              "id": "d093-797a-4c76-eea3",
              "name": "Bolt pistol",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        },
        {
          "name": "Plasma pistol",
          "profiles": [
            {
              "id": "4a80-2594-8839-c0bf",
              "name": "Plasma pistol - supercharge",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 8,
              "ap": -3,
              "damage": "2",
              "keywords": "Hazardous, Pistol"
            },
            {
              "id": "5edb-fb23-55e8-8415",
              "name": "Plasma pistol - standard",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 7,
              "ap": -2,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Hazardous",
            "Pistol"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "5047-1299-63ca-db8a",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Plasma Incinerator",
          "profiles": [
            {
              "id": "261b-f672-2999-265f",
              "name": "Plasma Incinerator - Standard",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 7,
              "ap": -2,
              "damage": "1",
              "keywords": "Assault, Heavy"
            },
            {
              "id": "a039-cb1b-3837-ba8b",
              "name": "Plasma Incinerator - Supercharge",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 8,
              "ap": -3,
              "damage": "2",
              "keywords": "Assault, Heavy, Hazardous"
            }
          ],
          "rules": [
            "Hazardous",
            "Heavy",
            "Assault"
          ]
        }
      ]
    },
    "bfb1-7512-e1a3-9fa2": {
      "name": "Impulsor",
      "weapons": [
        {
          "name": "Ironhail Skytalon Array",
          "profiles": [
            {
              "id": "c584-4082-2c05-a4ba",
              "name": "Ironhail Skytalon Array",
              "type": "ranged",
              "range": "36\"",
              "attacks": "8",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Anti-Fly 4+, Sustained Hits 1"
            }
          ],
          "rules": [
            "Sustained Hits",
            "Anti-"
          ]
        },
        {
          "name": "Bellicatus Missile Array",
          "profiles": [
            {
              "id": "a4d0-6b1e-b6e8-f6ce",
              "name": "Bellicatus Missile Array - Frag",
              "type": "ranged",
              "range": "48\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast"
            },
            {
              "id": "3e8b-ef9f-3ada-0658",
              "name": "Bellicatus Missile Array - Icarus",
              "type": "ranged",
              "range": "48\"",
              "attacks": "D3",
              "skill": "3+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "Anti-Fly 2+"
            },
            {
              "id": "59bc-a344-af08-2111",
              "name": "Bellicatus Missile Array - Krak",
              "type": "ranged",
              "range": "48\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "D6",
              "keywords": "-"
            }
          ],
          "rules": [
            "Anti-",
            "Blast"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "83a0-da0c-752f-b4b3",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Fragstorm grenade launcher",
          "profiles": [
            {
              "id": "b2-9e09-20e1-6b64",
              "name": "Fragstorm grenade launcher",
              "type": "ranged",
              "range": "18\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        },
        {
          "name": "Armoured Hull",
          "profiles": [
            {
              "id": "b695-6a40-93a3-f048",
              "name": "Armoured Hull",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "4+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Ironhail Heavy Stubber",
          "profiles": [
            {
              "id": "9111-913e-ec42-e830",
              "name": "Ironhail Heavy Stubber",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 3"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        }
      ]
    },
    "8da0-4570-c3c-819f": {
      "name": "Intercessor Squad",
      "weapons": [
        {
          "name": "Bolt Rifle",
          "profiles": [
            {
              "id": "837b-6918-767-152b",
              "name": "Bolt Rifle",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Assault, Heavy"
            }
          ],
          "rules": [
            "Assault",
            "Heavy"
          ]
        },
        {
          "name": "Astartes grenade launcher",
          "profiles": [
            {
              "id": "e307-f8d3-d06c-9dd9",
              "name": "Astartes grenade launcher - krak",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -2,
              "damage": "D3",
              "keywords": "-"
            },
            {
              "id": "960c-e26b-b802-53d1",
              "name": "Astartes grenade launcher - frag",
              "type": "ranged",
              "range": "24\"",
              "attacks": "D3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        },
        {
          "name": "Hand flamer",
          "profiles": [
            {
              "id": "5dec-ac64-4bf5-7d6c",
              "name": "Hand flamer",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 3,
              "ap": 0,
              "damage": "1",
              "keywords": "Ignores Cover, Pistol, Torrent"
            }
          ],
          "rules": [
            "Pistol",
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Power weapon",
          "profiles": [
            {
              "id": "8f2f-6d13-36c5-eded",
              "name": "Power weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 5,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Plasma pistol",
          "profiles": [
            {
              "id": "4a80-2594-8839-c0bf",
              "name": "Plasma pistol - supercharge",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 8,
              "ap": -3,
              "damage": "2",
              "keywords": "Hazardous, Pistol"
            },
            {
              "id": "5edb-fb23-55e8-8415",
              "name": "Plasma pistol - standard",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 7,
              "ap": -2,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Hazardous",
            "Pistol"
          ]
        },
        {
          "name": "Astartes Chainsword",
          "profiles": [
            {
              "id": "a474-3508-518d-1582",
              "name": "Astartes Chainsword",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Power fist",
          "profiles": [
            {
              "id": "3a24-34af-7558-5365",
              "name": "Power fist",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Thunder Hammer",
          "profiles": [
            {
              "id": "7d4-47b7-439b-b2ca",
              "name": "Thunder Hammer",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "4+",
              "strength": 8,
              "ap": -2,
              "damage": "2",
              "keywords": "Devastating Wounds"
            }
          ],
          "rules": [
            "Devastating Wounds"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "5047-1299-63ca-db8a",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Bolt pistol",
          "profiles": [
            {
              "id": "d093-797a-4c76-eea3",
              "name": "Bolt pistol",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        }
      ]
    },
    "d361-a36e-1448-264d": {
      "name": "Land Raider Redeemer",
      "weapons": [
        {
          "name": "Flamestorm Cannon",
          "profiles": [
            {
              "id": "b61e-d7bc-b6ec-6313",
              "name": "Flamestorm Cannon",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6+3",
              "skill": "N/A",
              "strength": 6,
              "ap": -2,
              "damage": "2",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Torrent",
            "Ignores Cover"
          ]
        },
        {
          "name": "Armoured Tracks",
          "profiles": [
            {
              "id": "5346-57b-924-13b4",
              "name": "Armoured Tracks",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "4+",
              "strength": 8,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Hunter-killer missile",
          "profiles": [
            {
              "id": "11a9-2c2b-fbea-4bbc",
              "name": "Hunter-killer missile",
              "type": "ranged",
              "range": "48\"",
              "attacks": "1",
              "skill": "2+",
              "strength": 14,
              "ap": -3,
              "damage": "D6",
              "keywords": "One Shot"
            }
          ],
          "rules": [
            "One Shot"
          ]
        },
        {
          "name": "Multi-melta",
          "profiles": [
            {
              "id": "e7ca-a953-c254-dc54",
              "name": "Multi-melta",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "83a0-da0c-752f-b4b3",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Twin assault cannon",
          "profiles": [
            {
              "id": "e305-23e6-6fd3-ac5f",
              "name": "Twin assault cannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "6",
              "skill": "3+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "Devastating wounds, Twin-linked"
            }
          ],
          "rules": [
            "Twin-linked",
            "Devastating Wounds"
          ]
        }
      ]
    },
    "a136-76f7-34d1-8035": {
      "name": "Marneus Calgar in Armour of Antilochus",
      "weapons": [
        {
          "name": "Gauntlets of Ultramar",
          "profiles": [
            {
              "id": "3a4f-e9f6-7e4f-70ec",
              "name": "Gauntlets of Ultramar",
              "type": "ranged",
              "range": "18\"",
              "attacks": "4",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Pistol, Twin-linked"
            },
            {
              "id": "e429-5ee8-6d5f-8277",
              "name": "Gauntlets of Ultramar",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "2+",
              "strength": 8,
              "ap": -3,
              "damage": "3",
              "keywords": "Twin-linked"
            }
          ],
          "rules": [
            "Pistol",
            "Twin-linked"
          ]
        }
      ]
    },
    "1d94-b3c8-9205-827e": {
      "name": "Redemptor Dreadnought",
      "weapons": [
        {
          "name": "Redemptor Fist",
          "profiles": [
            {
              "id": "9c53-a84a-fc78-d05d",
              "name": "Redemptor Fist",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "3+",
              "strength": 12,
              "ap": -2,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Macro Plasma Incinerator",
          "profiles": [
            {
              "id": "e54-149a-9924-afe",
              "name": "Macro Plasma Incinerator - Standard",
              "type": "ranged",
              "range": "36\"",
              "attacks": "D6+1",
              "skill": "3+",
              "strength": 8,
              "ap": -3,
              "damage": "2",
              "keywords": "Blast"
            },
            {
              "id": "256a-8119-50f8-259",
              "name": "Macro Plasma Incinerator - Supercharge",
              "type": "ranged",
              "range": "36\"",
              "attacks": "D6+1",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "3",
              "keywords": "Blast, Hazardous"
            }
          ],
          "rules": [
            "Hazardous",
            "Blast"
          ]
        },
        {
          "name": "Heavy Onslaught Gatling Cannon",
          "profiles": [
            {
              "id": "9a6f-e83b-69b1-8dbf",
              "name": "Heavy Onslaught Gatling Cannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "12",
              "skill": "3+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "Devastating Wounds"
            }
          ],
          "rules": [
            "Devastating Wounds"
          ]
        },
        {
          "name": "Heavy Flamer",
          "profiles": [
            {
              "id": "8158-c8b3-6940-5199",
              "name": "Heavy Flamer",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 5,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Onslaught gatling cannon",
          "profiles": [
            {
              "id": "a084-430f-5fb6-6ef2",
              "name": "Onslaught gatling cannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "8",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Devastating Wounds"
            }
          ],
          "rules": [
            "Devastating Wounds"
          ]
        },
        {
          "name": "Twin Fragstorm Grenade Launcher",
          "profiles": [
            {
              "id": "1dcf-9522-85c0-2605",
              "name": "Twin Fragstorm Grenade Launcher",
              "type": "ranged",
              "range": "18\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast, Twin-linked"
            }
          ],
          "rules": [
            "Blast",
            "Twin-linked"
          ]
        },
        {
          "name": "Twin Storm Bolter",
          "profiles": [
            {
              "id": "27cb-34a-cb99-600b",
              "name": "Twin Storm Bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2, Twin-linked"
            }
          ],
          "rules": [
            "Rapid Fire",
            "Twin-linked"
          ]
        },
        {
          "name": "Icarus Rocket Pod",
          "profiles": [
            {
              "id": "c387-f167-8913-822c",
              "name": "Icarus Rocket Pod",
              "type": "ranged",
              "range": "24\"",
              "attacks": "D3",
              "skill": "3+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "Anti-fly 2+"
            }
          ],
          "rules": [
            "Anti-"
          ]
        }
      ]
    },
    "e671-cd3a-2b03-3954": {
      "name": "Techmarine",
      "weapons": [
        {
          "name": "Forge Bolter",
          "profiles": [
            {
              "id": "2aea-ded0-1a03-3242",
              "name": "Forge Bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "3",
              "skill": "2+",
              "strength": 5,
              "ap": -1,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Grav-pistol",
          "profiles": [
            {
              "id": "66c9-79a1-6f19-5849",
              "name": "Grav-pistol",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Anti-vehicle 2+, Pistol"
            }
          ],
          "rules": [
            "Pistol",
            "Anti-"
          ]
        },
        {
          "name": "Omnissian power axe",
          "profiles": [
            {
              "id": "2012-125d-f852-eb24",
              "name": "Omnissian power axe",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 6,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Servo-arm",
          "profiles": [
            {
              "id": "ba94-462a-52f0-ead",
              "name": "Servo-arm",
              "type": "melee",
              "range": "Melee",
              "attacks": "1",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "3",
              "keywords": "Extra Attacks"
            }
          ],
          "rules": [
            "Extra Attacks"
          ]
        }
      ]
    }
  }
};
