import type { FactionUnitOptions } from "./types";

// Generated by scripts/sync-unit-options.mjs. Do not edit by hand.
export const imperiumGreyKnights: FactionUnitOptions = {
  "catalogue": "Imperium - Grey Knights",
  "rules": {
    "Anti-": "Weapons with **[ANTI-KEYWORD X+]** in their profile are known as Anti weapons. Each time an attack is made with such a weapon against a target with the keyword after the word ‘Anti-’, an unmodified Wound roll of ‘x+’ scores a Critical Wound.",
    "Blast": "Weapons with **[BLAST]** in their profile are known as Blast weapons, and they make a random number of attacks. Each time you determine how many attacks are made with a Blast weapon, add 1 to the result for every five models that were in the target unit when you selected it as the target (rounding down). Blast weapons can never be used to make attacks against a unit that is within Engagement Range of one or more units from the attacking model’s army (including its own unit).",
    "Devastating Wounds": "Weapons with **[DEVASTATING WOUNDS]** in their profile are known as Devastating Wounds weapons. Each time an attack is made with such a weapon, if that attack scores a Critical Wound, no saving throw of any kind can be made against that attack (including invulnerable saving throws). Such attacks are only allocated to models after all other attacks made by the attacking unit have been allocated and resolved. After that attack is allocated and after any modifiers are applied, it inflicts a number of mortal wounds on the target equal to the Damage characteristic of that attack, instead of inflicting damage normally.",
    "Hazardous": "Weapons with **[HAZARDOUS]** in their profile are known as Hazardous weapons. Each time a unit is selected to shoot or fight, after that unit has resolved all of its attacks, for each Hazardous weapon that targets were selected for when resolving those attacks, that unit must take one Hazardous test. To do so, roll one D6: on a 1, that test is failed. For each failed test you must resolve the following sequence (resolve each failed test one at a time): \n\n■ If possible, select one model in that unit that has lost one or more wounds and is equipped with one or more Hazardous weapons. \n■ Otherwise, if possible, select one model in that unit (excluding **^^Character^^** models) equipped with one or more Hazardous weapons. \n■ Otherwise, select one **^^Character^^** model in that unit equipped with one or more Hazardous weapons. \n\nIf a model was selected, that unit suffers 3 mortal wounds and when allocating those mortal wounds, they must be allocated to the selected model. \n\nIf a unit from a player’s army is selected as the target of the Fire Overwatch Stratagem in their opponent’s Charge phase, any mortal wounds inflicted by Hazardous tests are allocated after the charging unit has ended its Charge move.",
    "Ignores Cover": "Weapons with **[IGNORES COVER]** in their profile are known as Ignores Cover weapons. Each time an attack is made with such a weapon, the target cannot have the Benefit of Cover against that attack.",
    "Melta": "Weapons with **[MELTA X]** in their profile are known as Melta weapons. Each time an attack made with such a weapon targets a unit within half that weapon’s range, that attack’s Damage characteristic is increased by the amount denoted by ‘x’.",
    "Precision": "Weapons with **[PRECISION]** in their profile are known as Precision weapons. Each time an attack made with such a weapon successfully wounds an Attached unit, if a Character model in that unit is visible to the attacking model, the attacking model’s player can choose to have that attack allocated to that Character model instead of following the normal attack sequence.",
    "Psychic": "Some weapons and abilities can only be used by **^^Psykers^^**. Such weapons and abilities are tagged with the word 'Psychic'. If a Psychic weapon or ability causes any unit to suffer one or more wounds, each of those wounds is considered to have been inflicted by a Psychic Attack.",
    "Rapid Fire": "Weapons with **[RAPID FIRE X]** in their profile are known as Rapid Fire weapons. Each time such a weapon targets a unit within half that weapon’s range, the Attacks characteristic of that weapon is increased by the amount denoted by ‘x’.",
    "Sustained Hits": "Weapons with **[SUSTAINED HITS X]** in their profile are known as Sustained Hits weapons. Each time an attack is made with such a weapon, if a Critical Hit is rolled, that attack scores a number of additional hits on the target as denoted by ‘x’",
    "Torrent": "Weapons with **[TORRENT]** in their profile are known as Torrent weapons. Each time an attack is made with such a weapon, that attack automatically hits the target.",
    "Twin-linked": "Weapons with **[TWIN-LINKED]** in their profile are known as Twin-linked weapons. Each time an attack is made with such a weapon, you can re-roll that attack’s Wound roll."
  },
  "units": {
    "7314-3c4a-36ab-a594": {
      "name": "Armiger Helverin",
      "weapons": [
        {
          "name": "Armiger autocannon",
          "profiles": [
            {
              "id": "3d6c-b927-b515-c0d8",
              "name": "Armiger autocannon",
              "type": "ranged",
              "range": "48\"",
              "attacks": "4",
              "skill": "3+",
              "strength": 9,
              "ap": -1,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Meltagun",
          "profiles": [
            {
              "id": "4b6f-2df5-d7b6-34dd",
              "name": "Meltagun",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Questoris heavy stubber",
          "profiles": [
            {
              "id": "3b13-7770-1d2b-9e66",
              "name": "Questoris heavy stubber",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Rapid Fire 3"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Armoured feet",
          "profiles": [
            {
              "id": "b6b7-cce0-ad60-bdf4",
              "name": "Armoured feet",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "5bbd-c5d3-58d7-e391": {
      "name": "Armiger Warglaive",
      "weapons": [
        {
          "name": "Reaper chain-cleaver",
          "profiles": [
            {
              "id": "3a79-406d-aaa7-ed6c",
              "name": "Reaper chain-cleaver - strike",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 10,
              "ap": -3,
              "damage": "3",
              "keywords": "-"
            },
            {
              "id": "5e11-8d35-b7a7-ba38",
              "name": "Reaper chain-cleaver - sweep",
              "type": "melee",
              "range": "Melee",
              "attacks": "8",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Thermal spear",
          "profiles": [
            {
              "id": "38d-4520-1309-4074",
              "name": "Thermal spear",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 12,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 4"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Meltagun",
          "profiles": [
            {
              "id": "4b6f-2df5-d7b6-34dd",
              "name": "Meltagun",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Questoris heavy stubber",
          "profiles": [
            {
              "id": "3b13-7770-1d2b-9e66",
              "name": "Questoris heavy stubber",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Rapid Fire 3"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        }
      ]
    },
    "5412-1f01-b7cc-bf12": {
      "name": "Brotherhood Librarian",
      "weapons": [
        {
          "name": "Nemesis force weapon",
          "profiles": [
            {
              "id": "8404-b7bc-4d0f-6136",
              "name": "Nemesis force weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "2+",
              "strength": 6,
              "ap": -1,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Combi-weapon",
          "profiles": [
            {
              "id": "d680-44f9-1df9-8e42",
              "name": "Combi-weapon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Anti-infantry 4+, Devastating Wounds, Rapid Fire 1"
            }
          ],
          "rules": [
            "Anti-",
            "Rapid Fire",
            "Devastating Wounds"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "9756-e60b-776b-cf23",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Vortex of Doom",
          "profiles": [
            {
              "id": "3820-e568-e53-96f2",
              "name": "Vortex of Doom",
              "type": "ranged",
              "range": "18\"",
              "attacks": "D6+3",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "2",
              "keywords": "Blast, Psychic"
            }
          ],
          "rules": [
            "Psychic",
            "Blast"
          ]
        }
      ]
    },
    "a037-a89c-f59f-8b1e": {
      "name": "Brotherhood Terminator Squad",
      "weapons": [
        {
          "name": "Nemesis force weapon",
          "profiles": [
            {
              "id": "e61d-6154-44ab-89ab",
              "name": "Nemesis force weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 6,
              "ap": -2,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "9756-e60b-776b-cf23",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Incinerator",
          "profiles": [
            {
              "id": "2128-f1c4-afbc-82af",
              "name": "Incinerator",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Psycannon",
          "profiles": [
            {
              "id": "3701-b2f4-a180-cd80",
              "name": "Psycannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Psilencer",
          "profiles": [
            {
              "id": "4063-edc3-baa4-6475",
              "name": "Psilencer",
              "type": "ranged",
              "range": "24\"",
              "attacks": "6",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Precision, Psychic, Sustained Hits 1"
            }
          ],
          "rules": [
            "Sustained Hits",
            "Precision",
            "Psychic"
          ]
        }
      ]
    },
    "9ddb-760d-8cf7-1c8a": {
      "name": "Castellan Crowe",
      "weapons": [
        {
          "name": "Purifying Flame",
          "profiles": [
            {
              "id": "73f3-22f9-3831-441a",
              "name": "Purifying Flame",
              "type": "ranged",
              "range": "18\"",
              "attacks": "3",
              "skill": "2+",
              "strength": 4,
              "ap": -2,
              "damage": "1",
              "keywords": "Anti-Infantry 2+, Ignores Cover, Psychic"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Psychic",
            "Anti-"
          ]
        },
        {
          "name": "Black Blade of Antwyr",
          "profiles": [
            {
              "id": "dae1-9183-96d9-6ccd",
              "name": "Black Blade of Antwyr",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 6,
              "ap": -2,
              "damage": "2",
              "keywords": "Devastating Wounds, Precision"
            }
          ],
          "rules": [
            "Devastating Wounds",
            "Precision"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "d032-863c-420d-d110",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        }
      ]
    },
    "3625-f9f1-122b-bf9d": {
      "name": "Grand Master in Nemesis Dreadknight",
      "weapons": [
        {
          "name": "Nemesis mace",
          "profiles": [
            {
              "id": "23f1-d294-a434-9658",
              "name": "Nemesis mace",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 6,
              "ap": -3,
              "damage": "3",
              "keywords": "Anti-Character 2+, Precision, Psychic"
            }
          ],
          "rules": [
            "Precision",
            "Anti-",
            "Psychic"
          ]
        },
        {
          "name": "Nemesis flail",
          "profiles": [
            {
              "id": "6104-3c01-f94d-b60c",
              "name": "Nemesis flail",
              "type": "melee",
              "range": "Melee",
              "attacks": "10",
              "skill": "2+",
              "strength": 5,
              "ap": -1,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Dreadfists",
          "profiles": [
            {
              "id": "9291-62df-94b4-6e2c",
              "name": "Dreadfists",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "2+",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Nemesis daemon greathammer",
          "profiles": [
            {
              "id": "48db-1777-7d99-7f48",
              "name": "Nemesis daemon greathammer",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "3+",
              "strength": 14,
              "ap": -3,
              "damage": "D6+1",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Nemesis greatsword",
          "profiles": [
            {
              "id": "bfc1-ea26-dbb7-6027",
              "name": "Nemesis greatsword - strike",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 10,
              "ap": -2,
              "damage": "D6",
              "keywords": "Psychic"
            },
            {
              "id": "28af-7d69-c39a-d65",
              "name": "Nemesis greatsword - sweep",
              "type": "melee",
              "range": "Melee",
              "attacks": "10",
              "skill": "2+",
              "strength": 5,
              "ap": -1,
              "damage": "1",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Sublimator",
          "profiles": [
            {
              "id": "067c-1a73-e0b0-3b80",
              "name": "Sublimator",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 4, Psychic, Twin-linked"
            }
          ],
          "rules": [
            "Psychic",
            "Melta",
            "Twin-linked"
          ]
        },
        {
          "name": "Gatling psilencer",
          "profiles": [
            {
              "id": "5dd4-fb4c-f1d0-86ec",
              "name": "Gatling psilencer",
              "type": "ranged",
              "range": "24\"",
              "attacks": "12",
              "skill": "3+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "Psychic, Sustained Hits 1"
            }
          ],
          "rules": [
            "Psychic",
            "Sustained Hits"
          ]
        },
        {
          "name": "Heavy incinerator",
          "profiles": [
            {
              "id": "e53e-235a-53e1-c196",
              "name": "Heavy incinerator",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2D6",
              "skill": "N/A",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Torrent",
            "Ignores Cover"
          ]
        },
        {
          "name": "Heavy psycannon",
          "profiles": [
            {
              "id": "4d47-648-9923-a782",
              "name": "Heavy psycannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "6",
              "skill": "3+",
              "strength": 10,
              "ap": -2,
              "damage": "3",
              "keywords": "Ignores Cover, Psychic"
            }
          ],
          "rules": [
            "Psychic",
            "Ignores Cover"
          ]
        },
        {
          "name": "Fragstorm grenade launcher",
          "profiles": [
            {
              "id": "4db0-66d3-f31e-1b81",
              "name": "Fragstorm grenade launcher",
              "type": "ranged",
              "range": "18\"",
              "attacks": "D6",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        }
      ]
    },
    "7256-bb3a-3e79-31fe": {
      "name": "Grand Master Voldus",
      "weapons": [
        {
          "name": "Malleus Argyrum",
          "profiles": [
            {
              "id": "9c20-33ed-5139-f2df",
              "name": "Malleus Argyrum",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 10,
              "ap": -2,
              "damage": "3",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Searing Purity",
          "profiles": [
            {
              "id": "0227-3d63-da92-f4c8",
              "name": "Searing Purity",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D3+1",
              "skill": "2+",
              "strength": 12,
              "ap": -2,
              "damage": "2",
              "keywords": "Devastating Wounds, Psychic"
            }
          ],
          "rules": [
            "Devastating Wounds",
            "Psychic"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "d032-863c-420d-d110",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        }
      ]
    },
    "d9f7-71b7-8e67-7f44": {
      "name": "Interceptor Squad",
      "weapons": [
        {
          "name": "Nemesis force weapon",
          "profiles": [
            {
              "id": "6d43-4f42-80da-0c3a",
              "name": "Nemesis force weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 6,
              "ap": -2,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "9756-e60b-776b-cf23",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "d90e-6422-f76d-8bae",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Incinerator",
          "profiles": [
            {
              "id": "2128-f1c4-afbc-82af",
              "name": "Incinerator",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Psilencer",
          "profiles": [
            {
              "id": "4063-edc3-baa4-6475",
              "name": "Psilencer",
              "type": "ranged",
              "range": "24\"",
              "attacks": "6",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Precision, Psychic, Sustained Hits 1"
            }
          ],
          "rules": [
            "Sustained Hits",
            "Precision",
            "Psychic"
          ]
        },
        {
          "name": "Psycannon",
          "profiles": [
            {
              "id": "3701-b2f4-a180-cd80",
              "name": "Psycannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        }
      ]
    },
    "6528-4634-c2cf-2840": {
      "name": "Paladin Squad",
      "weapons": [
        {
          "name": "Nemesis force weapon",
          "profiles": [
            {
              "id": "3c70-95c2-d686-f2ee",
              "name": "Nemesis force weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "2+",
              "strength": 6,
              "ap": -2,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "d032-863c-420d-d110",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Incinerator",
          "profiles": [
            {
              "id": "2128-f1c4-afbc-82af",
              "name": "Incinerator",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Psycannon",
          "profiles": [
            {
              "id": "9746-351c-3528-ba15",
              "name": "Psycannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "3",
              "skill": "2+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Psilencer",
          "profiles": [
            {
              "id": "d93e-1c3a-3aa3-92fe",
              "name": "Psilencer",
              "type": "ranged",
              "range": "24\"",
              "attacks": "6",
              "skill": "2+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Precision, Psychic, Sustained Hits 1"
            }
          ],
          "rules": [
            "Sustained Hits",
            "Psychic",
            "Precision"
          ]
        }
      ]
    },
    "8865-df22-1629-bf02": {
      "name": "Purifier Squad",
      "weapons": [
        {
          "name": "Nemesis force weapon",
          "profiles": [
            {
              "id": "6d43-4f42-80da-0c3a",
              "name": "Nemesis force weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 6,
              "ap": -2,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "9756-e60b-776b-cf23",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Purifying Flame",
          "profiles": [
            {
              "id": "8208-0103-d2f9-5859",
              "name": "Purifying Flame",
              "type": "ranged",
              "range": "18\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 4,
              "ap": -2,
              "damage": "1",
              "keywords": "Anti-Infantry 2+, Ignores Cover, Psychic"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Psychic",
            "Anti-"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "d90e-6422-f76d-8bae",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Incinerator",
          "profiles": [
            {
              "id": "2128-f1c4-afbc-82af",
              "name": "Incinerator",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Psilencer",
          "profiles": [
            {
              "id": "4063-edc3-baa4-6475",
              "name": "Psilencer",
              "type": "ranged",
              "range": "24\"",
              "attacks": "6",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Precision, Psychic, Sustained Hits 1"
            }
          ],
          "rules": [
            "Sustained Hits",
            "Precision",
            "Psychic"
          ]
        },
        {
          "name": "Psycannon",
          "profiles": [
            {
              "id": "3701-b2f4-a180-cd80",
              "name": "Psycannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        }
      ]
    },
    "d81f-c9ac-e338-ba37": {
      "name": "Strike Squad",
      "weapons": [
        {
          "name": "Nemesis force weapon",
          "profiles": [
            {
              "id": "6d43-4f42-80da-0c3a",
              "name": "Nemesis force weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 6,
              "ap": -2,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "9756-e60b-776b-cf23",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Incinerator",
          "profiles": [
            {
              "id": "2128-f1c4-afbc-82af",
              "name": "Incinerator",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Psycannon",
          "profiles": [
            {
              "id": "3701-b2f4-a180-cd80",
              "name": "Psycannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "Psychic"
            }
          ],
          "rules": [
            "Psychic"
          ]
        },
        {
          "name": "Psilencer",
          "profiles": [
            {
              "id": "4063-edc3-baa4-6475",
              "name": "Psilencer",
              "type": "ranged",
              "range": "24\"",
              "attacks": "6",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Precision, Psychic, Sustained Hits 1"
            }
          ],
          "rules": [
            "Sustained Hits",
            "Precision",
            "Psychic"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "d90e-6422-f76d-8bae",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "bd43-b303-66e0-4c10": {
      "name": "Venerable Dreadnought",
      "weapons": [
        {
          "name": "Assault cannon",
          "profiles": [
            {
              "id": "efe0-8125-9e39-3187",
              "name": "Assault cannon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "6",
              "skill": "3+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "Devastating Wounds"
            }
          ],
          "rules": [
            "Devastating Wounds"
          ]
        },
        {
          "name": "Heavy plasma cannon",
          "profiles": [
            {
              "id": "b5e1-2340-39f5-f072",
              "name": "Heavy plasma cannon - standard",
              "type": "ranged",
              "range": "36\"",
              "attacks": "D3",
              "skill": "3+",
              "strength": 7,
              "ap": -2,
              "damage": "2",
              "keywords": "Blast"
            },
            {
              "id": "1871-d4ef-8c06-775a",
              "name": "Heavy plasma cannon - supercharge",
              "type": "ranged",
              "range": "36\"",
              "attacks": "D3",
              "skill": "3+",
              "strength": 8,
              "ap": -3,
              "damage": "3",
              "keywords": "Blast, Hazardous"
            }
          ],
          "rules": [
            "Hazardous",
            "Blast"
          ]
        },
        {
          "name": "Twin lascannon",
          "profiles": [
            {
              "id": "0ad2-3842-783e-ef55",
              "name": "Twin lascannon",
              "type": "ranged",
              "range": "48\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 12,
              "ap": -3,
              "damage": "D6+1",
              "keywords": "Twin-linked"
            }
          ],
          "rules": [
            "Twin-linked"
          ]
        },
        {
          "name": "Storm bolter",
          "profiles": [
            {
              "id": "9756-e60b-776b-cf23",
              "name": "Storm bolter",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Dreadnought combat weapon",
          "profiles": [
            {
              "id": "57f5-eeba-73cf-e204",
              "name": "Dreadnought combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "3+",
              "strength": 12,
              "ap": -2,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Heavy flamer",
          "profiles": [
            {
              "id": "8b85-297f-a555-c9c1",
              "name": "Heavy flamer",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 5,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        }
      ]
    }
  }
};
