import type { FactionUnitOptions } from "./types";

// Generated by scripts/sync-unit-options.mjs. Do not edit by hand.
export const imperiumAdeptusCustodes: FactionUnitOptions = {
  "catalogue": "Imperium - Adeptus Custodes",
  "rules": {
    "Assault": "Weapons with **[ASSAULT]** in their profile are known as Assault weapons. If a unit that Advanced this turn contains any models equipped with Assault weapons, it is still eligible to shoot in this turn’s Shooting phase. When such a unit is selected to shoot, you can only resolve attacks using Assault weapons its models are equipped with.",
    "Blast": "Weapons with **[BLAST]** in their profile are known as Blast weapons, and they make a random number of attacks. Each time you determine how many attacks are made with a Blast weapon, add 1 to the result for every five models that were in the target unit when you selected it as the target (rounding down). Blast weapons can never be used to make attacks against a unit that is within Engagement Range of one or more units from the attacking model’s army (including its own unit).",
    "Devastating Wounds": "Weapons with **[DEVASTATING WOUNDS]** in their profile are known as Devastating Wounds weapons. Each time an attack is made with such a weapon, if that attack scores a Critical Wound, no saving throw of any kind can be made against that attack (including invulnerable saving throws). Such attacks are only allocated to models after all other attacks made by the attacking unit have been allocated and resolved. After that attack is allocated and after any modifiers are applied, it inflicts a number of mortal wounds on the target equal to the Damage characteristic of that attack, instead of inflicting damage normally.",
    "Ignores Cover": "Weapons with **[IGNORES COVER]** in their profile are known as Ignores Cover weapons. Each time an attack is made with such a weapon, the target cannot have the Benefit of Cover against that attack.",
    "Lance": "Weapons with **[LANCE]** in their profile are known as Lance weapons. Each time an attack is made with such a weapon, if the bearer made a Charge move this turn, add 1 to that attack’s Wound roll.",
    "Melta": "Weapons with **[MELTA X]** in their profile are known as Melta weapons. Each time an attack made with such a weapon targets a unit within half that weapon’s range, that attack’s Damage characteristic is increased by the amount denoted by ‘x’.",
    "Pistol": "Weapons with **[PISTOL]** in their profile are known as Pistols. If a unit contains any models equipped with Pistols, that unit is eligible to shoot in its controlling player’s Shooting phase even while it is within Engagement Range of one or more enemy units. When such a unit is selected to shoot, it can only resolve attacks using its Pistols and can only target one of the enemy units it is within Engagement Range of. In such circumstances, a Pistol can target an enemy unit even if other friendly units are within Engagement Range of the same enemy unit. \n\nIf a model is equipped with one or more Pistols, unless it is a **^^Monster^^** or **^^Vehicle^^** model, it can either shoot with its Pistols or with all of its other ranged weapons. Declare whether such a model will shoot with its Pistols or its other ranged weapons before selecting targets.",
    "Precision": "Weapons with **[PRECISION]** in their profile are known as Precision weapons. Each time an attack made with such a weapon successfully wounds an Attached unit, if a Character model in that unit is visible to the attacking model, the attacking model’s player can choose to have that attack allocated to that Character model instead of following the normal attack sequence.",
    "Rapid Fire": "Weapons with **[RAPID FIRE X]** in their profile are known as Rapid Fire weapons. Each time such a weapon targets a unit within half that weapon’s range, the Attacks characteristic of that weapon is increased by the amount denoted by ‘x’.",
    "Sustained Hits": "Weapons with **[SUSTAINED HITS X]** in their profile are known as Sustained Hits weapons. Each time an attack is made with such a weapon, if a Critical Hit is rolled, that attack scores a number of additional hits on the target as denoted by ‘x’",
    "Torrent": "Weapons with **[TORRENT]** in their profile are known as Torrent weapons. Each time an attack is made with such a weapon, that attack automatically hits the target.",
    "Twin-linked": "Weapons with **[TWIN-LINKED]** in their profile are known as Twin-linked weapons. Each time an attack is made with such a weapon, you can re-roll that attack’s Wound roll."
  },
  "units": {
    "c8a6-a4c5-703e-b717": {
      "name": "Allarus Custodians",
      "weapons": [
        {
          "name": "Guardian Spear",
          "profiles": [
            {
              "id": "37d5-f2f2-cfed-7ab1",
              "name": "Guardian Spear",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 7,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            },
            {
              "id": "ea05-b86a-223e-6ffe",
              "name": "Guardian Spear",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Assault"
            }
          ],
          "rules": [
            "Assault"
          ]
        },
        {
          "name": "Balistus grenade launcher",
          "profiles": [
            {
              "id": "6505-76ad-2840-1f87",
              "name": "Balistus grenade launcher",
              "type": "ranged",
              "range": "18\"",
              "attacks": "D6",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        },
        {
          "name": "Castellan Axe",
          "profiles": [
            {
              "id": "1fde-760c-17e2-4fd1",
              "name": "Castellan axe",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "2+",
              "strength": 9,
              "ap": -1,
              "damage": "3",
              "keywords": "-"
            },
            {
              "id": "76c0-ea97-5a33-2b52",
              "name": "Castellan axe",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Assault"
            }
          ],
          "rules": [
            "Assault"
          ]
        },
        {
          "name": "Misericordia",
          "profiles": [
            {
              "id": "6fed-22cf-99ad-96c2",
              "name": "Misericordia",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 5,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "7314-3c4a-36ab-a594": {
      "name": "Armiger Helverin",
      "weapons": [
        {
          "name": "Armiger autocannon",
          "profiles": [
            {
              "id": "3d6c-b927-b515-c0d8",
              "name": "Armiger autocannon",
              "type": "ranged",
              "range": "48\"",
              "attacks": "4",
              "skill": "3+",
              "strength": 9,
              "ap": -1,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Meltagun",
          "profiles": [
            {
              "id": "4b6f-2df5-d7b6-34dd",
              "name": "Meltagun",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Questoris heavy stubber",
          "profiles": [
            {
              "id": "3b13-7770-1d2b-9e66",
              "name": "Questoris heavy stubber",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Rapid Fire 3"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Armoured feet",
          "profiles": [
            {
              "id": "b6b7-cce0-ad60-bdf4",
              "name": "Armoured feet",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 6,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "5bbd-c5d3-58d7-e391": {
      "name": "Armiger Warglaive",
      "weapons": [
        {
          "name": "Reaper chain-cleaver",
          "profiles": [
            {
              "id": "3a79-406d-aaa7-ed6c",
              "name": "Reaper chain-cleaver - strike",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 10,
              "ap": -3,
              "damage": "3",
              "keywords": "-"
            },
            {
              "id": "5e11-8d35-b7a7-ba38",
              "name": "Reaper chain-cleaver - sweep",
              "type": "melee",
              "range": "Melee",
              "attacks": "8",
              "skill": "3+",
              "strength": 8,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Thermal spear",
          "profiles": [
            {
              "id": "38d-4520-1309-4074",
              "name": "Thermal spear",
              "type": "ranged",
              "range": "18\"",
              "attacks": "2",
              "skill": "3+",
              "strength": 12,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 4"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Meltagun",
          "profiles": [
            {
              "id": "4b6f-2df5-d7b6-34dd",
              "name": "Meltagun",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 9,
              "ap": -4,
              "damage": "D6",
              "keywords": "Melta 2"
            }
          ],
          "rules": [
            "Melta"
          ]
        },
        {
          "name": "Questoris heavy stubber",
          "profiles": [
            {
              "id": "3b13-7770-1d2b-9e66",
              "name": "Questoris heavy stubber",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Rapid Fire 3"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        }
      ]
    },
    "48b7-e713-d5b1-f11c": {
      "name": "Blade Champion",
      "weapons": [
        {
          "name": "Vaultswords",
          "profiles": [
            {
              "id": "7953-e1ea-8b27-b564",
              "name": "Vaultswords - Behemor",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "2+",
              "strength": 7,
              "ap": -2,
              "damage": "2",
              "keywords": "Precision"
            },
            {
              "id": "d09f-3496-dc55-e6b4",
              "name": "Vaultswords - Hurricanis",
              "type": "melee",
              "range": "Melee",
              "attacks": "9",
              "skill": "2+",
              "strength": 5,
              "ap": -1,
              "damage": "1",
              "keywords": "Sustained Hits 1"
            },
            {
              "id": "7ffc-b8d9-10a7-7e4e",
              "name": "Vaultswords - Victus",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 6,
              "ap": -3,
              "damage": "3",
              "keywords": "Devastating Wounds"
            }
          ],
          "rules": [
            "Precision",
            "Sustained Hits",
            "Devastating Wounds"
          ]
        }
      ]
    },
    "4988-d93e-5034-2b3c": {
      "name": "Contemptor-Galatus Dreadnought",
      "weapons": [
        {
          "name": "Galatus warblade",
          "profiles": [
            {
              "id": "3e86-fd-1659-cef5",
              "name": "Galatus warblade",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent, Twin-linked"
            },
            {
              "id": "754b-9a4a-6b86-73f8",
              "name": "Galatus warblade",
              "type": "melee",
              "range": "Melee",
              "attacks": "8",
              "skill": "2+",
              "strength": 8,
              "ap": -2,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent",
            "Twin-linked"
          ]
        }
      ]
    },
    "91b3-2e1c-e642-d213": {
      "name": "Custodian Guard",
      "weapons": [
        {
          "name": "Guardian Spear",
          "profiles": [
            {
              "id": "3665-5bcf-a899-fad",
              "name": "Guardian Spear",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 7,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            },
            {
              "id": "99cf-4b14-147f-8229",
              "name": "Guardian Spear",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Assault"
            }
          ],
          "rules": [
            "Assault"
          ]
        },
        {
          "name": "Sentinel blade",
          "profiles": [
            {
              "id": "52f5-f956-571d-51e2",
              "name": "Sentinel Blade",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 6,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            },
            {
              "id": "888d-3f8f-2d0-297",
              "name": "Sentinel Blade",
              "type": "ranged",
              "range": "12\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Assault, Pistol"
            }
          ],
          "rules": [
            "Assault",
            "Pistol"
          ]
        },
        {
          "name": "Misericordia",
          "profiles": [
            {
              "id": "f33d-a12e-44fc-42dc",
              "name": "Misericordia",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 5,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "9610-b148-8433-93b8": {
      "name": "Custodian Wardens",
      "weapons": [
        {
          "name": "Guardian Spear",
          "profiles": [
            {
              "id": "987-7629-8fda-88f8",
              "name": "Guardian Spear",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 7,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            },
            {
              "id": "277-79d8-5124-f932",
              "name": "Guardian Spear",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Assault"
            }
          ],
          "rules": [
            "Assault"
          ]
        },
        {
          "name": "Castellan Axe",
          "profiles": [
            {
              "id": "644d-df58-5b9b-31c2",
              "name": "Castellan axe",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "2+",
              "strength": 9,
              "ap": -1,
              "damage": "3",
              "keywords": "-"
            },
            {
              "id": "6f60-2244-c2fa-e57f",
              "name": "Castellan axe",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Assault"
            }
          ],
          "rules": [
            "Assault"
          ]
        }
      ]
    },
    "3ec3-a4df-fdbf-5507": {
      "name": "Prosecutors",
      "weapons": [
        {
          "name": "Boltgun",
          "profiles": [
            {
              "id": "4bbd-8a2b-1ec0-2b8c",
              "name": "Boltgun",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 1"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "5cff-97db-f2a6-a5e8",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "2",
              "skill": "3+",
              "strength": 3,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "6319-eeba-b717-bd86": {
      "name": "Shield-Captain in Allarus Terminator Armour",
      "weapons": [
        {
          "name": "Guardian Spear",
          "profiles": [
            {
              "id": "758c-b70e-8940-0a3e",
              "name": "Guardian Spear",
              "type": "melee",
              "range": "Melee",
              "attacks": "7",
              "skill": "2+",
              "strength": 7,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            },
            {
              "id": "0e1d-9037-73ea-a4e6",
              "name": "Guardian Spear",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Assault"
            }
          ],
          "rules": [
            "Assault"
          ]
        },
        {
          "name": "Castellan Axe",
          "profiles": [
            {
              "id": "ea20-f463-db39-5c55",
              "name": "Castellan axe",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "2+",
              "strength": 9,
              "ap": -1,
              "damage": "3",
              "keywords": "-"
            },
            {
              "id": "1c2c-2282-3f68-6e7b",
              "name": "Castellan axe",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Assault"
            }
          ],
          "rules": [
            "Assault"
          ]
        },
        {
          "name": "Balistus grenade launcher",
          "profiles": [
            {
              "id": "6505-76ad-2840-1f87",
              "name": "Balistus grenade launcher",
              "type": "ranged",
              "range": "18\"",
              "attacks": "D6",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        }
      ]
    },
    "7d7c-c212-47a3-38e4": {
      "name": "Trajann Valoris",
      "weapons": [
        {
          "name": "Watcher's Axe",
          "profiles": [
            {
              "id": "cbb7-e6-d938-22bc",
              "name": "Watcher's Axe",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "2+",
              "strength": 10,
              "ap": -2,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Eagle's Scream",
          "profiles": [
            {
              "id": "f447-7ba3-899d-5f35",
              "name": "Eagle's Scream",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 5,
              "ap": -2,
              "damage": "3",
              "keywords": "Assault"
            }
          ],
          "rules": [
            "Assault"
          ]
        }
      ]
    },
    "201e-e502-a8d1-3974": {
      "name": "Venatari Custodians",
      "weapons": [
        {
          "name": "Venatari lance",
          "profiles": [
            {
              "id": "d355-c766-b5ab-acbc",
              "name": "Venatari lance",
              "type": "ranged",
              "range": "24\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 4,
              "ap": -1,
              "damage": "2",
              "keywords": "Assault"
            },
            {
              "id": "7a0d-fb2b-1f72-2e8c",
              "name": "Venatari lance",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 7,
              "ap": -2,
              "damage": "2",
              "keywords": "Lance"
            }
          ],
          "rules": [
            "Assault",
            "Lance"
          ]
        },
        {
          "name": "Kinetic destroyer",
          "profiles": [
            {
              "id": "8996-af7a-da88-622",
              "name": "Kinetic destroyer",
              "type": "ranged",
              "range": "12\"",
              "attacks": "2",
              "skill": "2+",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "Pistol, Sustained Hits 1"
            }
          ],
          "rules": [
            "Pistol",
            "Sustained Hits"
          ]
        },
        {
          "name": "Tarsis buckler",
          "profiles": [
            {
              "id": "6c54-f454-4353-4ac2",
              "name": "Tarsis buckler",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 5,
              "ap": -2,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    }
  }
};
