import type { FactionUnitOptions } from "./types";

// Generated by scripts/sync-unit-options.mjs. Do not edit by hand.
export const xenosOrks: FactionUnitOptions = {
  "catalogue": "Xenos - Orks",
  "rules": {
    "Anti-": "Weapons with **[ANTI-KEYWORD X+]** in their profile are known as Anti weapons. Each time an attack is made with such a weapon against a target with the keyword after the word ‘Anti-’, an unmodified Wound roll of ‘x+’ scores a Critical Wound.",
    "Assault": "Weapons with **[ASSAULT]** in their profile are known as Assault weapons. If a unit that Advanced this turn contains any models equipped with Assault weapons, it is still eligible to shoot in this turn’s Shooting phase. When such a unit is selected to shoot, you can only resolve attacks using Assault weapons its models are equipped with.",
    "Blast": "Weapons with **[BLAST]** in their profile are known as Blast weapons, and they make a random number of attacks. Each time you determine how many attacks are made with a Blast weapon, add 1 to the result for every five models that were in the target unit when you selected it as the target (rounding down). Blast weapons can never be used to make attacks against a unit that is within Engagement Range of one or more units from the attacking model’s army (including its own unit).",
    "Devastating Wounds": "Weapons with **[DEVASTATING WOUNDS]** in their profile are known as Devastating Wounds weapons. Each time an attack is made with such a weapon, if that attack scores a Critical Wound, no saving throw of any kind can be made against that attack (including invulnerable saving throws). Such attacks are only allocated to models after all other attacks made by the attacking unit have been allocated and resolved. After that attack is allocated and after any modifiers are applied, it inflicts a number of mortal wounds on the target equal to the Damage characteristic of that attack, instead of inflicting damage normally.",
    "Extra Attacks": "Weapons with **[EXTRA ATTACKS]** in their profile are known as Extra Attacks weapons. Each time the bearer of one or more Extra Attacks weapons fights, it makes attacks with each of the Extra Attacks melee weapons it is equipped with and it makes attacks with one of the melee weapons it is equipped with that does not have the [EXTRA ATTACKS] ability (if any). The number of attacks made with an Extra Attacks weapon cannot be modified by other rules, unless that weapon’s name is explicitly specified in that rule.",
    "Hazardous": "Weapons with **[HAZARDOUS]** in their profile are known as Hazardous weapons. Each time a unit is selected to shoot or fight, after that unit has resolved all of its attacks, for each Hazardous weapon that targets were selected for when resolving those attacks, that unit must take one Hazardous test. To do so, roll one D6: on a 1, that test is failed. For each failed test you must resolve the following sequence (resolve each failed test one at a time): \n\n■ If possible, select one model in that unit that has lost one or more wounds and is equipped with one or more Hazardous weapons. \n■ Otherwise, if possible, select one model in that unit (excluding **^^Character^^** models) equipped with one or more Hazardous weapons. \n■ Otherwise, select one **^^Character^^** model in that unit equipped with one or more Hazardous weapons. \n\nIf a model was selected, that unit suffers 3 mortal wounds and when allocating those mortal wounds, they must be allocated to the selected model. \n\nIf a unit from a player’s army is selected as the target of the Fire Overwatch Stratagem in their opponent’s Charge phase, any mortal wounds inflicted by Hazardous tests are allocated after the charging unit has ended its Charge move.",
    "Ignores Cover": "Weapons with **[IGNORES COVER]** in their profile are known as Ignores Cover weapons. Each time an attack is made with such a weapon, the target cannot have the Benefit of Cover against that attack.",
    "Pistol": "Weapons with **[PISTOL]** in their profile are known as Pistols. If a unit contains any models equipped with Pistols, that unit is eligible to shoot in its controlling player’s Shooting phase even while it is within Engagement Range of one or more enemy units. When such a unit is selected to shoot, it can only resolve attacks using its Pistols and can only target one of the enemy units it is within Engagement Range of. In such circumstances, a Pistol can target an enemy unit even if other friendly units are within Engagement Range of the same enemy unit. \n\nIf a model is equipped with one or more Pistols, unless it is a **^^Monster^^** or **^^Vehicle^^** model, it can either shoot with its Pistols or with all of its other ranged weapons. Declare whether such a model will shoot with its Pistols or its other ranged weapons before selecting targets.",
    "Precision": "Weapons with **[PRECISION]** in their profile are known as Precision weapons. Each time an attack made with such a weapon successfully wounds an Attached unit, if a Character model in that unit is visible to the attacking model, the attacking model’s player can choose to have that attack allocated to that Character model instead of following the normal attack sequence.",
    "Rapid Fire": "Weapons with **[RAPID FIRE X]** in their profile are known as Rapid Fire weapons. Each time such a weapon targets a unit within half that weapon’s range, the Attacks characteristic of that weapon is increased by the amount denoted by ‘x’.",
    "Torrent": "Weapons with **[TORRENT]** in their profile are known as Torrent weapons. Each time an attack is made with such a weapon, that attack automatically hits the target.",
    "Twin-linked": "Weapons with **[TWIN-LINKED]** in their profile are known as Twin-linked weapons. Each time an attack is made with such a weapon, you can re-roll that attack’s Wound roll."
  },
  "units": {
    "e651-5901-35e5-dc35": {
      "name": "Boss Snikrot",
      "weapons": [
        {
          "name": "Mork’s Teeth",
          "profiles": [
            {
              "id": "2f51-1f50-c3df-dff4",
              "name": "Mork’s Teeth",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "2+",
              "strength": 6,
              "ap": -1,
              "damage": "2",
              "keywords": "Precision, Twin-linked"
            }
          ],
          "rules": [
            "Twin-linked",
            "Precision"
          ]
        },
        {
          "name": "Slugga",
          "profiles": [
            {
              "id": "fc03-187d-5fa8-3e05",
              "name": "Slugga",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        }
      ]
    },
    "4ea0-6b70-c17c-bc00": {
      "name": "Ghazghkull Thraka",
      "weapons": [
        {
          "name": "Mork’s Roar",
          "profiles": [
            {
              "id": "2b34-6be2-6c96-75de",
              "name": "Mork’s Roar",
              "type": "ranged",
              "range": "36\"",
              "attacks": "12",
              "skill": "5+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 4"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Gork’s Klaw",
          "profiles": [
            {
              "id": "e688-c82d-9852-48ab",
              "name": "Gork’s Klaw - strike",
              "type": "melee",
              "range": "Melee",
              "attacks": "6",
              "skill": "2+",
              "strength": 14,
              "ap": -3,
              "damage": "4",
              "keywords": "-"
            },
            {
              "id": "e5bd-a8f9-bca0-16e9",
              "name": "Gork’s Klaw - sweep",
              "type": "melee",
              "range": "Melee",
              "attacks": "12",
              "skill": "2+",
              "strength": 8,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Makari’s stabba",
          "profiles": [
            {
              "id": "7758-d06f-5fe6-54ff",
              "name": "Makari’s stabba",
              "type": "melee",
              "range": "Melee",
              "attacks": "1",
              "skill": "4+",
              "strength": 3,
              "ap": 0,
              "damage": "1",
              "keywords": "Devastating Wounds"
            }
          ],
          "rules": [
            "Devastating Wounds"
          ]
        }
      ]
    },
    "de8f-24f9-c543-92b7": {
      "name": "Gretchin",
      "weapons": [
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "c145-d515-835b-a8b0",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "1",
              "skill": "5+",
              "strength": 2,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Grot blasta",
          "profiles": [
            {
              "id": "680a-9e4f-1230-d9b0",
              "name": "Grot blasta",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "4+",
              "strength": 3,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        },
        {
          "name": "Grot-smacka",
          "profiles": [
            {
              "id": "2063-555b-ab81-7195",
              "name": "Grot-smacka",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Slugga",
          "profiles": [
            {
              "id": "8a84-7c52-bf36-8bf9",
              "name": "Slugga",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        }
      ]
    },
    "8c36-c946-2e0f-f648": {
      "name": "Killa Kans",
      "weapons": [
        {
          "name": "Kan shoota",
          "profiles": [
            {
              "id": "fb65-5edf-1023-6c39",
              "name": "Kan shoota",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "4+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Devastating Wounds, Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire",
            "Devastating Wounds"
          ]
        },
        {
          "name": "Kan klaw",
          "profiles": [
            {
              "id": "b5d1-4e50-edae-b2af",
              "name": "Kan klaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "4+",
              "strength": 8,
              "ap": -2,
              "damage": "3",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Grotzooka",
          "profiles": [
            {
              "id": "336d-a799-7cff-1fb3",
              "name": "Grotzooka",
              "type": "ranged",
              "range": "18\"",
              "attacks": "D3+3",
              "skill": "4+",
              "strength": 6,
              "ap": -1,
              "damage": "1",
              "keywords": "Blast, Ignores Cover"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Blast"
          ]
        },
        {
          "name": "Rokkit launcha",
          "profiles": [
            {
              "id": "e7c6-d3cb-2920-6f9e",
              "name": "Rokkit launcha",
              "type": "ranged",
              "range": "24\"",
              "attacks": "D3",
              "skill": "4+",
              "strength": 9,
              "ap": -2,
              "damage": "3",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        },
        {
          "name": "Skorcha",
          "profiles": [
            {
              "id": "2836-aa14-8c6b-da7e",
              "name": "Skorcha",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 5,
              "ap": -1,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        }
      ]
    },
    "303-267f-e45c-6aa9": {
      "name": "Kommandos",
      "weapons": [
        {
          "name": "Slugga",
          "profiles": [
            {
              "id": "ce63-1cbe-d476-f9f1",
              "name": "Slugga",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        },
        {
          "name": "Choppa",
          "profiles": [
            {
              "id": "d51d-7f26-af01-89d8",
              "name": "Choppa",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Kustom shoota",
          "profiles": [
            {
              "id": "a564-4e0-9914-a50f",
              "name": "Kustom shoota",
              "type": "ranged",
              "range": "18\"",
              "attacks": "4",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "304a-d503-a99c-748e",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Breacha ram",
          "profiles": [
            {
              "id": "50db-5f10-618-a7de",
              "name": "Breacha ram",
              "type": "melee",
              "range": "Melee",
              "attacks": "2",
              "skill": "4+",
              "strength": 9,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Burna",
          "profiles": [
            {
              "id": "1596-443a-d7a1-e7a9",
              "name": "Burna",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D6",
              "skill": "N/A",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Ignores Cover, Torrent"
            }
          ],
          "rules": [
            "Ignores Cover",
            "Torrent"
          ]
        },
        {
          "name": "Rokkit launcha",
          "profiles": [
            {
              "id": "2adc-cde3-b9d4-3aaf",
              "name": "Rokkit launcha",
              "type": "ranged",
              "range": "24\"",
              "attacks": "D3",
              "skill": "5+",
              "strength": 9,
              "ap": -2,
              "damage": "3",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        },
        {
          "name": "Power klaw",
          "profiles": [
            {
              "id": "2a0c-d470-c159-9b2b",
              "name": "Power klaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "4+",
              "strength": 9,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Big choppa",
          "profiles": [
            {
              "id": "8c72-e163-8dfb-cb28",
              "name": "Big choppa",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 7,
              "ap": -1,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "7067-34f4-5272-e05f": {
      "name": "Meganobz",
      "weapons": [
        {
          "name": "Kustom shoota",
          "profiles": [
            {
              "id": "a564-4e0-9914-a50f",
              "name": "Kustom shoota",
              "type": "ranged",
              "range": "18\"",
              "attacks": "4",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "Power klaw",
          "profiles": [
            {
              "id": "2a0c-d470-c159-9b2b",
              "name": "Power klaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "4+",
              "strength": 9,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Kombi-weapon",
          "profiles": [
            {
              "id": "1451-6820-fd91-1dec",
              "name": "Kombi-weapon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Anti-Infantry 4+, Devastating Wounds, Rapid Fire 1"
            }
          ],
          "rules": [
            "Devastating Wounds",
            "Anti-",
            "Rapid Fire"
          ]
        },
        {
          "name": "Killsaw",
          "profiles": [
            {
              "id": "79a1-8883-2650-9969",
              "name": "Killsaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "2",
              "skill": "4+",
              "strength": 12,
              "ap": -3,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Twin killsaw",
          "profiles": [
            {
              "id": "8bcf-45e6-715a-e762",
              "name": "Twin killsaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "2",
              "skill": "4+",
              "strength": 12,
              "ap": -3,
              "damage": "2",
              "keywords": "Twin-linked"
            }
          ],
          "rules": [
            "Twin-linked"
          ]
        }
      ]
    },
    "3b2-8c11-616a-1005": {
      "name": "Mek",
      "weapons": [
        {
          "name": "Wrench",
          "profiles": [
            {
              "id": "9ffb-39f3-d46b-2f31",
              "name": "Wrench",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Killsaw",
          "profiles": [
            {
              "id": "152f-bcce-3-f8f7",
              "name": "Killsaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "1",
              "skill": "4+",
              "strength": 12,
              "ap": -3,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Kustom mega-slugga",
          "profiles": [
            {
              "id": "e6dc-45f4-f247-45e1",
              "name": "Kustom mega-slugga",
              "type": "ranged",
              "range": "12\"",
              "attacks": "D3",
              "skill": "5+",
              "strength": 8,
              "ap": -2,
              "damage": "D6",
              "keywords": "Blast, Hazardous"
            }
          ],
          "rules": [
            "Blast",
            "Hazardous"
          ]
        }
      ]
    },
    "9ee5-2b39-de06-dda6": {
      "name": "Morkanaut",
      "weapons": [
        {
          "name": "Klaw of Mork",
          "profiles": [
            {
              "id": "2a8-5e21-cd76-3e00",
              "name": "Klaw of Mork - strike",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 18,
              "ap": -3,
              "damage": "6",
              "keywords": "-"
            },
            {
              "id": "b67e-7113-bc07-786e",
              "name": "Klaw of Mork - sweep",
              "type": "melee",
              "range": "Melee",
              "attacks": "12",
              "skill": "3+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Kustom mega-zappa",
          "profiles": [
            {
              "id": "fb65-4600-380f-8800",
              "name": "Kustom mega-zappa",
              "type": "ranged",
              "range": "36\"",
              "attacks": "D6+3",
              "skill": "5+",
              "strength": 10,
              "ap": -2,
              "damage": "D6",
              "keywords": "Blast, Hazardous"
            }
          ],
          "rules": [
            "Blast",
            "Hazardous"
          ]
        },
        {
          "name": "Kustom mega-blasta",
          "profiles": [
            {
              "id": "1508-23e-fa3b-d006",
              "name": "Kustom mega-blasta",
              "type": "ranged",
              "range": "24\"",
              "attacks": "3",
              "skill": "5+",
              "strength": 9,
              "ap": -2,
              "damage": "D6",
              "keywords": "Hazardous"
            }
          ],
          "rules": [
            "Hazardous"
          ]
        },
        {
          "name": "Rokkit launcha",
          "profiles": [
            {
              "id": "2adc-cde3-b9d4-3aaf",
              "name": "Rokkit launcha",
              "type": "ranged",
              "range": "24\"",
              "attacks": "D3",
              "skill": "5+",
              "strength": 9,
              "ap": -2,
              "damage": "3",
              "keywords": "Blast"
            }
          ],
          "rules": [
            "Blast"
          ]
        },
        {
          "name": "Twin big shoota",
          "profiles": [
            {
              "id": "2990-d370-7498-3e58",
              "name": "Twin big shoota",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "5+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2, Twin-linked"
            }
          ],
          "rules": [
            "Twin-linked",
            "Rapid Fire"
          ]
        }
      ]
    },
    "b16a-7132-3f8a-abe5": {
      "name": "Nobz",
      "weapons": [
        {
          "name": "Slugga",
          "profiles": [
            {
              "id": "ce63-1cbe-d476-f9f1",
              "name": "Slugga",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        },
        {
          "name": "Big choppa",
          "profiles": [
            {
              "id": "cb08-174d-d24a-5c3f",
              "name": "Big choppa",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 7,
              "ap": -1,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Power klaw",
          "profiles": [
            {
              "id": "2a0c-d470-c159-9b2b",
              "name": "Power klaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "4+",
              "strength": 9,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "af4a-297f-199e-be46",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Kombi-weapon",
          "profiles": [
            {
              "id": "1451-6820-fd91-1dec",
              "name": "Kombi-weapon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Anti-Infantry 4+, Devastating Wounds, Rapid Fire 1"
            }
          ],
          "rules": [
            "Devastating Wounds",
            "Anti-",
            "Rapid Fire"
          ]
        }
      ]
    },
    "83a7-ea20-ed9-d14a": {
      "name": "Warbikers",
      "weapons": [
        {
          "name": "Twin dakkagun",
          "profiles": [
            {
              "id": "2a24-7d4d-f8d9-148",
              "name": "Twin dakkagun",
              "type": "ranged",
              "range": "18\"",
              "attacks": "3",
              "skill": "5+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Assault, Rapid Fire 2, Twin-linked"
            }
          ],
          "rules": [
            "Assault",
            "Twin-linked",
            "Rapid Fire"
          ]
        },
        {
          "name": "Close combat weapon",
          "profiles": [
            {
              "id": "304a-d503-a99c-748e",
              "name": "Close combat weapon",
              "type": "melee",
              "range": "Melee",
              "attacks": "2",
              "skill": "3+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Slugga",
          "profiles": [
            {
              "id": "ce63-1cbe-d476-f9f1",
              "name": "Slugga",
              "type": "ranged",
              "range": "12\"",
              "attacks": "1",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol"
            }
          ],
          "rules": [
            "Pistol"
          ]
        },
        {
          "name": "Choppa",
          "profiles": [
            {
              "id": "d51d-7f26-af01-89d8",
              "name": "Choppa",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 4,
              "ap": -1,
              "damage": "1",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Big choppa",
          "profiles": [
            {
              "id": "cb08-174d-d24a-5c3f",
              "name": "Big choppa",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "3+",
              "strength": 7,
              "ap": -1,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Power klaw",
          "profiles": [
            {
              "id": "2a0c-d470-c159-9b2b",
              "name": "Power klaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "3",
              "skill": "4+",
              "strength": 9,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    },
    "2efc-c4b3-2ecc-5a37": {
      "name": "Warboss",
      "weapons": [
        {
          "name": "Twin slugga",
          "profiles": [
            {
              "id": "5bde-8a1f-83e6-6450",
              "name": "Twin slugga",
              "type": "ranged",
              "range": "12\"",
              "attacks": "2",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Pistol, Twin-linked"
            }
          ],
          "rules": [
            "Pistol",
            "Twin-linked"
          ]
        },
        {
          "name": "Attack squig",
          "profiles": [
            {
              "id": "3094-cf7a-7a70-3807",
              "name": "Attack Squig",
              "type": "melee",
              "range": "Melee",
              "attacks": "2",
              "skill": "4+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Extra Attacks"
            }
          ],
          "rules": [
            "Extra Attacks"
          ]
        },
        {
          "name": "Big choppa",
          "profiles": [
            {
              "id": "a43a-fbb3-2a23-b3c5",
              "name": "Big choppa",
              "type": "melee",
              "range": "Melee",
              "attacks": "5",
              "skill": "2+",
              "strength": 8,
              "ap": -1,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Power klaw",
          "profiles": [
            {
              "id": "2b2f-dd7c-cb35-1a32",
              "name": "Power klaw",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "3+",
              "strength": 10,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        },
        {
          "name": "Kombi-weapon",
          "profiles": [
            {
              "id": "1451-6820-fd91-1dec",
              "name": "Kombi-weapon",
              "type": "ranged",
              "range": "24\"",
              "attacks": "1",
              "skill": "5+",
              "strength": 4,
              "ap": 0,
              "damage": "1",
              "keywords": "Anti-Infantry 4+, Devastating Wounds, Rapid Fire 1"
            }
          ],
          "rules": [
            "Devastating Wounds",
            "Anti-",
            "Rapid Fire"
          ]
        }
      ]
    },
    "494b-11ce-5af-5b50": {
      "name": "Warboss in Mega Armour",
      "weapons": [
        {
          "name": "Big shoota",
          "profiles": [
            {
              "id": "f828-d419-e65-9bcb",
              "name": "Big shoota",
              "type": "ranged",
              "range": "36\"",
              "attacks": "3",
              "skill": "4+",
              "strength": 5,
              "ap": 0,
              "damage": "1",
              "keywords": "Rapid Fire 2"
            }
          ],
          "rules": [
            "Rapid Fire"
          ]
        },
        {
          "name": "’Uge choppa",
          "profiles": [
            {
              "id": "bbbf-8f37-b529-648b",
              "name": "’Uge choppa",
              "type": "melee",
              "range": "Melee",
              "attacks": "4",
              "skill": "2+",
              "strength": 12,
              "ap": -2,
              "damage": "2",
              "keywords": "-"
            }
          ],
          "rules": []
        }
      ]
    }
  }
};
