import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const anvilSiegeForce: DetachmentData = {
  name: "Anvil Siege Force",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Shield of the Imperium",
      text: `Ranged weapons equipped by **^^Adeptus Astartes^^** models from your army have the **[HEAVY]** ability. If such a weapon already has this ability, each time an attack is made with that weapon, if the attacking model's unit Remained Stationary this turn, add 1 to the Wound roll.`,
    },
  ],
  stratagems: [
    {
      name: "Armour Of Contempt",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "No Threat Too Great",
      cost: 2,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes a ranged attack that targets a MONSTER or VEHICLE unit, you can re-roll the Wound roll.`,
    },
    {
      name: "Battle Drill Recall",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [SUSTAINED HITS 1] ability. If your unit Remained Stationary this turn, then until the end of the phase, each time a model in your unit makes a ranged attack, a successful unmodified Hit roll of 5+ scores a Critical Hit.`,
    },
    {
      name: "Hail Of Vengeance",
      cost: 2,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has resolved its attacks",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that had one or more of its models destroyed as a result of the attacking unit's attacks.

EFFECT: Your unit can shoot as if it were your Shooting phase, but must target only that enemy unit when doing so, and can only do so if that enemy unit is an eligible target.`,
    },
    {
      name: "Not One Backwards Step",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Command phase",
      text: `TARGET: One ADEPTUS ASTARTES INFANTRY unit from your army within range of an objective marker.

EFFECT: Until the end of the turn, double the Objective Control characteristic of models in your unit, but it must Remain Stationary this turn.`,
    },
    {
      name: "Rigid Discipline",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of the Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that is within Engagement Range of one or more enemy units.

EFFECT: Your unit can immediately make a Fall Back move of up to 6".

RESTRICTIONS: When making that move, your unit must end that move either wholly within your deployment zone or within range of an objective marker.`,
    },
  ],
};
