import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const auguriumTaskForce: DetachmentData = {
  name: "Augurium Task Force",
  faction: "Imperium - Grey Knights",
  rules: [
    {
      name: "Prescient Redeployment",
      text: `From the second battle round onwards, at the start of your Movement phase, if you did not select the maximum number of ^^**Grey Knights^^** units from your army using the Gate of Infinity ability at the end of your opponent's previous turn, you can select one ^^**Grey Knights^^** unit from your army that is on the battlefield that could have been selected using the Gate of Infinity ability. Remove that unit from the battlefield and place it into Strategic Reserves.


**Designer's Note**: *This means that your unit can retain its position on the battlefield at the end of your Command phase, and then be placed into Strategic Reserves at the start of your Movement phase, to set it up again in your Reinforcements step in another position.`,
    },
  ],
  stratagems: [
    {
      name: "Appointed Hour",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Grey Knights Psyker unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, an unmodified Hit roll of 5+ scores a Critical Hit.`,
    },
    {
      name: "Aggressive Anticipation",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Grey Knights Psyker unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, you can ignore any or all modifiers to that attack's Weapon Skill or Ballistic Skill characteristics and/or any or all modifiers to the Hit roll.`,
    },
    {
      name: "Necessary End",
      cost: 1,
      type: "Epic Deed",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Grey Knights Infantry unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not fought this phase, roll one D6. If the result is greater than the current battle round number, do not remove the destroyed model from play; it can fight after the attacking unit has finished making its attacks, and is then removed from play.`,
    },
    {
      name: "Forewarned Evasion",
      cost: 1,
      type: "Epic Deed",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Grey Knights Walker unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time an attack targets your unit, subtract 1 from the Hit roll.`,
    },
    {
      name: "Redirected Strike",
      cost: 1,
      type: "Epic Deed",
      phase: "End of your Command phase",
      text: `TARGET: One Grey Knights Psyker unit from your army that is not within Engagement Range of one or more enemy units.

EFFECT: If your unit has the Deep Strike ability, it can be placed into Strategic Reserves.

Designer's Note: This Stratagem lets players utilise abilities that retain control of objective markers and react to their missions and objectives with this unit.`,
    },
    {
      name: "Mirage Of Echoes",
      cost: 1,
      type: "Strategic Ploy",
      phase: "The Reinforcements step of your opponent's Movement phase, just after an enemy unit is set up",
      text: `TARGET: One Grey Knights Psyker unit from your army that is within 12" of that enemy unit and is not within Engagement Range of one or more enemy units.

EFFECT: If your unit has the Deep Strike ability, it can be placed into Strategic Reserves.`,
    },
  ],
};
