import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const auricChampions: DetachmentData = {
  name: "Auric Champions",
  faction: "Imperium - Adeptus Custodes",
  rules: [
    {
      name: "Assemblage of Might",
      text: `At the start of your Command phase, select one unit from your opponent’s army. Until the start of your next Command phase, each time a model in an ^^**Adeptus Custodes Character^^** unit from your army makes an attack that targets that enemy unit, add 1 to the Wound roll.`,
    },
  ],
  stratagems: [
    {
      name: "Shoulder The Mantle",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Movement phase, before the Reinforcements step",
      text: `TARGET: One Adeptus Custodes Character model from your army that is not leading a unit.

EFFECT: Select one friendly unit (excluding Battle-shocked and Attached units) within 2" horizontally and 5" vertically of your model that it could lead (as described in the Leader section of its datasheet). Your model attaches to that unit as a Leader. Change that unit's Starting Strength accordingly.`,
    },
    {
      name: "Earning Of A Name",
      cost: 1,
      type: "Epic Deed",
      phase: "Fight phase",
      text: `TARGET: Up to two Adeptus Custodes Character units from your army that have not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a CHARACTER model in either of your units makes an attack that targets a MONSTER or VEHICLE unit, you can re-roll the Hit roll and you can re-roll the Wound roll.`,
    },
    {
      name: "The Emperor's Auspice",
      cost: 1,
      type: "Epic Deed",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Adeptus Custodes Character unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, CHARACTER models in your unit have the Feel No Pain 4+ ability.`,
    },
    {
      name: "Vigil Unending",
      cost: 2,
      type: "Epic Deed",
      phase: "Fight phase",
      text: `TARGET: One Adeptus Custodes Character model from your army that was just destroyed and has not fought this phase. You can use this Stratagem on that unit even though it was just destroyed.

EFFECT: Do not remove your destroyed model from play. The destroyed model can fight after the attacking unit has finished making attacks, and is then removed from play.`,
    },
    {
      name: "Superhuman Reserves",
      cost: 2,
      type: "Epic Deed",
      phase: "Any phase, just after an Adeptus Custodes Warlord model from your army has used an ability on its datasheet or from an Enhancement that says it can only be used Once per battle",
      text: `TARGET: That Adeptus Custodes Warlord model.

EFFECT: Your model can use its Once per battle' ability one additional time during this battle (but not in the same phase).

RESTRICTIONS: You cannot use this Stratagem more than once per battle.`,
    },
    {
      name: "Slayer Of Champions",
      cost: 1,
      type: "Epic Deed",
      phase: "Any phase",
      text: `TARGET: One Adeptus Custodes Character unit from your army that has just destroyed the unit you selected at the start of your Command phase as the target of your Assemblage of Might ability.

EFFECT: Select one enemy unit on the battlefield Until the start of your next Command phase, each time an ADEPTUS CUSTODES CHARACTER model from your army makes an attack that target that enemy unit, add 1 to the Wound roll In addition, if the destroyed unit was a CHARACTER unit, gain 1CP.`,
    },
  ],
};
