import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const banishers: DetachmentData = {
  name: "Banishers",
  faction: "Imperium - Grey Knights",
  rules: [
    {
      name: "Channelled Force",
      text: `Each time a **^^Grey Knights**^^ unit from your army is selected to fight, that unit can take a Leadership test. If that test is passed, select one of the following rules. Until the end of the phase, that unit has that rule.
- Melee weapons equipped by models in this unit with the [**^^Psychic**^^] ability also have the [**^^Sustained Hits 1**^^] ability.
- Melee weapons equipped by models in this unit with the [**^^Psychic**^^] ability also have the [**^^Lethal Hits**^^] ability.`,
    },
  ],
  stratagems: [
    {
      name: "Chaos Bane",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Shooting phase",
      text: `TARGET: One Grey Knights Psyker unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [ANTI-CHAOS 4+] ability.`,
    },
    {
      name: "Warding Chant",
      cost: 1,
      type: "Epic Deed",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Grey Knights Psyker unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, models in your unit have the Feel No Pain 5+ ability against attacks with an unmodified Damage characteristic of 1.`,
    },
    {
      name: "Shadow Of Anarch",
      cost: 1,
      type: "Epic Deed",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move",
      text: `TARGET: One Grey Knights Psyker unit from your army that is within 9" of that enemy unit and is not within Engagement Range of one or more enemy units.

EFFECT: Your unit can make a Normal move of up to 6" or, if it has the Deep Strike ability, it can be placed into Strategic Reserves.`,
    },
    {
      name: "Circle Of Sanctuary",
      cost: 1,
      type: "Epic Deed",
      phase: "Start of your opponent's Movement phase",
      text: `TARGET: One Grey Knights Character model from your army.

EFFECT: Until the end of the phase, enemy units that are set up on the battlefield as Reinforcements cannot be set up within 12" horizontally of your model.`,
    },
    {
      name: "Celerity",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Charge phase",
      text: `TARGET: One Grey Knights Psyker Infantry unit from your army.

EFFECT: Until the end of the turn, your unit is eligible to declare a charge in a turn in which it Advanced.`,
    },
    {
      name: "Hexwrought Reprisal",
      cost: 1,
      type: "Epic Deed",
      phase: "End of any phase",
      text: `TARGET: One Grey Knights Psyker unit from your army that is on the battlefield and suffered one or more mortal wounds this phase.

EFFECT: Select one enemy unit which inflicted one or more mortal wounds on your unit this phase, then roll a number of dice equal to the number of mortal wounds your unit suffered this phase: for each 2+, that enemy unit suffers one mortal wound (to a maximum of 6 mortal wounds). These mortal wounds are Psychic Attacks.`,
    },
  ],
};
