import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const bastionTaskForce: DetachmentData = {
  name: "Bastion Task Force",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Interlocking Tactics",
      text: `^^**Adeptus Astartes Battleline^^** units from your army:

- Are eligible to shoot and declare a charge in a turn in which they Advanced or Fell Back.

- Are eligible to start to perform an Action in a turn in which they Advanced or Fell Back.

Each time an ^^**Adeptus Astartes Battleline^^** unit from your army is selected to attack, after resolving those attacks, select one enemy unit hit by one or more of those attacks. Until the end of the turn, that enemy unit is auspex scanned. Each time an ^^**Adeptus Astartes^^** model from your army makes an attack that targets an auspex scanned unit, re‑roll a Hit roll of 1.`,
    },
  ],
  stratagems: [
    {
      name: "Light Of Vengeance",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Select the [LETHAL HITS] or [SUSTAINED HITS 1] ability. Until the end of the phase, weapons equipped by models in your unit have that ability while targeting an auspex scanned unit or if the bearer has the Battleline keyword.`,
    },
    {
      name: "Codex Discipline",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets an enemy unit, re-roll a Hit roll of 1. If that target is auspex scanned, re-roll a Wound roll of 1 as well.`,
    },
    {
      name: "Heresy Undone",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase or your Charge phase",
      text: `TARGET: One ADEPTUS ASTARTES unit (excluding Battleline units) from your army.

EFFECT: Until the end of the phase, your unit is eligible to shoot and declare a charge in a turn in which it Advanced or Fell Back. If it does, every target of that charge and every target of those attacks must be an auspex scanned unit.`,
    },
    {
      name: "Guided Disruption",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase or the Fight phase, just after an Adeptus Astartes Battleline unit from your army has finished making its attacks",
      text: `TARGET: That ADEPTUS ASTARTES BATTLELINE unit.

EFFECT: When an enemy unit is auspex scanned as a result of those attacks this turn, if that enemy unit does not have the MONSTER or VEHICLE keywords, until the start of your next turn, it is pinned. While a unit is pinned, subtract 2 from that unit's Move characteristic and subtract 2 from Charge rolls made for that unit.`,
    },
    {
      name: "Shock Bombardment",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase or the Fight phase, just after an Adeptus Astartes Battleline unit from your army finished making its attacks",
      text: `TARGET: That ADEPTUS ASTARTES BATTLELINE unit.

EFFECT: When an enemy unit is auspex scanned as a result of those attacks this turn, until the start of your next turn, it is suppressed. While a unit is suppressed, each time a model in that unit makes an attack, subtract 1 from the Hit roll.`,
    },
    {
      name: "Angels Defiant",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent’s Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Adeptus Astartes Battleline unit from your army that was selected as the target of one or more of the attacking unit’s attacks.

EFFECT: Until the end of the phase, each time an attack targets your unit, if the Strength characteristic of that attack is greater than the Toughness characteristic of your unit, subtract 1 from the Wound roll.`,
    },
  ],
};
