import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const bladeOfUltramar: DetachmentData = {
  name: "Blade of Ultramar",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Mastered Doctrines",
      text: `At the start of up to three of your Command phases, you can select one of the Combat Doctrines listed below. Until the start of your next Command phase, that Combat Doctrine is active and its effects apply to all ^^**Adeptus Astartes^^** units from your army. You cannot select a Combat Doctrine you have already selected this battle, unless a friendly **^^Marneus Calgar^^** model is on the battlefield.

**DEVASTATOR DOCTRINE**
This unit is eligible to shoot in a turn in which it Advanced.

**TACTICAL DOCTRINE**
This unit is eligible to shoot and declare a charge in a turn in which it Fell Back.

**ASSAULT DOCTRINE**
This unit is eligible to declare a charge in a turn in which it Advanced.`,
    },
  ],
  stratagems: [
    {
      name: "Courage And Honour!",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army.

EFFECT: Until the end of the phase, melee weapons equipped by models in your unit have the [LANCE] ability. If your unit is under the effects of the Assault Doctrine, until the end of the phase, improve the Armour Penetration characteristic of such weapons by 1 as well.`,
    },
    {
      name: "Exemplary Vigilance",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [IGNORES COVER] ability. If your unit is under the effects of the Devastator Doctrine, until the end of the phase, improve the Armour Penetration characteristic of such weapons by 1 as well.`,
    },
    {
      name: "Armour Of Contempt",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Tactical Foresight",
      cost: 1,
      type: "Epic Deed",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time an attack targets your unit, if the Strength characteristic of that attack is greater than or equal to the Toughness characteristic of that unit, subtract 1 from the Wound roll.`,
    },
    {
      name: "Practical Tactics",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move",
      text: `TARGET: One Adeptus Astartes Infantry or Adeptus Astartes Mounted unit from your army that is not within Engagement Range of one or more enemy units and is within 9" of the enemy unit that just ended that move.

EFFECT: Your unit can make a Normal move of up to D6", or a Normal move of up to 6" instead if it is under the effects of the Tactical Doctrine.`,
    },
    {
      name: "Ultramarian Adaptivity",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Command phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army.

EFFECT: Select the Devastator Doctrine, Tactical Doctrine or Assault Doctrine. Until the start of your next Command phase, that Combat Doctrine is active for your unit instead of any other Combat Doctrine that is active for your army, even if you have already selected that Combat Doctrine this battle.`,
    },
  ],
};
