import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const blitzBrigade: DetachmentData = {
  name: "Blitz Brigade",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Eager For The Fight",
      text: `Each time an **^^Orks^^** unit from your army disembarks from a **^^Transport^^**, until the end of the turn, you can re‑roll Advance and Charge rolls made for that **^^Orks^^** unit.`,
    },
    {
      name: "Assault",
      text: `Weapons with **[ASSAULT]** in their profile are known as Assault weapons. If a unit that Advanced this turn contains any models equipped with Assault weapons, it is still eligible to shoot in this turn’s Shooting phase. When such a unit is selected to shoot, you can only resolve attacks using Assault weapons its models are equipped with.`,
    },
  ],
  stratagems: [
    {
      name: "Armoured Duellists",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One Orks Vehicle unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time your unit makes an attack that targets a MONSTER or VEHICLE unit, add 1 to the Hit roll and add 1 to the Wound roll.`,
    },
    {
      name: "Mount Up, Ladz",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of the Fight phase",
      text: `TARGET: One Orks Infantry unit from your army that is not within Engagement Range of one or more enemy units, and one friendly Transport it is able to embark within.

EFFECT: If your ORKS INFANTRY unit is wholly within 6" of that TRANSPORT, it can embark within it.`,
    },
    {
      name: "Yooz In Trouble Now",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has shot",
      text: `TARGET: One Battlewagon, Hunta Rig or Kill Rig model from your army that was hit by one or more of the attacking unit's attacks.

EFFECT: One Orks Infantry unit embarked within your model can disembark and make a Surge move. To do so, roll one D6: models in that unit move a number of inches up to this result, but that unit must end that move as close as possible to the closest enemy unit (excluding AIRCRAFT). When doing so, those models can be moved within Engagement Range of that enemy unit.`,
    },
    {
      name: "Run 'em Down",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One Battlewagon, Kill Rig or Hunta Rig unit from your army that has not been selected to move this phase.

EFFECT: Select up to two other friendly Orks Vehicle or Orks Monster units within 6" of your unit. Until the end of the turn, your unit and each unit you selected are eligible to declare a charge in a turn in which they Advanced.`,
    },
    {
      name: "Mekanised Brutality",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One Battlewagon, Kill Rig or Hunta Rig unit from your army that has not been selected to move this phase.

EFFECT: Until the end of the turn, each time a unit disembarks from your unit after your unit makes a Normal move, that disembarked unit is still eligible to declare a charge this turn.`,
    },
    {
      name: "Impervious",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Battlewagon, Kill Rig or Hunta Rig unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time an attack targets your unit, if the Strength characteristic of that attack is greater than the Toughness characteristic of your unit, subtract 1 from the Wound roll.`,
    },
  ],
};
