import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const brotherhoodStrike: DetachmentData = {
  name: "Brotherhood Strike",
  faction: "Imperium - Grey Knights",
  rules: [
    {
      name: "Fury of Titan",
      text: `Each time a unit from your army is set up using the Deep Strike rule, until the end of the turn, each time a model in that unit makes an attack, re-roll a Hit roll of 1 and re-roll a Wound roll of 1.`,
    },
  ],
  stratagems: [
    {
      name: "Shining Veil",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Grey Knights unit that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, your unit has the Stealth ability.`,
    },
    {
      name: "Purgation Pattern",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One Grey Knights unit from your army that was set up using the Deep Strike ability this turn and has not been selected to shoot this phase.

EFFECT: Until the end of the phase, weapons equipped by models in your unit have the [SUSTAINED HITS 1] ability.`,
    },
    {
      name: "Combat Manifestation",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Movement phase",
      text: `TARGET: One Grey Knights unit from your army that is arriving using the Deep Strike ability this phase.

EFFECT: Set your unit up anywhere on the battlefield that is more than 6" horizontally away from all enemy units, but until the end of the turn, it is not eligible to declare a charge.`,
    },
    {
      name: "Expeditious Exit",
      cost: 2,
      type: "Strategic Ploy",
      phase: "End of your opponent's Fight phase",
      text: `TARGET: One Grey Knights Psyker Infantry unit from your army.

EFFECT: If every model in your unit has the Deep Strike ability, remove your unit from the battlefield and place it into Strategic Reserves.

Designer's Note: This Stratagem allows you to remove a unit in addition to those removed using the Gate of Infinity rule, and it allows you to remove a unit within Engagement Range of one or more enemy units.`,
    },
    {
      name: "Duty Unending",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit within Engagement Range of one or more Grey Knights units from your army Falls Back",
      text: `TARGET: One of those GREY KNIGHTS units that is not within Engagement Range of one or more enemy units.

EFFECT: If your unit has the Deep Strike ability, it can be placed into Strategic Reserves.`,
    },
    {
      name: "Truesilver Channelling",
      cost: 2,
      type: "Strategic Ploy",
      phase: "Fight phase",
      text: `TARGET: One Grey Knights Infantry unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, Psychic weapons equipped by models in your unit have the [DEVASTATING WOUNDS] ability.`,
    },
  ],
};
