import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const bullyBoyz: DetachmentData = {
  name: "Bully Boyz",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Da Boss Is Watchin'",
      text: `At the start of your Command phase, in a turn in which you have not called a Waaagh!, if you have one or more **^^Warboss^^** models on the battlefield (or embarked within a **^^Transport^^** that is on the battlefield), you can call a Waaagh! for a second time this battle. When doing so, that second Waaagh! only counts as having been called for **^^Warboss^^**, **^^Nobz^^** and **^^Meganobz^^** units from your army.`,
    },
  ],
  stratagems: [
    {
      name: "Cut'em Down",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Movement phase, just after an enemy unit is selected to Fall Back",
      text: `TARGET: One Nobz or Meganobz unit from your army within Engagement Range of that enemy unit.

EFFECT: When that enemy unit Falls Back, all models in that enemy unit must take a Desperate Escape test. When doing so, if a Waaagh! is active for your unit, subtract 1 from each of those tests.`,
    },
    {
      name: "Hulking Brutes",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Nobz or Meganobz unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Armed To Dateef",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Nobz or Meganobz unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, re-roll a Hit roll of 1. If a Waaagh! is active for your unit, you can re-roll the Hit roll instead.`,
    },
    {
      name: "Crushing Impact",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Charge phase, just after a Nobz or Meganobz unit from your army ends a Charge move",
      text: `TARGET: That NOBZ or MEGANOBZ unit.

EFFECT: Select one enemy unit within Engagement Range of your unit, then roll one D6 for each model in your unit that is within Engagement Range of that enemy unit: for each 5+, that enemy unit suffers 1 mortal wound (to a maximum of 6 mortal wounds). If a Waaagh! is active for your unit, that enemy unit suffers 1 mortal wound for each 4+ instead.`,
    },
    {
      name: "Always Lookin' Fer A Fight",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase, just after an enemy unit is destroyed",
      text: `TARGET: One Nobz or Meganobz unit from your army that destroyed that enemy unit.

EFFECT: Until the end of the phase, each time your unit makes a Consolidation move, it can move up to D3+3" instead of up to 3". If a Waaagh! is active for your unit, it can move up to 6" instead.`,
    },
    {
      name: "Too Arrogant To Die",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Nobz or Meganobz unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not shot or fought this phase, roll one D6, adding 2 to the result if a Waaagh! is active for your unit. On a 5+, do not remove the destroyed model from play; it can shoot or fight after the attacking unit has finished making its attacks, and is then removed from play.`,
    },
  ],
};
