import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const cabalOfChaos: DetachmentData = {
  name: "Cabal of Chaos",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Empyric Wellspring",
      text: `Each time a unit from your army makes a Dark Pact, select one of the following abilities. Your unit has that ability until the end of the phase. 


**Leaping Warpflame**
While this unit is within 9" of one or more friendly ^^**Heretic Astartes Psyker^^** models, improve the Strength characteristic of ranged weapons equipped by models in this unit by 1. 


**Monstrous Manifestation**
While this unit is within 9" of one or more friendly ^^**Heretic Astartes Daemon Prince^^** or ^^**Heretic Astartes Daemon Prince with Wings^^** models, improve the Armour Penetration characteristic of melee weapons equipped by models in this unit by 1.`,
    },
  ],
  stratagems: [
    {
      name: "Shroud Of Chaos",
      cost: 1,
      type: "Battle Tactic",
      phase: "Start of your opponent's Shooting phase",
      text: `TARGET: One Heretic Astartes Psyker, Heretic Astartes Daemon Prince or Heretic Astartes Daemon Prince with Wings unit from your army.

EFFECT: Until the end of the phase, your unit has the following ability:

Shroud of Chaos (Aura): Models in friendly HERETIC ASTARTES units within 6" of this unit have the Stealth ability.`,
    },
    {
      name: "Unholy Haste",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Charge phase",
      text: `TARGET: One Heretic Astartes Infantry unit from your army that has not been selected to charge that phase.

EFFECT: Until the end of the phase, your unit is eligible to declare a charge in a turn in which it Advanced.`,
    },
    {
      name: "Baleful Blessing",
      cost: 1,
      type: "Epic Deed",
      phase: "Any phase, just after a Heretic Astartes unit from your army has a mortal wound allocated to it",
      text: `TARGET: That HERETIC ASTARTES unit.

EFFECT: Until the end of the phase, models in your unit have the Feel No Pain 5+ ability against mortal wounds.`,
    },
    {
      name: "Soulseekers",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One Heretic Astartes unit from your army that has not been selected to shoot that phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [IGNORES COVER] ability.`,
    },
    {
      name: "No Rest In Death",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One Heretic Astartes unit from your army within 9" of a Heretic Astartes Psyker, Heretic Astartes Daemon Prince or Heretic Astartes Daemon Prince with Wings unit from your army.

EFFECT: One model in your unit regains up to D3+1 lost wounds. If your unit has the Battleline keyword, you can return up to D3 destroyed models (excluding Character models) to your unit with their full wounds remaining, instead.`,
    },
    {
      name: "Mutation's Curse",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One Heretic Astartes Psyker unit from your army.

EFFECT: Select one visible enemy unit within 12" of your unit. Roll one D6: on a 1, that enemy unit suffers 1 mortal wound; on a 2-4, that enemy unit suffers D3 mortal wounds; on a 5-6, that enemy unit suffers 2D3 mortal wounds.`,
    },
  ],
};
