import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const ceramiteSentinels: DetachmentData = {
  name: "Ceramite Sentinels",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Adaptive Defence",
      text: `Each time an ^^**Adeptus Astartes**^^ model from your army makes an attack, if that model’s unit is within a terrain feature, re‑roll a Hit roll of 1 and re‑roll a Wound roll of 1. 


^^**Adeptus Astartes**^^ units from your army gain the ^^**Entrenched**^^ keyword while all of the following are true: 
- That unit is within a terrain feature.
- That unit was not set up on the battlefield this turn.
- No model in that unit has moved more than 3” this turn.`,
    },
  ],
  stratagems: [
    {
      name: "Armour Of Contempt",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Priority Strike",
      cost: 2,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Adeptus Astartes Infantry or Adeptus Astartes Mounted unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a CHARACTER, MONSTER or VEHICLE unit, you can re-roll the Wound roll.`,
    },
    {
      name: "Augmented Targeting",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot this phase.

EFFECT: Select either the [SUSTAINED HITS 1] or [LETHAL HITS] abilities. Until the end of the phase, ranged weapons equipped by models in your unit have the selected ability. If your unit is ENTRENCHED, until the end of the phase, ranged weapons equipped by models in your unit have the [SUSTAINED HITS 1] and [LETHAL HITS] abilities instead.`,
    },
    {
      name: "Unyielding Might",
      cost: 1,
      type: "Battle Tactic",
      phase: "Command phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that is within Engagement Range of one or more enemy units.

EFFECT: Until the start of your next Command phase, add 1 to the Objective Control characteristics of models in your unit.`,
    },
    {
      name: "Stand To The End",
      cost: 1,
      type: "Epic Deed",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not fought this phase, roll one D6, adding 1 to the result if it is an ENTRENCHED unit: on a 4+, do not remove it from play. That destroyed model can fight after the attacking unit has finished making its attacks, and is then removed from play.`,
    },
    {
      name: "Evasive Repositioning",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has shot",
      text: `TARGET: One Adeptus Astartes Infantry or Adeptus Astartes Mounted unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Your unit can make a Normal move of up to D6". If your unit is ENTRENCHED, you can re-roll the D6 to determine how far your unit can move.`,
    },
  ],
};
