import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const chaosCult: DetachmentData = {
  name: "Chaos Cult",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Desperate Devotion",
      text: `Each time a ^^**Damned**^^ unit from your army with the Dark Pacts ability is selected to make a Normal or Advance move or declare a charge (excluding units that arrived from Reserves this turn) it can make a Desperate Pact. If it does, until the end of the phase, add 2" to the Move characteristic of models in that unit and add 2 to Charge rolls made for that unit.


Desperate Pacts
Each time a unit makes a Desperate Pact, it must first take a Leadership test; if that test is failed, the unit suffers D3 mortal wounds before any effects of the Desperate Pact are resolved.`,
    },
  ],
  stratagems: [
    {
      name: "Crazed Focus",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One DAMNED unit from your army that has not been selected to shoot this phase.

EFFECT: Your unit can make a Desperate Pact. If it does, until the end of the phase, each time a model in your unit makes an attack, improve the Armour Penetration characteristic of that attack by 1, and if your unit did not fail the resulting Leadership test when making that Desperate Pact, improve the Strength characteristic of that attack by 1 as well.`,
    },
    {
      name: "Infernal Sacrifice",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One DAMNED unit from your army that has not been selected to fight this phase.

EFFECT: Your unit can make a Desperate Pact. If it does, your unit suffers D3 mortal wounds (in addition to any suffered for failing the resulting Leadership test), and until the end of the phase, add 1 to the Attacks characteristic of the melee weapons equipped by models in your unit, and if your unit did not fail the resulting Leadership test when making that Desperate Pact, until the end of the phase, improve the Strength characteristic of those weapons by 1 as well.`,
    },
    {
      name: "Chosen For Glory",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One DAMNED unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Your unit can make a Desperate Pact. If it does, until the end of the phase, each time a model in your unit makes an attack, you can re-roll the Hit roll, and if your unit did not fail the resulting Leadership test when making that Desperate Pact, you can re-roll the Wound roll as well.`,
    },
    {
      name: "Mortal Thralls",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected ts targets",
      text: `TARGET: One HERETIC ASTARTES unit from your army that was selected as the target of one or more of the attacking units attacks, and one friendly DAMNED unit within 3" of your unit and visible to both your unit and the attacking unit.

EFFECT: Until the end of the phase, while your DAMNED unit is on the battlefield, each time your opponent would make a Wound roll for an attack that targets your HERETIC ASTARTES unit, if your DAMNED unit is visible to the attacking model and is an eligible target for that attack, no roll is made; instead, your DAMNED unit suffers a number of mortal wounds equal to the Damage characteristic of that attack.`,
    },
    {
      name: "Reckless Haste",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Charge phase",
      text: `TARGET: One DAMNED unit from your army.

EFFECT: Until the end of the turn, your unit is eligible to declare a charge in a turn in which it Advanced.`,
    },
    {
      name: "Selfless Demise",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One DAMNED unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has resolved all of its attacks, each time a model in your unit is destroyed, roll one D6 on a 6, the attacking unit suffers 1 mortal wound after all of its attacks have been resolved.`,
    },
  ],
};
