import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const creationsOfBile: DetachmentData = {
  name: "Creations of Bile",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Creations of Bile",
      text: `At the start of the battle, select which augmentations are active for ^^**Heretic Astartes Infantry**^^ models (excluding ^^**Damned**^^ models) from your army until the end of the battle. To do so, either select one from the list below, or randomly determine two by rolling two D6. If ^^**Fabius Bile**^^ is your ^^**Warlord**^^, when randomly determining your augmentations, you can re‑roll one or both of the dice. Duplicated augmentations have no additional effect.


1 - **Cholinergic Accelerants:** Add 1 to the Attacks characteristic of melee weapons equipped by this model.
2 - **Hyperadrenal Infusion:** Add 2" to the Move characteristic of this model.
3 - **Paraneural Reactions:** Improve the Weapon Skill characteristic of melee weapons equipped by this model by 1.
4 - **Supracutaneous Chitination:** Improve the Toughness characteristic of this model by 1.
5 - **Macrotensile Sinews:** Add 1 to the Strength characteristic of melee weapons equipped by this model.
6 - **Ophthalmic Enhancement:** Improve the Ballistic Skill characteristic of ranged weapons equipped by this model by 1.`,
    },
  ],
  stratagems: [
    {
      name: "Masters Are Watching",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Heretic Astartes Infantry unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not fought this phase, roll one D6, subtracting 1 from the result if it is a Damned unit: on a 4+, do not remove it from play. That destroyed model can fight after the attacking unit has finished making its attacks, and is then removed from play.`,
    },
    {
      name: "Autostimulants",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Start of your Charge phase",
      text: `TARGET: One Heretic Astartes Infantry unit from your army.

EFFECT: Until the end of the turn, your unit is eligible to declare a charge in a turn in which it Advanced.`,
    },
    {
      name: "Delayed Mutations",
      cost: 2,
      type: "Strategic Ploy",
      phase: "Your Command phase",
      text: `TARGET: One Heretic Astartes Infantry unit (excluding Damned units) from your army.

EFFECT: Your unit suffers D3 mortal wounds. Then select one augmentation (see Experimental Augmentations). Until the start of your next Command phase, models in your unit have the selected augmentation in addition to any other augmentations they have.`,
    },
    {
      name: "Specimens For The Spider",
      cost: 2,
      type: "Strategic Ploy",
      phase: "Fight phase",
      text: `TARGET: One Heretic Astartes Infantry unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes a melee attack that targets a CHARACTER unit, you can re-roll the Wound roll. After your unit has fought, if one or more enemy CHARACTER models were destroyed as a result of those attacks, select one enemy unit within 6" of your unit. That enemy unit must take a Battle-shock test. If the enemy WARLORD was destroyed as a result of those attacks, each enemy unit within 6" of your unit must take a Battle-shock test instead.`,
    },
    {
      name: "Monstrous Visages",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Heretic Astartes Infantry unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time an attack targets your unit, subtract 1 from the Hit roll.`,
    },
    {
      name: "Diabolic Regeneration",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Command phase",
      text: `TARGET: One Heretic Astartes Infantry unit (excluding Damned units) from your army.

EFFECT: One destroyed model (excluding Character models) is returned to your unit. If your unit is a Battleline unit, D3 destroyed models (excluding CHARACTER models) are returned to your unit instead.`,
    },
  ],
};
