import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const cultOfTheArkifane: DetachmentData = {
  name: "Cult of the Arkifane",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Soul Forge Boons",
      text: `^^**Heretic Astartes Vehicle^^** units from your army gain the ^^**Daemon^^** keyword. 
^^**Heretic Astartes Vehicle, Lord Discordant^^** and ^^**Vashtorr the Arkifane^^** units from your army gain the ^^**Soul Forge^^** keyword. 
^^**Soul Forge^^** units from your army have a 5+ invulnerable save.`,
    },
  ],
  stratagems: [
    {
      name: "Touch Of The Arkifane",
      cost: 1,
      type: "Battle Tactic",
      phase: "Any phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army (excluding Damned units) that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, if your unit is selected to make a Dark Pact, you can select both abilities for that unit's weapons to gain.`,
    },
    {
      name: "Balefire Boon",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Soul Forge unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, improve the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Soul-Tally Offering",
      cost: 2,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Soul Forge unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a CHARACTER, MONSTER or VEHICLE unit, you can re-roll the Wound roll.`,
    },
    {
      name: "Biomechanoid Regeneration",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Command phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army (excluding Damned units).

EFFECT: One model in your unit regains up to D3 lost wounds. If your unit has the Soul Forge keyword, one model in your unit regains up to 3 lost wounds instead.`,
    },
    {
      name: "Forge-Fire Surge",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after a HERETIC ASTARTES unit from your army Advances",
      text: `TARGET: That HERETIC ASTARTES unit.

EFFECT: Until the end of the turn, your unit is eligible to shoot in a turn in which it Advanced. If your unit has the Soul Forge keyword, until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Advanced instead.`,
    },
    {
      name: "Unholy Fortitude",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Soul Forge unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, add 1 to the Toughness characteristic of models in your unit.`,
    },
  ],
};
