import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const daBigHunt: DetachmentData = {
  name: "Da Big Hunt",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Da Hunt Is On",
      text: `At the start of your Command phase, select one **^^Monster^^**, **^^Vehicle^^**, or **^^Character^^** unit from your opponent's army. Until the start of your next Command phase, that enemy unit is your Prey:
- Each time a **^^Beast Snagga^^** unit from your army declares a charge that includes your Prey as one of the targets, you can re-roll the Charge roll.
- Each time a **^^Beast Snagga^^** model from your army makes an attack that targets your Prey, improve the Armour Penetration characteristic of that attack by 1.`,
    },
  ],
  stratagems: [
    {
      name: "Stalkin' Taktiks",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Beast Snagga Infantry or Beast Snagga Mounted unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a ranged attack targets your unit, models in your unit have the Benefit of Cover against that attack. In addition, if your unit has the INFANTRY keyword, until the end of the phase, models in your unit have the Stealth ability.`,
    },
    {
      name: "Drag It Down",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One Beast Snagga unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, melee weapons equipped by models in your unit have the [SUSTAINED HITS 1] ability. In addition, each time a model in your unit makes a melee attack that targets your Prey, a Critical Hit is scored on an unmodified Hit roll of 5+, instead of only a 6.`,
    },
    {
      name: "Dat One's Even Bigga!",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Charge phase",
      text: `TARGET: One Beast Snagga unit from your army.

EFFECT: Until the end of the phase, your unit is eligible to charge in a turn in which it Advanced or Fell Back. In addition, you can re-roll Charge rolls made for your unit, provided one of the targets of that charge is your Prey.`,
    },
    {
      name: "Where D'ya Fink You're Going?",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Fall Back move",
      text: `TARGET: One Beast Snagga Infantry or Beast Snagga Mounted unit from your army that was within Engagement Range of that enemy unit at the start of the phase.

EFFECT: If your unit is not within Engagement Range of one or more enemy units, it can make a Normal move of up to 6".`,
    },
    {
      name: "Instinctive Hunters",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of your opponent's Fight phase",
      text: `TARGET: One Beast Snagga unit from your army that is not within Engagement Range of one or more enemy unit.

EFFECT: Remove your unit from the battlefield and place it into Strategic Reserves.`,
    },
    {
      name: "Unstoppable Momentum",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Charge phase, just after a Beast Snagga Mounted unit from your army ends a Charge move",
      text: `TARGET: That Beast Snagga unit.

EFFECT: Select one enemy unit within Engagement Range of your unit and roll one D6 for each model in your unit: for each 4+, that enemy unit suffers 1 mortal wound (to a maximum of 6 mortal wounds). If that enemy unit is your Prey, roll three additional D6.`,
    },
  ],
};
