import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const deceptors: DetachmentData = {
  name: "Deceptors",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Masters of Misdirection",
      text: `In the Declare Battle Formations step, you can select a number of ^^**Legionaries**^^ and ^^**Cultist Mob**^^ units from your army; until the end of the battle, those units, and any ^^**Character**^^ units attached to them (excluding ^^**Epic Heroes**^^), have the Infiltrator ability. The maximum number of units you can select in this way depends on the battle size, as shown below.


**Battle Size | Legionaries | Cultist Mobs**
Incursion | Up to 2 units | Up to 2 units
Strike Force | Up to 3 units | Up to 3 units
Onslaught | Up to 4 units | Up to 4 units`,
    },
  ],
  stratagems: [
    {
      name: "Pick Them Off",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a unit that is below its Starting Strength, you can re-roll the Hit roll. If the target is Below Half-strength, you can re-roll the Wound roll as well.`,
    },
    {
      name: "From All Sides",
      cost: 1,
      type: "Battle Tactic",
      phase: "Start of your Charge phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army.

EFFECT: Until the end of the phase, add 1 to Charge rolls made for your unit for each other HERETIC ASTARTES unit from your army that made a Charge move this phase (to a maximum of +3)`,
    },
    {
      name: "Coils Of Deception",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after a HERETIC ASTARTES unit from your army Falls Back",
      text: `TARGET: That HERETIC ASTARTES unit.

EFFECT: Until the end of the turn, your unit is eligible to shoot in a turn in which it Fell Back`,
    },
    {
      name: "Scrambled Coordinates",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Start of the Reinforcements step of your opponent's Movement phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army.

EFFECT: Until the end of the phase, enemy units that are set up on the battlefield from Reserves cannot be set up within 12" horizontally of your unit.`,
    },
    {
      name: "Relentless Pursuit",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move",
      text: `TARGET: One HERETIC ASTARTES INFANTRY or HERETIC ASTARTES MOUNTED unit from your army that is within 9" of that enemy unit and not within Engagement Range of one or more enemy units.

EFFECT: Your unit can make a Normal move of up to 6".`,
    },
    {
      name: "Detonator",
      cost: 1,
      type: "Wargear",
      phase: "Any phase, just after an enemy model with the Deadly Demise ability (excluding TITANIC models) is destroyed",
      text: `TARGET: One HERETIC ASTARTES CHARACTER unit from your army that was within 18" of that enemy model when it was destroyed.

EFFECT: Your opponent does not roll to determine whether mortal wounds are inflicted by their model's Deadly Demise ability. Instead, mortal wounds are automatically inflicted (if that ability inflicts a random number of mortal wounds, your opponent rolls to determine that number as normal).`,
    },
  ],
};
