import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const dreadTalons: DetachmentData = {
  name: "Dread Talons",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Terror Descends (Aura)",
      text: `In the Battle-shock step of your opponent's Command phase, if an enemy unit that is below its Starting Strength is within 12" of one or more ^^**Heretic Astartes**^^ units from your army, that enemy unit must take a Battle-shock test.
Each time an enemy unit within 12" of one or more ^^**Heretic Astartes**^^ units from your army takes a Battle-shock test, subtract 1 from the result.
Enemy units affected by this Detachment rule do not need to take any other Battle-shock tests in the same phase.`,
    },
  ],
  stratagems: [
    {
      name: "Pitiless Hunters",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One HERETIC ASTARTES INFANTRY unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a unit that is Battle-shocked and/or Below Half-strength, you can re-roll the Hit roll and you can re-roll the Wound roll.`,
    },
    {
      name: "Depthless Cruelty",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One HERETIC ASTARTES INFANTRY unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a unit that is Battle-shocked and/or Below Half-strength, improve the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Bloody Example",
      cost: 1,
      type: "Epic Deed",
      phase: "Fight phase, just after a HERETIC ASTARTES unit from your army destroys a CHARACTER unit",
      text: `TARGET: That HERETIC ASTARTES unit.

EFFECT: Each enemy unit within 12" of and visible to your unit must take a Battle-shock test.`,
    },
    {
      name: "Merciless Pursuit",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of your opponent's Movement phase",
      text: `TARGET: One HERETIC ASTARTES INFANTRY unit from your army that is not within Engagement range of one or more enemy units.

EFFECT: Select one enemy unit that Fell Back this turn and is within 6" of your unit. Your unit can declare a charge as if it were your Charge phase. When doing so, you can only select that enemy unit as the target of that charge (and only if it is an eligible target). Note that even if this charge is successful, your unit does not receive any Charge bonus this turn.`,
    },
    {
      name: "Screaming Descent",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Reinforcements step of your Movement phase, from the second battle round onwards",
      text: `TARGET: One HERETIC ASTARTES JUMP PACK unit from your army that is in Reserves.

EFFECT: Set your unit up anywhere on the battlefield that is more than 6" horizontally away from all enemy units, but until the end of the turn, it is not eligible to declare a charge. Then select one enemy INFANTRY or MOUNTED unit within 9" of and visible to your unit: that unit must take a Battle-shock test.`,
    },
    {
      name: "Relentless Terror",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after a HERETIC ASTARTES INFANTRY unit from your army Falls Back",
      text: `TARGET: That HERETIC ASTARTES INFANTRY unit.

EFFECT: Until the end of the turn, your unit is eligible to declare a charge in a turn in which it Fell Back.`,
    },
  ],
};
