import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const dreadMob: DetachmentData = {
  name: "Dread Mob",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Try Dat Button!",
      text: `Each time a **^^Mek^^**, **^^Orks Walker^^** or **^^Grots Vehicle^^** unit from your army is selected to shoot or fight, roll one D6. Until the end of the phase, weapons equipped by models in that unit have the corresponding ability shown in the table below.
Alternatively, when such a unit is selected to shoot or fight, you can select one of the abilities above instead of rolling the D6. If you do, until the end of the phase, weapons equipped by models in that unit have the **[HAZARDOUS]* ability as well.
If a weapon equipped by a model you army has the **[HAZARDOUS]** ability from multiple sources, each time you take a Hazardous test for that weapon, it is failed on a roll of a 1 or a 2.

**^^Gretchin^^** units from your army gain the **^^Battleline^^** keyword.`,
    },
    {
      name: "Hazardous",
      text: `Weapons with **[HAZARDOUS]** in their profile are known as Hazardous weapons. Each time a unit is selected to shoot or fight, after that unit has resolved all of its attacks, for each Hazardous weapon that targets were selected for when resolving those attacks, that unit must take one Hazardous test. To do so, roll one D6: on a 1, that test is failed. For each failed test you must resolve the following sequence (resolve each failed test one at a time): 

■ If possible, select one model in that unit that has lost one or more wounds and is equipped with one or more Hazardous weapons. 
■ Otherwise, if possible, select one model in that unit (excluding **^^Character^^** models) equipped with one or more Hazardous weapons. 
■ Otherwise, select one **^^Character^^** model in that unit equipped with one or more Hazardous weapons. 

If a model was selected, that unit suffers 3 mortal wounds and when allocating those mortal wounds, they must be allocated to the selected model. 

If a unit from a player’s army is selected as the target of the Fire Overwatch Stratagem in their opponent’s Charge phase, any mortal wounds inflicted by Hazardous tests are allocated after the charging unit has ended its Charge move.`,
    },
    {
      name: "Sustained Hits",
      text: `Weapons with **[SUSTAINED HITS X]** in their profile are known as Sustained Hits weapons. Each time an attack is made with such a weapon, if a Critical Hit is rolled, that attack scores a number of additional hits on the target as denoted by ‘x’`,
    },
    {
      name: "Lethal Hits",
      text: `Weapons with **[LETHAL HITS]** in their profile are known as Lethal Hits weapons. Each time an attack is made with such a weapon, a Critical Hit automatically wounds the target.`,
    },
  ],
  stratagems: [
    {
      name: "Dakka! Dakka! Dakka!",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One Orks Walker or Grots Vehicle unit from your army that has not been selected to shoot this phase.

EFFECT: Each time you use this Stratagem, you can choose to push it. Until the end of the phase, each time a model in your unit makes an attack, re-roll a Hit roll of 1. If you chose to push it, you can re-roll the Hit roll instead and, until the end of the phase, ranged weapons equipped by models in your unit have the [HAZARDOUS] ability as well.`,
    },
    {
      name: "Extra Gubbinz",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Orks Walker or Grots Vehicle unit from your army (excluding TITANIC units) that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time an attack is allocated to a model in your unit, subtract 1 from the Damage characteristic of that attack.`,
    },
    {
      name: "Bigger Shells For Bigger Gitz",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One Mek, Orks Walker or Grots Vehicle unit from your army that has not been selected to shoot this phase.

EFFECT: Each time you use this Stratagem, you can choose to push it. Until the end of the phase, each time a model in your unit makes an attack that targets a MONSTER or VEHICLE, add 1 to the Wound roll. If you chose to push it, add 1 to the Damage characteristic of that attack and, until the end of the phase, ranged weapons equipped by models in your unit have the [HAZARDOUS] ability as well.`,
    },
    {
      name: "Klankin' Klaws",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One Orks Walker unit from your army that has not been selected to fight this phase.

EFFECT: Each time you use this Stratagem, you can choose to push it. Until the end of the phase, add 2 to the Strength characteristic of melee weapons equipped by models in your unit and, if you chose to push it, until the end of the phase, add 1 to the Damage characteristic of those weapons and they have the [HAZARDOUS] ability as well.`,
    },
    {
      name: "Conniving Runts",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move",
      text: `TARGET: One Gretchin unit from your army that is within 9" of that enemy unit and not within Engagement Range of any enemy units.

EFFECT: Roll one D6: on a 4+, that enemy unit suffers D3+1 mortal wounds. Your unit can then make a Normal move.`,
    },
    {
      name: "Superfuelled Boiler",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after an Orks Walker unit from your army has been selected to Advance",
      text: `TARGET: That Orks Walker unit.

EFFECT: Until the end of the turn, you can re-roll Advance rolls made for your unit and ranged weapons equipped by models in your unit have the [ASSAULT] ability.`,
    },
  ],
};
