import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const fellhammerSiegeHost: DetachmentData = {
  name: "Fellhammer Siege-host",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Iron Fortitude",
      text: `Each time a ranged attack targets a ^^**Heretic Astartes**^^ unit from your army (excluding ^^**Damned**^^ units), if the Strength characteristic of that attack is greater than the Toughness characteristic of that unit, subtract 1 from the Wound roll.`,
    },
  ],
  stratagems: [
    {
      name: "Persistent Assailants",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that was selected as the target of one or more attacks this phase and has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, you can re-roll the Hit roll, and if your unit is Below Half-strength you can re-roll the Wound roll as well.`,
    },
    {
      name: "Pitiless Cannonade",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a unit that is Below Half-strength, a successful unmodified Hit roll of 5+ scores a Critical Hit`,
    },
    {
      name: "Point-Blank Destruction",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that is within Engagement Range of one or more enemy units and has not been selected to shoot this phase.

EFFECT: Until the end of the phase, your unit's ranged weapons (excluding Blast weapons) have the [PISTOL] ability.`,
    },
    {
      name: "Brutal Attrition",
      cost: 1,
      type: "Epic Deed",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One HERETIC ASTARTES INFANTRY unit from your army (excluding DAMNED units) that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a melee attack is allocated to your unit, after the attacking unit has finished making its attacks, roll one D6 (to maximum of six D6 per attacking unit): for each 4+, the attacking unit suffers 1 mortal wound.`,
    },
    {
      name: "Siegecraft",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Start of your opponents Charge phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army.

EFFECT: Until the end of the phase, each time an enemy unit selects your unit as a target of a charge, subtract 2 from the Charge roll (this is not cumulative with any other negative modifiers to that Charge roll).`,
    },
    {
      name: "Steadfast Determination",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One HERETIC ASTARTES unit from your army (excluding DAMNED units) that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, models in your unit have the Feel No Pain 5+ ability.`,
    },
  ],
};
