import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const freebooterKrew: DetachmentData = {
  name: "Freebooter Krew",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Here Be Loot",
      text: `At the start of your Command phase, select one objective marker. Until the start of your next Command phase, that objective marker is your loot objective.

Each time a model in an **^^Orks Infantry^^**, **^^Orks Mounted^^** or **^^Orks Walker^^** unit from your army makes an attack, that attack has the **[SUSTAINED HITS 1]** ability if either or both of the following are true:

- That model's unit is within range of your loot objective.
- That attack targets a unit within range of your loot objective.`,
    },
    {
      name: "Sustained Hits",
      text: `Weapons with **[SUSTAINED HITS X]** in their profile are known as Sustained Hits weapons. Each time an attack is made with such a weapon, if a Critical Hit is rolled, that attack scores a number of additional hits on the target as denoted by ‘x’`,
    },
  ],
  stratagems: [
    {
      name: "Boardin' Rush",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Movement phase",
      text: `TARGET: One ORKS unit from your army that has not been selected to move this phase.

EFFECT: Until the end of the phase, each time your unit Advances, do not make an Advance roll. Instead, until the end of the phase, add 6" to the Move characteristic of models in your unit.`,
    },
    {
      name: "Bash And Grab",
      cost: 1,
      type: "Battle Tactic",
      phase: "The Fight phase",
      text: `TARGET: One ORKS unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets an enemy unit within range of the loot objective, you can re-roll the Wound roll.`,
    },
    {
      name: "Grab And Bash",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Command phase",
      text: `TARGET: One ORKS unit from your army (excluding Gretchin units) that is within range of the loot objective.

EFFECT: Until the start of your next Command phase, the Waaagh! is active for your unit, even if you have already called a Waaagh! this battle.

Designer's Note: This means that any abilities that are in effect while the Waaagh! is active for your army will be in effect for your unit.`,
    },
    {
      name: "Deck Fraggers",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One ORKS unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit targets an INFANTRY unit with a ranged weapon, that weapon has the [BLAST] ability.`,
    },
    {
      name: "Rolling Loot-Heap",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One Flash Gitz unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [ANTI-VEHICLE 4+] ability.`,
    },
    {
      name: "Krump And Run",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit falls back",
      text: `TARGET: One ORKS unit from your army that was within engagement range of that enemy unit at the start of the phase and is not within range of one or more enemy units.

EFFECT: Your unit can make a Normal move of up to 6".`,
    },
  ],
};
