import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const greenTide: DetachmentData = {
  name: "Green Tide",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Mob Mentality",
      text: `Each time an attack targets a **^^Boyz^^** unit from your army, models in that unit have a 6+ invulnerable save against that attack. Each time an attack targets a **^^Boyz^^** unit from your army that contains 10 or more models, models in that unit have a 5+ invulnerable save against that attack.`,
    },
  ],
  stratagems: [
    {
      name: "Competitive Streak",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One Boyz unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, re-roll a Wound roll of 1. If your unit contains 10 or more models, re-roll the Wound roll instead.`,
    },
    {
      name: "Bulldozer Brutality",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One Boyz unit from your army that has not been selected to fight this phase and is within Engagement Range of one or more enemy units.

EFFECT: Until the end of the phase, each time your unit is selected to fight, when determining which models in your unit are eligible to fight, any models in your unit that are within 3" of one or more enemy models are eligible to fight. When resolving those attacks, such models can target one of those enemy units that is within 3" of them and within Engagement Range of their unit.`,
    },
    {
      name: "Tide Of Muscle",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Charge phase",
      text: `TARGET: One Boyz unit from your army that has not declared a charge this phase.

EFFECT: Until the end of the phase, each time your unit declares a charge, add 1 to the Charge roll and, if your unit contains 10 or more models, you can re-roll the Charge roll.'`,
    },
    {
      name: "Braggin' Rights",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Command phase",
      text: `TARGET: Two Boyz units from your army that are within 6" of each other.

EFFECT: Until the start of your next Command phase, while those two units are within 6" of each other, they both count as containing 10 or more models for the purposes of your Detachment rule, any Enhancements models from your army have and any Stratagems you use.`,
    },
    {
      name: "Come On Ladz!",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Command phase",
      text: `TARGET: One Boyz unit from your army.

EFFECT: Return up to D3+2 destroyed models to your unit (excluding Character models).`,
    },
    {
      name: "Go Get 'em!",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Boyz unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: After the attacking unit has shot, your unit can make a Go Get 'Em! move. To do so, roll one D6: each model in your unit can move a distance in inches up to the result, but your unit must end that move as close as possible to the closest enemy unit. When doing so, those models can be moved within Engagement Range of that enemy unit. If your unit contains 10 or more models, you can re-roll the D6 to determine how far your unit can move.`,
    },
  ],
};
