import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const hallowedConclave: DetachmentData = {
  name: "Hallowed Conclave",
  faction: "Imperium - Grey Knights",
  rules: [
    {
      name: "Duty Before All",
      text: `^^**Grey Knights Terminator**^^ units from your army are eligible to shoot and declare a charge in a turn in which they Fell Back.`,
    },
  ],
  stratagems: [
    {
      name: "Giants Of The Battlefield",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One Grey Knights Terminator unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, add 1 to the Attacks characteristic of melee weapons equipped by models in your unit.`,
    },
    {
      name: "Precognitive Strategies",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move",
      text: `TARGET: One Grey Knights Infantry unit from your army that is within 9" of that enemy unit and not within Engagement Range of one or more enemy units.

EFFECT: Your unit can make a Normal move of up to D6".`,
    },
    {
      name: "Shining Resolve",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Grey Knights Infantry unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time an attack targets your unit, if the Strength characteristic of that attack is greater than the Toughness characteristic of your unit, subtract 1 from the Wound roll.`,
    },
    {
      name: "Grind Them Underfoot",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Charge phase, just after a Grey Knights Terminator unit from your army ends a Charge move",
      text: `TARGET: That GREY KNIGHTS unit.

EFFECT: Select one enemy unit within Engagement Range of your unit, then roll one D6 for each model in your unit that is within Engagement Range of that enemy unit: for each 4+, that enemy unit suffers 1 mortal wound (to a maximum of 6 mortal wounds).`,
    },
    {
      name: "Point-Blank Purgation",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One Grey Knights Infantry unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, storm bolter weapons equipped by models in your unit have the [PISTOL] and [TWIN-LINKED] abilities.`,
    },
    {
      name: "Unending Fidelity",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Grey Knights Infantry unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not shot or fought this phase, roll one D6. On a 4+, do not remove the destroyed model from play; it can shoot or fight after the attacking unit has finished making its attacks, and is then removed from play.`,
    },
  ],
};
