import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const headhunterTaskForce: DetachmentData = {
  name: "Headhunter Task Force",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Target Sighted",
      text: `Each time a Tank Ace unit from your army (see below) Advances, do not make an Advance roll for it. Instead, until the end of the phase, add 6" to the Move characteristic of models in that unit. Each time a Tank Ace unit from your
army shoots in your Shooting phase, if that unit did not Advance this turn, you can re‑roll the Damage roll.


Adeptus Astartes Vehicle units from your army (excluding Fortifications, Drop Pods, Walkers and units that can Fly)
have the Tank Ace keyword. In the Muster Armies step, you can select up to three Tank Ace units from your
army to gain the Character keyword. 


Designer’s Note: This means that the selected units can be given enhancements, and one of them can be selected as your Warlord.`,
    },
  ],
  stratagems: [
    {
      name: "Target Weak Point",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One Tank Ace unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes a ranged attack that targets a MONSTER or VEHICLE unit, improve the Armour Penetration characteristic of that attack by 1.

RESTRICTIONS: A unit cannot be targeted with this and the Kill Shot Stratagem in the same phase.`,
    },
    {
      name: "Kill Shot",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One Tank Ace unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a MONSTER or VEHICLE unit, re-roll a Wound roll of 1. If the target unit is below its Starting Strength, you can re-roll the Wound roll instead.

RESTRICTIONS: A unit cannot be targeted with this and the Target Weak Point Stratagem in the same phase.`,
    },
    {
      name: "Machine Vengeance",
      cost: 1,
      type: "Epic Deed",
      phase: "Your opponent's Shooting phase, just after an enemy unit has shot",
      text: `TARGET: One Tank Ace unit from your army (excluding units containing one or more models with a Wounds characteristic of 16+) that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Your unit can shoot as if it were your Shooting phase, but must target only that enemy unit when doing so, and can only do so if that enemy unit is visible and an eligible target.`,
    },
    {
      name: "Armour Of Contempt",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Rapid Gunnery",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, your unit is eligible to shoot in a turn in which it Fell Back.`,
    },
    {
      name: "Reactive Repositioning",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move",
      text: `TARGET: One Tank Ace unit from your army (excluding units containing one or more models with a Wounds characteristic of 16+) that is within 9" of that enemy unit.

EFFECT: Your unit can make a Normal move of up to D6".`,
    },
  ],
};
