import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const huronsMarauders: DetachmentData = {
  name: "Huron's Marauders",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Tyrannical Motivation",
      text: `In your Command phase, select one of the following abilities. Until the start of your next Command phase, each ^^**Heretic Astartes Infantry**^^ unit from your army has that ability. At the start of each phase, if such a unit is visible to a friendly **^^Huron Blackheart**^^ model, until the end of the phase, it has both of the following abilities.


**Huron's Elite**
Each time a model in this unit makes an attack, add 1 to the Hit roll.


**Mobile Marauders**
This unit is eligible to shoot and declare a charge in a turn in which it Fell Back. 
***Designer’s Note:** If a unit is gaining eligibility to shoot and declare a charge in a turn in which it Fell Back as a result of being visible to Huron Blackheart, but after making a Fall Back move it is no longer visible to Huron Blackheart, that unit will not be eligible to shoot in your Shooting phase or to declare a charge in your Charge phase unless it is visible again at the start of the respective phase.*`,
    },
  ],
  stratagems: [
    {
      name: "Hardened Killers",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Command phase",
      text: `TARGET: One Damned unit from your army.

EFFECT: Select one of the following effects:
Improve the Ballistic Skill characteristic of ranged weapons equipped by models in this unit by 1.Improve the Attacks characteristic of Rapid Fire weapons equipped by models in this unit by 1.Improve the Save characteristic of models in this unit by 1.Until the start of your next turn, your unit has the benefit of that effect.`,
    },
    {
      name: "Seize The Prize",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Movement phase, just after a HERETIC ASTARTES unit (excluding Monsters and Vehicles) from your army has been selected to Advance",
      text: `TARGET: That HERETIC ASTARTES unit.

EFFECT: Do not make an Advance roll for your unit. Instead, until the end of the phase add 6" to the Move characteristic of models in your unit.`,
    },
    {
      name: "Reavers' Flurry",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Fight phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that made a Charge move this turn.

EFFECT: Until the end of the phase, add 1 to the Attacks characteristics of melee weapons equipped by models in your unit.`,
    },
    {
      name: "At The Tyrant's Command",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One HERETIC ASTARTES unit (excluding Monsters and Vehicles) from your army.

EFFECT: Until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Advanced.`,
    },
    {
      name: "Encircling Surge",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of your opponent's Fight phase",
      text: `TARGET: One HERETIC ASTARTES unit (excluding Monsters and Vehicles) from your army that is within 6" of one or more battlefield edges and not within Engagement Range of one or more enemy units.

EFFECT: Remove your unit from the battlefield and place it into Strategic Reserves.`,
    },
    {
      name: "To The Favoured The Spoils",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has shot",
      text: `TARGET: One HERETIC ASTARTES unit from your army that lost one or more wounds as a result of those attacks.

EFFECT: Your unit can make a Surge move. To do so, roll one D6: models in your unit move a number of inches up to the result, but your unit must end that move as close as possible to the closest enemy unit (excluding AIRCRAFT). When doing so, those models can be moved within Engagement Range of that enemy unit.`,
    },
  ],
};
