import type { DetachmentData } from "./types";
import { _1stCompanyTaskForce } from "./1st-company-task-force";
import { anvilSiegeForce } from "./anvil-siege-force";
import { auguriumTaskForce } from "./augurium-task-force";
import { auricChampions } from "./auric-champions";
import { banishers } from "./banishers";
import { bastionTaskForce } from "./bastion-task-force";
import { bladeOfUltramar } from "./blade-of-ultramar";
import { blitzBrigade } from "./blitz-brigade";
import { brotherhoodStrike } from "./brotherhood-strike";
import { bullyBoyz } from "./bully-boyz";
import { cabalOfChaos } from "./cabal-of-chaos";
import { ceramiteSentinels } from "./ceramite-sentinels";
import { chaosCult } from "./chaos-cult";
import { creationsOfBile } from "./creations-of-bile";
import { cultOfTheArkifane } from "./cult-of-the-arkifane";
import { daBigHunt } from "./da-big-hunt";
import { deceptors } from "./deceptors";
import { dreadMob } from "./dread-mob";
import { dreadTalons } from "./dread-talons";
import { fellhammerSiegeHost } from "./fellhammer-siege-host";
import { firestormAssaultForce } from "./firestorm-assault-force";
import { freebooterKrew } from "./freebooter-krew";
import { gladiusTaskForce } from "./gladius-task-force";
import { greenTide } from "./green-tide";
import { hallowedConclave } from "./hallowed-conclave";
import { headhunterTaskForce } from "./headhunter-task-force";
import { huronsMarauders } from "./hurons-marauders";
import { ironstormSpearhead } from "./ironstorm-spearhead";
import { kultOfSpeed } from "./kult-of-speed";
import { librariusConclave } from "./librarius-conclave";
import { lionsOfTheEmperor } from "./lions-of-the-emperor";
import { moreDakka } from "./more-dakka";
import { nightmareHunt } from "./nightmare-hunt";
import { nullMaidenVigil } from "./null-maiden-vigil";
import { orbitalAssaultForce } from "./orbital-assault-force";
import { pactboundZealots } from "./pactbound-zealots";
import { reclamationForce } from "./reclamation-force";
import { renegadeRaiders } from "./renegade-raiders";
import { renegadeWarband } from "./renegade-warband";
import { sancticSpearhead } from "./sanctic-spearhead";
import { shieldHost } from "./shield-host";
import { solarSpearhead } from "./solar-spearhead";
import { soulforgedWarpack } from "./soulforged-warpack";
import { speedwaaagh } from "./speedwaaagh";
import { stormlanceTaskForce } from "./stormlance-task-force";
import { taktikalBrigade } from "./taktikal-brigade";
import { talonsOfTheEmperor } from "./talons-of-the-emperor";
import { vanguardSpearhead } from "./vanguard-spearhead";
import { veteransOfTheLongWar } from "./veterans-of-the-long-war";
import { warHorde } from "./war-horde";
import { warpbaneTaskForce } from "./warpbane-task-force";
import { warpstrikeChampions } from "./warpstrike-champions";

export type { DetachmentData, DetachmentRule, Stratagem } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
const detachmentsByName: Record<string, DetachmentData> = {
  [_1stCompanyTaskForce.name]: _1stCompanyTaskForce,
  [anvilSiegeForce.name]: anvilSiegeForce,
  [auguriumTaskForce.name]: auguriumTaskForce,
  [auricChampions.name]: auricChampions,
  [banishers.name]: banishers,
  [bastionTaskForce.name]: bastionTaskForce,
  [bladeOfUltramar.name]: bladeOfUltramar,
  [blitzBrigade.name]: blitzBrigade,
  [brotherhoodStrike.name]: brotherhoodStrike,
  [bullyBoyz.name]: bullyBoyz,
  [cabalOfChaos.name]: cabalOfChaos,
  [ceramiteSentinels.name]: ceramiteSentinels,
  [chaosCult.name]: chaosCult,
  [creationsOfBile.name]: creationsOfBile,
  [cultOfTheArkifane.name]: cultOfTheArkifane,
  [daBigHunt.name]: daBigHunt,
  [deceptors.name]: deceptors,
  [dreadMob.name]: dreadMob,
  [dreadTalons.name]: dreadTalons,
  [fellhammerSiegeHost.name]: fellhammerSiegeHost,
  [firestormAssaultForce.name]: firestormAssaultForce,
  [freebooterKrew.name]: freebooterKrew,
  [gladiusTaskForce.name]: gladiusTaskForce,
  [greenTide.name]: greenTide,
  [hallowedConclave.name]: hallowedConclave,
  [headhunterTaskForce.name]: headhunterTaskForce,
  [huronsMarauders.name]: huronsMarauders,
  [ironstormSpearhead.name]: ironstormSpearhead,
  [kultOfSpeed.name]: kultOfSpeed,
  [librariusConclave.name]: librariusConclave,
  [lionsOfTheEmperor.name]: lionsOfTheEmperor,
  [moreDakka.name]: moreDakka,
  [nightmareHunt.name]: nightmareHunt,
  [nullMaidenVigil.name]: nullMaidenVigil,
  [orbitalAssaultForce.name]: orbitalAssaultForce,
  [pactboundZealots.name]: pactboundZealots,
  [reclamationForce.name]: reclamationForce,
  [renegadeRaiders.name]: renegadeRaiders,
  [renegadeWarband.name]: renegadeWarband,
  [sancticSpearhead.name]: sancticSpearhead,
  [shieldHost.name]: shieldHost,
  [solarSpearhead.name]: solarSpearhead,
  [soulforgedWarpack.name]: soulforgedWarpack,
  [speedwaaagh.name]: speedwaaagh,
  [stormlanceTaskForce.name]: stormlanceTaskForce,
  [taktikalBrigade.name]: taktikalBrigade,
  [talonsOfTheEmperor.name]: talonsOfTheEmperor,
  [vanguardSpearhead.name]: vanguardSpearhead,
  [veteransOfTheLongWar.name]: veteransOfTheLongWar,
  [warHorde.name]: warHorde,
  [warpbaneTaskForce.name]: warpbaneTaskForce,
  [warpstrikeChampions.name]: warpstrikeChampions,
};

// Keyed by the roster's catalogue name, in the catalogue's own order.
const detachmentsByFaction: Record<string, DetachmentData[]> = {
  "Chaos - Chaos Space Marines": [
    pactboundZealots,
    veteransOfTheLongWar,
    deceptors,
    renegadeRaiders,
    dreadTalons,
    fellhammerSiegeHost,
    chaosCult,
    soulforgedWarpack,
    creationsOfBile,
    cabalOfChaos,
    nightmareHunt,
    huronsMarauders,
    renegadeWarband,
    warpstrikeChampions,
    cultOfTheArkifane,
  ],
  "Imperium - Adeptus Custodes": [
    shieldHost,
    talonsOfTheEmperor,
    nullMaidenVigil,
    auricChampions,
    solarSpearhead,
    lionsOfTheEmperor,
  ],
  "Imperium - Grey Knights": [
    hallowedConclave,
    warpbaneTaskForce,
    brotherhoodStrike,
    auguriumTaskForce,
    sancticSpearhead,
    banishers,
  ],
  "Xenos - Orks": [
    warHorde,
    daBigHunt,
    dreadMob,
    greenTide,
    bullyBoyz,
    kultOfSpeed,
    taktikalBrigade,
    moreDakka,
    freebooterKrew,
    speedwaaagh,
    blitzBrigade,
  ],
  "Imperium - Adeptus Astartes - Ultramarines": [
    gladiusTaskForce,
    anvilSiegeForce,
    ironstormSpearhead,
    firestormAssaultForce,
    stormlanceTaskForce,
    vanguardSpearhead,
    _1stCompanyTaskForce,
    librariusConclave,
    bladeOfUltramar,
    bastionTaskForce,
    orbitalAssaultForce,
    reclamationForce,
    ceramiteSentinels,
    headhunterTaskForce,
  ],
};

export function getDetachmentData(
  name: string | null | undefined,
): DetachmentData | null {
  if (!name) return null;
  return detachmentsByName[name] ?? null;
}

/** Every detachment an army from this catalogue can field. */
export function detachmentsForFaction(
  catalogue: string | null | undefined,
): DetachmentData[] {
  if (!catalogue) return [];
  return detachmentsByFaction[catalogue] ?? [];
}
