import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const ironstormSpearhead: DetachmentData = {
  name: "Ironstorm Spearhead",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Armoured Wrath",
      text: `Once per phase for each ^^**Adeptus Astartes^^** unit in your army, you can re-roll one Hit roll, one Wound roll, or one Damage roll made for a model in that unit.`,
    },
  ],
  stratagems: [
    {
      name: "Mercy Is Weakness",
      cost: 2,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a unit that is below its Starting Strength, that attack has the [SUSTAINED HITS 1] ability, and when making such an attack, if the attacking model is a VEHICLE, a successful unmodified Hit roll of 5+ scores a Critical Hit.`,
    },
    {
      name: "Armour Of Contempt",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Unbowed Conviction",
      cost: 1,
      type: "Battle Tactic",
      phase: "Command phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that is below its Starting Strength.

EFFECT: Until the end of the turn, your unit can ignore any or all modifiers to its characteristics and/or to any roll or test made for it (excluding modifiers to saving throws).`,
    },
    {
      name: "Power Of The Machine Spirit",
      cost: 1,
      type: "Epic Deed",
      phase: "Your opponent's Shooting phase, just after an enemy unit has resolved its attacks",
      text: `TARGET: One ADEPTUS ASTARTES VEHICLE unit from your army that was reduced to Below Half-strength as a result of the attacking unit's attacks.

EFFECT: Your unit can shoot as if it were your Shooting phase, but must target only that enemy unit when doing so, and can only do so if that enemy unit is an eligible target.`,
    },
    {
      name: "Ancient Fury",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Command phase",
      text: `TARGET: One ADEPTUS ASTARTES WALKER model from your army.

EFFECT: Until the start of your next Command phase, improve your model's Move, Toughness, Leadership and Objective Control characteristics by 1 and each time your model makes an attack, add 1 to the Hit roll.`,
    },
    {
      name: "Vengeful Animus",
      cost: 1,
      type: "Epic Deed",
      phase: "Any phase, just after an ADEPTUS ASTARTES VEHICLE model from your army with the Deadly Demise ability is destroyed",
      text: `TARGET: That ADEPTUS ASTARTES VEHICLE model. You can use this Stratagem on that model even though it was just destroyed.

EFFECT: Do not roll one D6 to determine whether mortal wounds are inflicted by your model's Deadly Demise ability. Instead, mortal wounds are automatically inflicted.`,
    },
  ],
};
