import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const kultOfSpeed: DetachmentData = {
  name: "Kult of Speed",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Adrenaline Junkies",
      text: `**^^Speed Freeks^^** units from your army are eligible to shoot and declare a charge in a turn in which they Advanced or Fell Back.`,
    },
  ],
  stratagems: [
    {
      name: "Full Throttle!",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Charge phase, just after a SPEED FREEKS unit from your army ends a Charge move",
      text: `TARGET: That Speed Freeks unit.

EFFECT: Until the end of the turn, each time a model in your unit makes a melee attack, add 1 to the Wound roll.`,
    },
    {
      name: "Blitza Fire",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One Speed Freeks unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [LETHAL HITS] ability and, each time a model in your unit makes an attack that targets a unit within 9", a Critical Hit is scored on an unmodified Hit roll of 5+, instead of only a 6.

RESTRICTIONS: A unit cannot be targeted by this and the Dakkastorm Stratagem in the same phase.`,
    },
    {
      name: "Dakkastorm",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One Speed Freeks unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [SUSTAINED HITS 1] ability. While targeting a unit within 9", they have the [SUSTAINED HITS 2] ability instead.

RESTRICTIONS: A unit cannot be targeted by this and the Blitza Fire Stratagem in the same phase.`,
    },
    {
      name: "Speediest Freeks",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Speed Freeks or Trukk unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, models in your unit have a 5+ invulnerable save. If your unit is a VEHICLE unit with an unmodified Toughness characteristic of 8 or less, until the end of the phase, models in your unit have a 4+ invulnerable save instead.`,
    },
    {
      name: "More Gitz Over 'ere!",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move",
      text: `TARGET: One Speed Freeks unit from your army that is within 9" of that enemy unit and is not within Engagement Range of one or more enemy units.

EFFECT: Your unit can make a Normal move of up to 6".`,
    },
    {
      name: "Squig Flingin'",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after a SPEED FREEKS or TRUKK unit from your army ends a Normal, Advance or Fall Back move",
      text: `TARGET: That Speed Freeks or Trukk unit.

EFFECT: Select one enemy unit within 9" of your unit. That enemy unit must take a Battle-shock test and, when doing so, subtract 1 from the result.`,
    },
  ],
};
