import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const librariusConclave: DetachmentData = {
  name: "Librarius Conclave",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Psychic Disciplines",
      text: `At the start of the battle round, select one of the following Psychic Disciplines. Until the end of the battle round, that Psychic Discipline is active and its effects apply to all ^^**Adeptus Astartes Psyker**^^ units from your army. 


Biomancy Discipline
Add 2" to the Move characteristic of models in this unit. 


Divination Discipline
Each time a model in this unit makes an attack, re‑roll a Hit roll of 1 and re‑roll a Wound roll of 1.


Pyromancy Discipline
Each time a ranged attack made by a model in this unit targets an enemy unit within 12", improve the Armour Penetration characteristic of that attack by 1.


Telekinesis Discipline
Each time a ranged attack targets this unit, subtract 1 from the Strength characteristic of that attack.


Telepathy Discipline

Each time a model in this unit makes an attack, you can ignore any or all modifiers to that attack’s Weapon Skill or Ballistic Skill characteristics and/or any or all modifiers to the Hit roll.`,
    },
  ],
  stratagems: [
    {
      name: "Sensory Assault",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Command phase",
      text: `TARGET: One Adeptus Astartes Psyker unit from your army.

EFFECT: Select one enemy unit that is within 18" of and visible to one PSYKER model in your unit. Until the start of your next turn, that enemy unit is pinned. While a unit is pinned, subtract 2 from that unit's Move characteristic and subtract 2 from Charge rolls made for it. In addition, if the Telepathy Discipline is active for your army, that enemy unit must take a Battle-shock test, subtracting 1 from the result.`,
    },
    {
      name: "Armour Of Contempt",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Fiery Shield",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Adeptus Astartes Infantry or Adeptus Astartes Mounted unit from your army that is within 18" of one or more friendly Adeptus Astartes Psyker models, and that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time an attack targets your unit, subtract 1 from the Hit roll, and if the Pyromancy Discipline is active for your army, weapons that target your unit have the [HAZARDOUS] ability.`,
    },
    {
      name: "Iron Arm",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase",
      text: `TARGET: One Adeptus Astartes Infantry unit from your army that is within 18" of one or more Adeptus Astartes Psyker models from your army and has not been selected to Fight this phase.

EFFECT: Until the end of the phase, add 1 to the Strength characteristic of melee weapons equipped by models in your unit, or add 2 if the Biomancy Discipline is active for your army.`,
    },
    {
      name: "Assail",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One Adeptus Astartes Psyker unit from your army that is eligible to shoot.

EFFECT: Select one enemy unit within 18" of and visible to one or more PSYKER models in your unit (excluding units with the Lone Operative ability), and roll six D6, adding 1 to each result if the Telekinesis Discipline is active for your army: for each 4+, that enemy unit suffers 1 mortal wound.`,
    },
    {
      name: "Prescient Precision",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One Adeptus Astartes Psyker unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, that attack has the [LETHAL HITS] ability, and the [IGNORES COVER] ability as well if the Divination Discipline is active for your army.`,
    },
  ],
};
