import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const lionsOfTheEmperor: DetachmentData = {
  name: "Lions of the Emperor",
  faction: "Imperium - Adeptus Custodes",
  rules: [
    {
      name: "Against All Odds",
      text: `Each time an ^^**Adeptus Custodes^^** unit from your army (excluding ^^**Vehicles^^**) makes an attack, if there are no other friendly units within 6" of that unit, add 1 to the Hit roll and add 1 to the Wound roll.`,
    },
  ],
  stratagems: [
    {
      name: "Peerless Warrior",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One ADEPTUS CUSTODES unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, melee weapons equipped by models in your unit have the [PRECISION] ability.`,
    },
    {
      name: "Manoeuvre And Fire",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after an ADEPTUS CUSTODES unit from your army Falls Back",
      text: `TARGET: That ADEPTUS CUSTODES unit.

EFFECT: Until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Fell Back.`,
    },
    {
      name: "Swift As The Eagle",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has shot",
      text: `TARGET: One ADEPTUS CUSTODES unit from your army (excluding VEHICLE units) that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Your unit can make a Normal move of up to D6".`,
    },
    {
      name: "Unleash The Lions",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Command phase",
      text: `TARGET: One Allarus Custodians or Aquilon Custodians unit from your army that is on the battlefield.

EFFECT: That unit is split into separate units, each containing one model. These new units each have a Starting Strength of 1.`,
    },
    {
      name: "Gilded Champion",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Any phase, just after an Adeptus Custodes Character model from your army has used an ability on its datasheet that states it can only be used ‘once per battle'",
      text: `TARGET: That ADEPTUS CUSTODES CHARACTER model.

EFFECT: Your model can use that ‘once per battle' ability one additional time during the battle (but not in the same phase).

RESTRICTIONS: You cannot use this Stratagem on the same ADEPTUS CUSTODES CHARACTER model more than once per battle.`,
    },
    {
      name: "Defiant To The Last",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS CUSTODES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not fought this phase, roll one D6, adding 2 to the result if that model has the CHARACTER keyword. On a 4+, do not remove it from play; the destroyed model can fight after the attacking unit has finished making its attacks (when doing so, it is treated as having 1 wound remaining), and is then removed from play.`,
    },
  ],
};
