import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const moreDakka: DetachmentData = {
  name: "More Dakka!",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Dakka! Dakka! Dakka!",
      text: `Ranged weapons equipped by **^^Orks Infantry^^** and **^^Orks Walker^^** models from your army have the **[ASSAULT]** ability.

While the Waaagh! is active for your army, during your Shooting phase, ranged weapons equipped by **^^Orks Infantry^^** and **^^Orks Walker^^** models from your army have the **[SUSTAINED HITS 1]** ability.`,
    },
    {
      name: "Sustained Hits",
      text: `Weapons with **[SUSTAINED HITS X]** in their profile are known as Sustained Hits weapons. Each time an attack is made with such a weapon, if a Critical Hit is rolled, that attack scores a number of additional hits on the target as denoted by ‘x’`,
    },
    {
      name: "Assault",
      text: `Weapons with **[ASSAULT]** in their profile are known as Assault weapons. If a unit that Advanced this turn contains any models equipped with Assault weapons, it is still eligible to shoot in this turn’s Shooting phase. When such a unit is selected to shoot, you can only resolve attacks using Assault weapons its models are equipped with.`,
    },
  ],
  stratagems: [
    {
      name: "Long, Uncontrolled Bursts",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One ORKS unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [IGNORES COVER] ability.`,
    },
    {
      name: "Orks Is Still Orks",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One ORKS unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets an enemy unit, re-roll a Wound roll of 1. If that enemy unit is within range of an objective marker, you can re-roll the Wound roll instead.`,
    },
    {
      name: "Huge Show-Offs",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Command phase",
      text: `TARGET: One Orks Walker unit (excluding Killa Kans) from your army.

EFFECT: Until the start of your next Command phase, improve your unit's Move, Leadership and Objective Control characteristics by 1, and each time a model in your unit makes an attack, add 1 to the Hit roll.`,
    },
    {
      name: "Get Stuck In, Ladz!",
      cost: 2,
      type: "Epic Deed",
      phase: "Your Command phase",
      text: `TARGET: One ORKS unit from your army (excluding Gretchin units).

EFFECT: Until the start of your next Command phase, the Waaagh! is active for your unit, even if you have already called a Waaagh! this battle.

Designer's Note: This means that any abilities that are in effect while the Waaagh! is active for your army will be in effect for your unit.`,
    },
    {
      name: "Call Dat Dakka?",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has shot",
      text: `TARGET: One ORKS unit from your army that had one or more of its models destroyed as a result of the attacking unit's attacks.

EFFECT: Your unit can shoot as if it were your Shooting phase, but must target only that enemy unit when doing so, and can only do so if that enemy unit is an eligible target.`,
    },
    {
      name: "Speshul Shells",
      cost: 1,
      type: "Wargear",
      phase: "Your Shooting phase",
      text: `TARGET: One ORKS unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes a ranged attack that targets the closest eligible target within 18", improve the Armour Penetration characteristic of ranged weapons equipped by models in your unit by 1.`,
    },
  ],
};
