import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const nightmareHunt: DetachmentData = {
  name: "Nightmare Hunt",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Terror Made Manifest",
      text: `In the Battle‑shock step of your opponent’s Command phase, if an enemy unit that is below its Starting Strength is within 12" of one or more ^^**Heretic Astartes^^** units from your army, that enemy unit must take a Battle‑shock test, subtracting 1 from the result. Enemy units affected by this Detachment rule do not need to take any other Battle‑shock tests in the same phase. 
Each time a ^^**Heretic Astartes^^** model from your army makes an attack that targets a unit that is Below Half‑strength, add 1 to the Hit roll. 
Each time an attack targets a ^^**Heretic Astartes^^** unit from your army, if the attacking model is Battle‐shocked, subtract 1 from the Hit roll. 
Each time a ^^**Heretic Astartes^^** model from your army makes an attack that targets a Battle‐shocked unit, add 1 to the Wound roll.`,
    },
  ],
  stratagems: [
    {
      name: "Malicious Surge",
      cost: 1,
      phase: "Your Charge phase",
      text: `TARGET: One Heretic Astartes Infantry unit from your army.

EFFECT: Until the end of the phase, your unit is eligible to declare a charge in a turn in which it Advanced.`,
    },
    {
      name: "Sadistic Display",
      cost: 1,
      phase: "Fight phase, just after a HERETIC ASTARTES unit from your army destroys an enemy unit",
      text: `TARGET: That HERETIC ASTARTES unit.

EFFECT: Each enemy unit within 6" of and visible to your unit (excluding MONSTER and VEHICLE units) must take a Battle-shock test.`,
    },
    {
      name: "Relentless Terror",
      cost: 1,
      phase: "Your Movement phase, just after a Heretic Astartes Infantry unit from your army Falls Back",
      text: `TARGET: That HERETIC ASTARTES unit.

EFFECT: Until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Fell Back.`,
    },
    {
      name: "Horrific Incursion",
      cost: 1,
      phase: "Your Movement phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that arrived from Reserves this turn.

EFFECT: Select one enemy unit (excluding MONSTER and VEHICLE units) within 12" of and visible to your unit: that unit must take a Battle-shock test, subtracting 1 from the result.`,
    },
    {
      name: "Talons Sunk Deep",
      cost: 1,
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Heretic Astartes Infantry unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a unit that is Battle-shocked and/or Below Half-strength, improve the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Prey On The Weak",
      cost: 1,
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Heretic Astartes Infantry unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a unit that is Battle-shocked and/or Below Half-strength, you can re-roll the Hit roll.`,
    },
  ],
};
