import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const nullMaidenVigil: DetachmentData = {
  name: "Null Maiden Vigil",
  faction: "Imperium - Adeptus Custodes",
  rules: [
    {
      name: "Creeping Dread (Aura)",
      text: `In the Battle-shock step of your opponent's Command phase, if an enemy unit that is either a ^^**Psyker^^** unit or below its Starting Strength is within 12" of one or more ^^**Anathema Psykana^^** models from your army, that enemy unit must take a Battle-shock test. If that unit is below Half-strength, it must subtract 1 from its Battle-shock test this phase instead.`,
    },
  ],
  stratagems: [
    {
      name: "Witch Hunters",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Anathema Psykana unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Select either the [LETHAL HITS] or [SUSTAINED HITS 1] ability. Until the end of the phase, weapons equipped by models in your unit have the selected ability, but models in your unit can only target PSYKER units with their attacks.`,
    },
    {
      name: "Anathema Blademastery",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One Vigilators unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes a melee attack, you can re-roll the Hit roll If the target of that attack is Battle-shocked or a PSYKER, you can re-roll the Wound roll as well.`,
    },
    {
      name: "Purgation Sweep",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One Witchseekers unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, add 1 to the Attacks characteristic of Torrent weapons equipped by models in your unit. If such a weapon targets a PSYKER or Battle-shocked unit this phase, add 2 to its Attacks characteristic instead.`,
    },
    {
      name: "Psy-Chaff Volley",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One Prosecutors unit from your army that has just shot.

EFFECT: Select one enemy unit hit by one or more of those attacks. Until the start of your next turn, while your unit is on the battlefield, that enemy unit is prosecuted. While a unit is prosecuted, each time an Anathema Psykana model makes an attack against that unit, improve the Armour Penetration characteristic of that attack by 1. While a PSYKER or Battle-shocked unit is prosecuted, each time a model in that unit makes an attack, subtract 1 from the Hit roll.`,
    },
    {
      name: "Desperation's Price",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Any phase, just after an enemy PSYKER unit has either finished using a Psychic ability that targets a unit, or finished making Psychic Attacks",
      text: `TARGET: One Anathema Psykana unit from your army within 18" of that enemy PSYKER unit.

EFFECT: That enemy PSYKER unit must take a Leadership test If the test is passed, that PSYKER unit is Battle-shocked; if the test is failed that PSYKER unit suffers 3 mortal wounds and is Battle-shocked.`,
    },
    {
      name: "Psychic Abominations",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Anathema Psykana Infantry unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, your unit has the Stealth ability, and Battle-shocked and PSYKER models can only select your unit as a target of a ranged attack if they are within 12".`,
    },
  ],
};
