import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const orbitalAssaultForce: DetachmentData = {
  name: "Orbital Assault Force",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Rapid-drop Deployment",
      text: `At the start of the Declare Battle Formations step, select a number of ^^**Adeptus Astartes^^** units (excluding ^^**Titanic^^** units) from your army based on the battle size, as shown below. Models in those units have the Deep Strike ability.

Incursion - 2 Units
Strike Force - 3 Units
Onslaught - 4 Units

Each time an ^^**Adeptus Astartes^^** model from your army makes an attack, if it was set up on the battlefield this turn, re‑roll a Wound roll of 1. If it disembarked from a Drop Pod this turn, re‑roll a Hit roll of 1 as well.`,
    },
  ],
  stratagems: [
    {
      name: "Auto‑sense Coordination",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Select the [LETHAL HITS] or [SUSTAINED HITS 1] ability. Until the end of the phase, weapons equipped by models in your unit have this ability in a turn in which they disembarked from a Drop Pod or while targeting an enemy unit within 12".`,
    },
    {
      name: "Tactical Decapitation",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, weapons equipped by models in your unit have the [PRECISION] ability and each time a model in your unit makes an attack that targets a CHARACTER unit, add 1 to the Hit roll.`,
    },
    {
      name: "Blind Screen",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit (excluding Titanic units) from your army that was selected as the target of one or more of the attacking unit's attacks and one friendly Adeptus Astartes Smoke Vehicle or Drop Pod unit within 9" of it.

EFFECT: Until the end of the phase, models in your units have the Stealth ability and each time a ranged attack targets one of your units, models in that unit have the Benefit of Cover against that attack.`,
    },
    {
      name: "Suppression Strafing",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Command phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army.

EFFECT: Select one enemy unit visible to and within 18" of your unit. That enemy unit takes a Battle-shock test. When doing so, subtract 1 from that test and, if that test is failed, until the start of your next turn, that enemy unit is suppressed. While a unit is suppressed, each time a model in that unit makes an attack, subtract 1 from the Hit roll.

RESTRICTIONS: You cannot use this Stratagem more than once per battle round.`,
    },
    {
      name: "Shock Onslaught",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes a Pile-in or Consolidation move, it can move up to 6" instead of up to 3".`,
    },
    {
      name: "Onward For The Emperor",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of your opponent's Fight phase",
      text: `TARGET: One Adeptus Astartes Infantry unit from your army that was not set up on the battlefield this turn and one friendly Transport it is able to embark within.

EFFECT: If your ADEPTUS ASTARTES unit is wholly within 6" of that TRANSPORT, it can embark within it.`,
    },
  ],
};
