import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const pactboundZealots: DetachmentData = {
  name: "Pactbound Zealots",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Marks of Chaos",
      text: `When mustering your army, when you select a ^^Heretic Astartes^^ unit to include in your army, if that unit is not an ^^Epic Hero^^ and does not already have one of the following keywords, you must select one for that unit to gain and note it on your Army Roster: ^^Khorne, Tzeentch, Nurgle, Slaanesh, Chaos Undivided^^.


Each time a unit with one of these keywords gains a weapon ability as the result of a Dark Pact and does not fail the resulting Leadership test, until the end of the phase, that unit gains the associated ability below.


RESTRICTIONS
- You cannot select the ^^Khorne^^ keyword for a ^^Psyker^^ unit.
- A ^^Character^^ unit can only be attached to a unit if both units share the same keyword from the list below.
- A unit can only embark within (or start the battle embarked within) a ^^Transport^^ if both of those units share the same keyword from the list above.`,
    },
  ],
  stratagems: [
    {
      name: "Profane Zeal",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Heretic Astartes Chaos Undivided unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, you can re-roll the Wound roll.`,
    },
    {
      name: "Eye Of The Gods",
      cost: 1,
      type: "Epic Deed",
      phase: "Fight phase, just after a HERETIC ASTARTES CHARACTER unit from your army (excluding DAMNED, DAEMON and EPIC HERO units) destroys an enemy unit",
      text: `TARGET: One HERETIC ASTARTES CHARACTER model in that unit.

EFFECT: Until the end of the battle, add 1 to the Move, Toughness and Wounds characteristics of that CHARACTER model, and add 1 to the Attacks, Strength and Damage characteristics of that CHARACTER model's melee weapons.`,
    },
    {
      name: "Skinshift",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Command phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army.

EFFECT: One model in your unit regains up to 3 lost wounds. In addition, if your unit is a Tzeentch unit below its Starting Strength, one destroyed model (excluding Character models) is returned to your unit with its full wounds remaining.`,
    },
    {
      name: "Eternal Hate",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One HERETIC ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not fought this phase, roll one D6, adding 1 to the result if it is a Khorne unit: on a 4+, do not remove it from play. That destroyed model can fight after the attacking model's unit has finished making its attacks, and is then removed from play.`,
    },
    {
      name: "Festering Miasma",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One HERETIC ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, your unit has the Stealth ability. In addition, if your unit is a Nurgle unit, it can only be selected as the target of a ranged attack if the attacking model is within 18".`,
    },
    {
      name: "Torpefying Refrain",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army.

EFFECT: Until the end of the turn, your unit is eligible to declare a charge in a turn in which it Fell Back. If your unit is a Slaanesh unit, until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Advanced or Fell Back.`,
    },
  ],
};
