import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const reclamationForce: DetachmentData = {
  name: "Reclamation Force",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Oath of Reclamation",
      text: `- Each time an ^^**Adeptus Astartes^^** model from your army makes a melee attack that targets a unit within range of an
objective marker, improve the Armour Penetration characteristic of that attack by 1.

- Each time an attack targets an ^^**Adeptus Astartes^^** unit from your army, if your unit is within range of an objective
marker that you controlled at the start of the phase and if the Strength characteristic of that attack is greater
than the Toughness characteristic of your unit or your unit has the ^^**Titus^^** keyword, subtract 1 from the Wound roll.`,
    },
  ],
  stratagems: [
    {
      name: "Furious Dedication",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Charge phase or the Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that has not declared a charge or been selected to fight this phase.

EFFECT: Until the end of the turn, add 2 to Charge rolls made for your unit and add 1 to the Attacks characteristic of melee weapons equipped by models in your unit.

RESTRICTIONS: You cannot use this Stratagem more than once per turn.`,
    },
    {
      name: "Fight To The End",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not fought this phase, roll one D6: on a 4+, do not remove the destroyed model from play; it can fight after the attacking unit has finished making its attacks, and is then removed from play.`,
    },
    {
      name: "Ultramarian Destiny",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army.

EFFECT: Select one objective marker you control that your unit is within range of. That objective marker remains under your control until your opponent's Level of Control over that objective marker is greater than yours at the end of a phase.`,
    },
    {
      name: "Scions Of Guilliman",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after an ADEPTUS ASTARTES unit from your army ends a Fall Back move",
      text: `TARGET: That ADEPTUS ASTARTES unit.

EFFECT: Until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Fell Back.`,
    },
    {
      name: "Crusading Conquerors",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of the Command phase",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army.

EFFECT: Until the start of the next Command phase, add 1 to the Objective Control characteristic of models in your unit.`,
    },
    {
      name: "Marching Ever On",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit Falls Back",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was within Engagement Range of that enemy unit at the start of the phase.

EFFECT: Your unit can make a Normal move of up to D6"+1.`,
    },
  ],
};
