import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const renegadeRaiders: DetachmentData = {
  name: "Renegade Raiders",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Raiders and Reavers",
      text: `Ranged weapons equipped by ^^**Heretic Astartes**^^ models from your army have the [ASSAULT] ability, and each time a ^^**Heretic Astartes**^^ model from your army makes an attack that targets a unit within range of an objective marker, improve the Armour Penetration characteristic of that attack by 1.`,
    },
  ],
  stratagems: [
    {
      name: "Ruinous Raid",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or your Fight phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that disembarked from a TRANSPORT this turn and has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, if the target of that attack is within range of an objective marker, you can re-roll the Hit roll and you can re-roll the Wound roll.`,
    },
    {
      name: "Scour And Seize",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a unit within range of an objective marker, that attack has the [PRECISION] ability.`,
    },
    {
      name: "Unfailingly Obdurate",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One HERETIC ASTARTES unit from your army (excluding DAMNED units) that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Reavers' Haste",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Charge phase",
      text: `TARGET: One HERETIC ASTARTES INFANTRY or HERETIC ASTARTES MOUNTED unit from your army.

EFFECT: Until the end of the phase, your unit is eligible to declare a charge in a turn in which it Advanced. If you select one or more units within range of an objective marker as a target of that charge, add 1 to the Charge roll.`,
    },
    {
      name: "Opportunistic Raiders",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of the Fight phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that was eligible to fight this phase.

EFFECT: If your unit is not within Engagement Range of one or more enemy units, it can make a Normal move of up to 6", or up to 12" if it is a MOUNTED unit. Otherwise, your unit can make a Fall Back move. It cannot embark within a TRANSPORT at the end of this move if it disembarked from a TRANSPORT this turn.`,
    },
    {
      name: "Warpcharged Engines",
      cost: 1,
      type: "Wargear",
      phase: "Your Movement phase",
      text: `TARGET: One HERETIC ASTARTES TRANSPORT or HERETIC ASTARTES MOUNTED unit from your army that has not been selected to move this phase.

EFFECT: Until the end of the phase, if your unit Advances, do not make an Advance roll for it. Instead, until the end of the phase, add 6" to the Move characteristic of models in your unit.`,
    },
  ],
};
