import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const renegadeWarband: DetachmentData = {
  name: "Renegade Warband",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Slaves to None",
      text: `^^**Heretic Astartes**^^ models from your army lose the Dark Pacts ability. Ranged weapons equipped by **^^Heretic Astartes**^^ models from your army have the [ASSAULT] ability.

When mustering your army, you cannot use the Cults of the Dark Gods rule.`,
    },
    {
      name: "Vendetta",
      text: `At the start of your Command phase, select one unit from your opponent’s army. Until the start of your next Command phase, that enemy unit is your Vendetta target. Each time a ^^**Heretic Astartes**^^ model from your army (excluding **^^Damned**^^ models) makes an attack that targets your Vendetta target, you can re‑roll the Hit roll.`,
    },
    {
      name: "Twisted Doctrine",
      text: `In your Movement phase, each time you set up or select a ^^**Heretic Astartes^^** unit (excluding Battle‑shocked units) from your army to move, it can choose to Default to Doctrine. If it does, it must first take a Battle‑shock test. Then, select one of the following: 
- Until the end of the turn, this unit is eligible to shoot and declare a charge in a turn in which it Fell Back. 
- Until the end of the turn, this unit is eligible to declare a charge in a turn in which it Advanced.`,
    },
  ],
  stratagems: [
    {
      name: "Corrupted Munitions",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One HERETIC ASTARTES unit in your army that has just been selected to shoot.

EFFECT: Until the end of the phase, each time a model in this unit makes a ranged attack, improve the Armour Penetration of that attack by 1.`,
    },
    {
      name: "Vengeful Destruction",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Heretic Astartes Infantry (excluding Damned units) or Heretic Astartes Mounted unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time your unit makes an attack that targets your Vendetta target, add 1 to the Wound roll.`,
    },
    {
      name: "Never Outgunned",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that has just been selected to shoot or fight.

EFFECT: Select either the [LETHAL HITS] or [SUSTAINED HITS 1] ability. Until the end of the phase, weapons equipped by models in your unit have the selected ability.`,
    },
    {
      name: "Undying Hatred",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One HERETIC ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not fought this phase, roll one D6: on a 4+, do not remove the destroyed model from play; it can fight after the attacking unit has finished making its attacks, and is then removed from play.`,
    },
    {
      name: "Renegade Claim",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army within range of an objective marker you control.

EFFECT: That objective marker remains under your control until your opponent's Level of Control over that objective marker is greater than yours at the end of a phase.`,
    },
    {
      name: "Reavers' Reaction",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has shot",
      text: `TARGET: One HERETIC ASTARTES unit (excluding Monsters and Vehicles) from your army that was hit by one or more of those attacks.

EFFECT: Your unit can make a Normal move of up to D6".`,
    },
  ],
};
