import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const sancticSpearhead: DetachmentData = {
  name: "Sanctic Spearhead",
  faction: "Imperium - Grey Knights",
  rules: [
    {
      name: "Mailed Fist",
      text: `Each time a ^^**Grey Knights Vehicle**^^ unit from your army Advances, do not make an Advance roll for it; until the end of the phase, add 6" to the Move characteristic of models in that unit and, until the end of the turn, ranged weapons equipped by models in that unit have the [**^^Assault**^^] ability.`,
    },
  ],
  stratagems: [
    {
      name: "Abominus-Class Targets",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One Grey Knights unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack that targets a MONSTER or VEHICLE unit, add 1 to the Wound roll.`,
    },
    {
      name: "Truesilver Will",
      cost: 1,
      type: "Epic Deed",
      phase: "Any phase, just after a Grey Knights Psyker Vehicle unit from your army suffers a mortal wound",
      text: `TARGET: That GREY KNIGHTS PSYKER VEHICLE unit.

EFFECT: Until the end of the phase, models in your unit have the Feel No Pain 4+ ability against mortal wounds.`,
    },
    {
      name: "Argent Wrath",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Charge phase, just after a Grey Knights Vehicle unit from your army ends a Charge move",
      text: `TARGET: That GREY KNIGHTS VEHICLE unit.

EFFECT: Each enemy unit within 3" of your unit must take a Battle-shock test, subtracting 1 from that test.`,
    },
    {
      name: "Force Wave",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase or your Charge phase",
      text: `TARGET: One Grey Knights Vehicle unit from your army that has not been selected to move or charge this phase.

EFFECT: Until the end of the phase, each time your unit makes a Normal, Advance or Charge move, it can move horizontally through terrain features.`,
    },
    {
      name: "Redoubled Assault",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after a Grey Knights Vehicle unit from your army Falls Back",
      text: `TARGET: That GREY KNIGHTS VEHICLE unit.

EFFECT: Until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Fell Back.`,
    },
    {
      name: "Armoured Aegis",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Command phase",
      text: `TARGET: One Grey Knights Psyker Vehicle unit from your army.

EFFECT: One model in your unit regains up to 3 lost wounds.`,
    },
  ],
};
