import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const shieldHost: DetachmentData = {
  name: "Shield Host",
  faction: "Imperium - Adeptus Custodes",
  rules: [
    {
      name: "Martial Mastery",
      text: `At the start of the battle round, you can select one of the bullet points below. If you do, until the start of the next battle round, that bullet point’s effects apply.

- Each time an ^^**Adeptus Custodes^^** model from your army with the Martial Ka'tah ability makes a melee attack, a successful unmodified attack roll of 5+ scores a Critical Hit.
- Improve the Armour Penetration characteristic of melee weapons equipped by ^^**Adeptus Custodes^^** models from your army with the Martial Ka'tah ability by 1.`,
    },
  ],
  stratagems: [
    {
      name: "Archeotech Munitions",
      cost: 1,
      type: "Wargear",
      phase: "Your Shooting phase",
      text: `TARGET: One ADEPTUS CUSTODES unit from your army (excluding Anathema Psykana units) that has not been selected to shoot this phase.

EFFECT: Select either the [LETHAL HITS] or [SUSTAINED HITS 1] ability. Until the end of the phase ranged weapons equipped by models in your unit have the selected ability.`,
    },
    {
      name: "Arcane Genetic Alchemy",
      cost: 1,
      type: "Battle Tactic",
      phase: "Any phase, just after a mortal wound has been allocated to an Adeptus Custodes model from your army (excluding Anathema Psykana models)",
      text: `TARGET: That ADEPTUS CUSTODES model's unit.

EFFECT: Until the end of the phase, models in your unit have the Feel No Pain 4+ ability against mortal wounds.`,
    },
    {
      name: "Multipotentiality",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One Adeptus Custodes unit from your army that Fell Back this phase.

EFFECT: Until the end of your turn, that unit is eligible to shoot and declare a charge in a turn in which it Fell Back.`,
    },
    {
      name: "Vigilance Eternal",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One Adeptus Custodes Battleline unit from your army (excluding Anathema Psykana units) within range of an objective marker you control.

EFFECT: That objective marker remains under your control even if you have no models within range of it, until your opponent controls it at the start or end of any turn.`,
    },
    {
      name: "Unwavering Sentinels",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Adeptus Custodes Infantry unit from your army (excluding Anathema Psykana units) that is within range of an objective marker you control and that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a melee attack targets your unit, subtract 1 from the Hit roll.`,
    },
    {
      name: "Avenge The Fallen",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Start of the Fight phase",
      text: `TARGET: One ADEPTUS CUSTODES unit from your army (excluding Anathema Psykana units) that is below its Starting Strength.

EFFECT: Until the end of the phase, add 1 to the Attacks characteristic of melee weapons equipped by models in that unit. If your unit is Below Half-strength, until the end of the phase, add 2 to the Attacks characteristic of those melee weapons instead.`,
    },
  ],
};
