import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const solarSpearhead: DetachmentData = {
  name: "Solar Spearhead",
  faction: "Imperium - Adeptus Custodes",
  rules: [
    {
      name: "Auric Armour",
      text: `■ While an ^^**Adeptus Custodes Vehicle^^** unit from your army is at Starting Strength, unless that unit is an ^^**Aircraft^^** or it is Battle‑shocked, add 2 to the Objective Control characteristic of models in that unit.

■ While an ^^**Adeptus Custodes Vehicle^^** unit from your army is below Starting Strength, each time a model in that unit makes an attack, re‑roll a Hit roll of 1.

■ While an ^^**Adeptus Custodes Vehicle^^** unit from your army is Below Half‑strength, each time a model in that unit makes an attack, re‑roll a Hit roll of 1 and re‑roll a Wound roll of 1.`,
    },
    {
      name: "Moritoi Ancients",
      text: `Add 2" to the Move characteristic of models in ^^**Adeptus Custodes Walker^^** units from your army and add 1 to Advance and Charge rolls made for such units.`,
    },
  ],
  stratagems: [
    {
      name: "Flawless Construction",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Adeptus Custodes Vehicle unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time an attack targets a model in your unit, if the Strength characteristic of that attack is greater than the Toughness characteristic of your unit, subtract 1 from the Wound roll.`,
    },
    {
      name: "Emperor's Vengeance",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS CUSTODES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not fought this phase, roll one D6, adding 1 to the result if your unit has the Walker keyword. On a 4+, do not remove it from play; The destroyed model can fight after the attacking unit has finished making its attacks (when doing so, it is assumed to have 1 wound remaining), and is then removed from play.`,
    },
    {
      name: "Wrathful Advance",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase, just before an ADEPTUS CUSTODES unit from your army Piles In",
      text: `TARGET: That ADEPTUS CUSTODES unit.

EFFECT: Until the end of the phase, each time a model in your unit makes a Pile-in move, it can move up to D3+3" instead of up to 3".`,
    },
    {
      name: "Relentless Persecution",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after an ADEPTUS CUSTODES VEHICLE unit from your army Advances",
      text: `TARGET: That Adeptus Custodes Vehicle unit.

EFFECT: Until the end of the turn, your unit is eligible to shoot in a turn in which it Advanced. If your unit has the Walker keyword, until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Advanced instead.`,
    },
    {
      name: "Unstoppable",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase or your Charge phase",
      text: `TARGET: One Adeptus Custodes Vehicle or Adeptus Custodes Mounted unit from your army.

EFFECT: Until the end of the phase, each time a model in your unit makes a move, it can move through terrain features.`,
    },
    {
      name: "Punishment Inescapable",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: One ADEPTUS CUSTODES unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [IGNORES COVER] ability, and until the end of the phase, each time a model in your unit makes an attack, you can ignore any or all modifiers to that attack's Ballistic Skill characteristic and/or any or all modifiers to the Hit roll.`,
    },
  ],
};
