import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const soulforgedWarpack: DetachmentData = {
  name: "Soulforged Warpack",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Debt to the Soulforge",
      text: `Each time a ^^**Heretic Astartes Daemon Vehicle**^^ model from your army makes a Dark Pact, it can invoke its contract. If it does, subtract 1 from the resulting Leadership test when making that Dark Pact and, until the end of the phase:
- Each time a model in that unit makes a ranged attack, add 1 to the Wound roll.
- Add 2 to the Attacks characteristic of melee weapons equipped by models in that unit.`,
    },
  ],
  stratagems: [
    {
      name: "Desperate Pledge",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One HERETIC ASTARTES DAEMON VEHICLE unit from your army that has not been selected to shoot or fight this phase.

EFFECT: Until the end of the phase, if your unit invokes its contract, each time it makes an attack, improve the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Daemonic Possesion",
      cost: 1,
      type: "Epic Deed",
      phase: "Your Command phase",
      text: `TARGET: One HERETIC ASTARTES VEHICLE unit from your army (excluding Daemon units).

EFFECT: Until the end of the battle, your unit has the DAEMON keyword.`,
    },
    {
      name: "Glut Of Souls",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Fight phase",
      text: `TARGET: One HERETIC ASTARTES DAEMON VEHICLE unit from your army (excluding Titanic units) that has not been selected to fight this phase.

EFFECT: Until the end of the phase, if your unit invokes its contract, each time it makes an attack that destroys an enemy model, roll one D6: on 5+, your unit regains 1 lost wound after all of its attacks have been resolved (to a maximum of 6 wound).`,
    },
    {
      name: "Feeding Frenzy",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, when an enemy unit (excluding MONSTER and VEHICLES) is selected to Fall Back",
      text: `TARGET: One HERETIC ASTARTES DAEMON VEHICLE or Vashtorr the Arkifane unit from your army that is within Engagement Range of that enemy unit.

EFFECT: Until the end of the phase, each time an enemy unit (excluding MONSTERS and VEHICLES) that is within Engagement Range of your units Falls Back, all models in that enemy unit must take a Desperate Escape test. When doing so, of that enemy unit is Battle-shocked, substract 1 from each of those tests.`,
    },
    {
      name: "Unstoppable Rampage",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase or Charge phase",
      text: `TARGET: One Heretic Astartes Vehicle or Vashtorr the Arkifane unit from your army that has not been selected to move or charge this phase.

EFFECT: Until the end of the phase, each time your unit makes Normal, Advance or charge move, it can move horizontally through terrain features as if they were not there.`,
    },
    {
      name: "Predatory Pursuit",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall back move",
      text: `TARGET: One HERETIC ASTARTES VEHICLE or Vashtorr the Arkifane unit from your army that is within 9" of that enemy unit and not within Engagement Range of one or more enemy units.

EFFECT: Your unit can make a Normal move of up to 6", but must end that move as close as possible to that enemy unit.`,
    },
  ],
};
