import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const speedwaaagh: DetachmentData = {
  name: "Speedwaaagh!",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Turbo Boostas",
      text: `Each time a **^^Speed Freeks^^** or **^^Trukk^^** unit (excluding **^^Aircraft^^**) from your army Advances, it can use its turbo. If it does, do not make an Advance roll for it; instead, until the end of the phase, models in that unit have a Move characteristic of 24" but can only move in one straight line, and until the end of the turn, ranged weapons equipped by those models have the **[ASSAULT]** ability and that unit cannot declare a charge.

**Designer’s Note:** *When a unit uses its turbo, the models in that unit cannot pivot, and they cannot make a move of two or more straight lines (e.g. to navigate around obstacles). That unit also cannot declare a charge, even if another rule would let it declare a charge in a turn in which it Advanced.*`,
    },
    {
      name: "Assault",
      text: `Weapons with **[ASSAULT]** in their profile are known as Assault weapons. If a unit that Advanced this turn contains any models equipped with Assault weapons, it is still eligible to shoot in this turn’s Shooting phase. When such a unit is selected to shoot, you can only resolve attacks using Assault weapons its models are equipped with.`,
    },
  ],
  stratagems: [
    {
      name: "Mobile Dakkastorm",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase, just after a Speed Freeks or Trukk unit from your army has shot",
      text: `TARGET: That SPEED FREEKS or TRUKK unit.

EFFECT: Select one enemy unit hit by one or more of those attacks (excluding attacks made with Indirect Fire weapons). Until the end of the phase, each time a model in a SPEED FREEKS or TRUKK unit from your army makes an attack that targets that unit, improve the Strength characteristic of that attack by 2.`,
    },
    {
      name: "Evasive Manoova",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of your opponent's Fight phase",
      text: `TARGET: One Speed Freeks or Trukk unit from your army that is not within Engagement Range of one or more enemy units.

EFFECT: Remove your unit from the battlefield and place it into Strategic Reserves.`,
    },
    {
      name: "Dust Trails",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ORKS unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, your unit has the Benefit of Cover.`,
    },
    {
      name: "Ded Killy Construction",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Fight phase",
      text: `TARGET: One Speed Freeks or Trukk unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, melee weapons equipped by models in your unit have the [LANCE] ability and, if your unit made a Charge move this turn, until the end of the phase, add 1 to the Damage characteristic of those weapons.`,
    },
    {
      name: "On Da Move",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One ORKS unit from your army that has not been selected to move this phase.

EFFECT: Until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Fell Back or Advanced (unless it used its turbo this turn).`,
    },
    {
      name: "Speshul Ammo",
      cost: 1,
      type: "Wargear",
      phase: "Your Shooting phase",
      text: `TARGET: One ORKS unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit (excluding Torrent weapons) have the [ANTI-MONSTER 4+] and [ANTI-VEHICLE 4+] abilities.`,
    },
  ],
};
