import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const taktikalBrigade: DetachmentData = {
  name: "Taktikal Brigade",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Keywords",
      text: `**^^Stormboyz^^** units from your army gain the **^^Battleline^^** keyword.`,
    },
    {
      name: "Lissen 'Ere",
      text: `Once per battle round, in your Command phase or after being set up on the battlefield in your Movement phase, each **^^Boss Snikrot^^**, **^^Mek^^** and **^^Warboss^^** model in your army can issue Taktiks abilities.

To do so, select one of the Taktiks abilities below and select one friendly **^^Orks^^** unit within 6" of that model to issue them to. That model must take a Leadership test: if failed, the selected unit suffers 1 mortal wound. Until the start of your next Command phase, the selected unit is affected by the selected Taktik. A unit cannot have Taktiks issued to it in this way more than once per battle round.

Taktiks abilities cannot be issued to Battle shocked units, and if a unit affected by Taktiks becomes Battle shocked, all Taktiks cease to affect that unit while it is Battle shocked.

**Get Stuck In:** You can re-roll Charge rolls made for this unit.

**Get On Wiv It:** Add 1 to the Strength characteristic of melee weapons equipped by models in this unit.

**Sneaky Stalkin’:** **^^Infantry^^** and **^^Mounted^^** models (excluding **^^Meganobz^^**) in this unit have the Stealth ability and each time a ranged attack targets this unit, those models have the Benefit of Cover against that attack.

**Shoota Drills:** Each time an **^^Infantry^^** or **^^Mounted^^** model in this unit makes a ranged attack, add 1 to the Hit roll.`,
    },
  ],
  stratagems: [
    {
      name: "Fight Proppa",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One Orks Infantry or Orks Mounted unit from your army that has not been selected to fight this phase.

EFFECT: Select the [SUSTAINED HITS 1] or [LETHAL HITS] ability. Until the end of the phase, melee weapons equipped by models in your unit have the selected ability.`,
    },
    {
      name: "Krunchin' Descent",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Charge phase, just after a STORMBOYZ unit from your army ends a Charge move",
      text: `TARGET: That Stormboyz unit.

EFFECT: Select one enemy unit within Engagement Range of your unit, then roll one D6 for each model in your unit that is within Engagement Range of that enemy unit: for each 4+, that enemy unit suffers 1 mortal wound (to a maximum of 6 mortal wounds).`,
    },
    {
      name: "Dat's Ours",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Command phase",
      text: `TARGET: One ORKS unit from your army that is within Engagement Range of one or more enemy units.

EFFECT: Until the start of the next Command phase, add 1 to the Objective Control characteristic of models in your unit.`,
    },
    {
      name: "Taktikal Retreat",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase, just after an ORKS unit from your army Falls Back",
      text: `TARGET: That ORKS unit.

EFFECT: Until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Fell Back.`,
    },
    {
      name: "Ded Sneaky",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of your opponent's Fight phase",
      text: `TARGET: One Kommandos or Stormboyz unit from your army that is not within Engagement Range of one or more enemy units.

EFFECT: Remove your unit from the battlefield and place it into Strategic Reserves.`,
    },
    {
      name: "On To Da Next",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit Falls Back",
      text: `TARGET: One ORKS unit from your army that was within Engagement Range of that enemy unit at the start of the phase.

EFFECT: Your unit can make a Normal move of up to 6".`,
    },
  ],
};
