import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const talonsOfTheEmperor: DetachmentData = {
  name: "Talons of the Emperor",
  faction: "Imperium - Adeptus Custodes",
  rules: [
    {
      name: "Revered Companions",
      text: `^^**Anathema Psykana^^** units from your army gain the following ability:
**Null Aegis (Aura)**: While an ^^**Adeptus Custodes^^** unit is within 6" of this unit, models in that unit have the Feel No Pain 5+ ability against Psychic Attacks and mortal wounds.


All other **^^Adeptus Custodes**^^ units from your army gain the following ability:
**Deadly Unity (Aura)**: While an **^Anathema Psykana^^** unit is within 6" of this unit, each time a model in that ^^**Anathema Psykana^^** unit makes an attack, add 1 to the Hit roll.`,
    },
  ],
  stratagems: [
    {
      name: "Emperor's Executioners",
      cost: 2,
      type: "Battle Tactic",
      phase: "Start of the Fight phase",
      text: `TARGET: Up to two Adeptus Custodes units from your army.

EFFECT: Until the end of the phase, each time a model in one of your units targets an enemy unit that is below its Starting Strength, add 1 to the Wound roll.

RESTRICTIONS: You can only select two units if one (and only one) of them is an Anathema Psykana unit and both are within 6" of each other.`,
    },
    {
      name: "Talons Interlocked",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: Up to two ADEPTUS CUSTODES INFANTRY units from your army, and one enemy unit that is an eligible target for all of those units.

EFFECT: Until the end of the phase, your units can only target that enemy unit, but each time a model in one of your units makes a ranged attack, improve the Strength and Armour Penetration characteristics of that attack by 1.

RESTRICTIONS: You can only select two units if one (and only one) of them is an ANATHEMA PSYKANA unit and both are within 6" of each other.`,
    },
    {
      name: "Empyric Severance",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS CusTODES unit from your army that was selected as the target of one or more of the attacking unit's attacks, and one friendly ANATHEMA PSYKANA unit within 6" of that ADEPTUS CUSTODES unit.

EFFECT: Until the end of the phase, your unit has the Feel No Pain 4+ ability against Psychic attacks and mortal wounds.`,
    },
    {
      name: "Taloned Pincer",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move",
      text: `TARGET: Up to two Adeptus Custodes units from your army that are within 9" of that enemy unit.

EFFECT: Your units can make a Normal move of up to 6".

RESTRICTIONS: You cannot select units that are within Engagement Range of one or more enemy units. You can only select two units if one (and only one) of them is an Anathema Psykana unit and both are within 6" of each other.`,
    },
    {
      name: "Shield Of Honour",
      cost: 1,
      type: "Epic Deed",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Anathema Psykana Infantry unit from your army that was selected as the target of one or more of the attacking unit's attacks, and one other friendly Adeptus Custodes Infantry unit (excluding ANATHEMA PSYKANA units) within 6" of that ANATHEMA PSYKANA INFANTRY unit.

EFFECT: Until the end of the phase, any attack that targets your ANATHEMA PSYKANA unit must instead target your other ADEPTUS CUSTODES unit (unless it is not an eligible target).`,
    },
    {
      name: "Hunt As One",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Start of your Movement phase",
      text: `TARGET: Up to two ADEPTUS CUSTODES units from your army.

EFFECT: Until the end of the turn, your units are eilgible to shoot and/or declare a charge in a turn in which they Fell Back.

RESTRICTIONS: You can only select two units if one (and only one) of them is an ANATHEMA PSYKANA unit and both are within 6" of each other.`,
    },
  ],
};
