import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const vanguardSpearhead: DetachmentData = {
  name: "Vanguard Spearhead",
  faction: "Imperium - Adeptus Astartes - Ultramarines",
  rules: [
    {
      name: "Shadow Masters",
      text: `Each time a ranged attack targets an ^^**Adeptus Astartes**^^ unit from your army, unless the attacking model is within 12", subtract 1 from the Hit roll and the target has the Benefit of Cover against that attack.`,
    },
  ],
  stratagems: [
    {
      name: "Strike From The Shadows",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One ADEPTUS ASTARTES INFANTRY unit from your army that has not been selected to shoot this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes a ranged attack that targets an enemy unit that is more than 12" away, improve the Ballistic Skill and Armour Penetration characteristics of that attack by 1. If one or more enemy models are destroyed as a result of those attacks, select one of those destroyed models; that destroyed model's unit must take a Battle-shock test.`,
    },
    {
      name: "Surgical Strikes",
      cost: 2,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One ADEPTUS ASTARTES INFANTRY unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, melee weapons equipped by models in your unit have the [PRECISION] ability.`,
    },
    {
      name: "Armour Of Contempt",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ADEPTUS ASTARTES unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Guerrilla Tactics",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of your opponent's Fight phase",
      text: `TARGET: Up to two PHOBOS and/or SCOUT SQUAD units from your army, or one other ADEPTUS ASTARTES INFANTRY unit from your army.

EFFECT: Remove those units from the battlefield and place them into Strategic Reserves.

RESTRICTIONS: Each unit selected for this Stratagem must be more than 3" away from all enemy models.`,
    },
    {
      name: "Calculated Feint",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Charge phase, just after an enemy unit declares a charge",
      text: `TARGET: One ADEPTUS ASTARTES INFANTRY unit from your army that was selected as a target of that charge.

EFFECT: Your unit can make a Normal move of up to D6", or up to 6" instead if it is a PHOBOS or ScouT SQUAD unit.

RESTRICTIONS: You cannot select a unit that is within Engagement Range of one or more enemy units.`,
    },
    {
      name: "A Deadly Prize",
      cost: 1,
      type: "Wargear",
      phase: "Start of the Command phase",
      text: `TARGET: One ADEPTUS ASTARTES INFANTRY or ADEPTUS ASTARTES MOUNTED unit from your army within range of an objective marker you control.

EFFECT: That objective marker is said to be Sabotaged, and remains under your control even if you have no models within range of it, until your opponent controls it at the start or end of any turn. While an objective marker is Sabotaged and under your control, each time an enemy unit ends a Normal, Advance, Fall Back or Charge move within range of that objective marker, roll one D6: on a 2+, that enemy unit suffers D3 mortal wounds.`,
    },
  ],
};
