import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const veteransOfTheLongWar: DetachmentData = {
  name: "Veterans of the Long War",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Focus of Hatred",
      text: `At the start of your Command phase, select one unit from your opponent's army to be your focus of hatred. Until the start of your next Command phase, each time a ^^**Heretic Astartes**^^ model from your army (excluding ^^**Damned**^^ models) makes an attack that targets your focus of hatred, you can re-roll the Hit roll.`,
    },
  ],
  stratagems: [
    {
      name: "Let The Galaxy Burn",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army (excluding TZEENTCH units) that has not been selected to shoot this phase

EFFECT: Until the end of the phase, ranged weapons equipped by models in your unit have the [IGNORES COVER] ability, and change the Attacks characteristic of Torrent weapons equipped by models in your unit to 6.`,
    },
    {
      name: "Contemptuous Disregard",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponents Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One HERETIC ASTARTES unit from your army (excluding DAMNED units) that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.`,
    },
    {
      name: "Endless Ire",
      cost: 2,
      type: "Epic Deed",
      phase: "Any phase, just after your focus of hatred is destroyed",
      text: `TARGET: One HERETIC ASTARTES CHARACTER unit from your army (excluding DAMNED units)

EFFECT: Select one enemy unit within 12" of and visible to your unit. Until the start of your next Command phase, that enemy unit is considered to be your focus of hatred.`,
    },
    {
      name: "Bringers Of Despair",
      cost: 2,
      type: "Epic Deed",
      phase: "Start of the Fight phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army (excluding DAMNED units) that is within Engagement Range of your focus of hatred.

EFFECT: Until the end of the phase, your unit has the Fights First ability.`,
    },
    {
      name: "Black Crusade",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One HERETIC ASTARTES INFANTRY unit or HERETIC ASTARTES MOUNTED unit from your army (excluding DAMNED units).

EFFECT: Until the end of the turn, your unit is eligible to shoot in a turn in which it Advanced or Fell Back, and bolt pistols, boltguns and combi-bolters equipped by models in your unit have the [DEVASTATING WOUNDS] ability while your unit has not already inflicted 6 wounds this turn using that ability.`,
    },
    {
      name: "Millennia Of Experience",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your opponent's Movement phase, just after an enemy unit ends a Normal, Advance or Fall Back move",
      text: `TARGET: One HERETIC ASTARTES INFANTRY or HERETIC ASTARTES MOUNTED unit from your army (excluding DAMNED units) that is within 9" of that enemy unit and not within Engagement Range of one or more enemy units.

EFFECT: Your unit can make a Normal move of up to 6".`,
    },
  ],
};
