import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const warHorde: DetachmentData = {
  name: "War Horde",
  faction: "Xenos - Orks",
  rules: [
    {
      name: "Get Stuck In",
      text: `Melee weapons equipped by **^^Orks^^** models from your army have the **[SUSTAINED HITS 1]** ability.`,
    },
    {
      name: "Sustained Hits",
      text: `Weapons with **[SUSTAINED HITS X]** in their profile are known as Sustained Hits weapons. Each time an attack is made with such a weapon, if a Critical Hit is rolled, that attack scores a number of additional hits on the target as denoted by ‘x’`,
    },
  ],
  stratagems: [
    {
      name: "'ard As Nails",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ORKS unit from your army (excluding Grots, Monster and Vehicle units) that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time an attack targets your unit, subtract 1 from the Wound roll.`,
    },
    {
      name: "Mob Rule",
      cost: 1,
      type: "Battle Tactic",
      phase: "End of your Command phase",
      text: `TARGET: One Mob unit from your army that contains 10 or more models and is not Below Half-strength.

EFFECT: Select one friendly Battle-shocked Orks Infantry unit within 6" of that MOB unit. That ORKS INFANTRY unit is no longer Battle-shocked.`,
    },
    {
      name: "Ere We Go",
      cost: 1,
      type: "Battle Tactic",
      phase: "Start of your Movement phase",
      text: `TARGET: One Orks Infantry unit from your army.

EFFECT: Until the end of the turn, add 2 to Advance and Charge rolls made for your unit.`,
    },
    {
      name: "Unbridled Carnage",
      cost: 1,
      type: "Battle Tactic",
      phase: "Fight phase",
      text: `TARGET: One ORKS unit from your army that has not been selected to fight this phase.

EFFECT: Until the end of the phase, each time a model in your unit makes a melee attack, an unmodified hit roll of 5+ scores a Critical Hit.`,
    },
    {
      name: "Careen!",
      cost: 1,
      type: "Epic Deed",
      phase: "Any phase, just after an Orks Vehicle unit from your army with the Deadly Demise ability is destroyed",
      text: `TARGET: That destroyed ORKS VEHICLE unit, if you roll a 6 for its Deadly Demise ability. You can use this Stratagem on that unit even though it was just destroyed.

EFFECT: Your unit can make a Normal or Fall Back move before its Deadly Demise ability is resolved, and before any embarked units perform an Emergency Disembarkation. When making this move, your unit can move over enemy units (excluding MONSTERS and VEHICLES) as if they were not there.`,
    },
    {
      name: "Orks Is Never Beaten",
      cost: 2,
      type: "Epic Deed",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One ORKS unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, each time a model in your unit is destroyed, if that model has not fought this phase, do not remove it from play. The destroyed model can fight after the attacking model's unit has finished making attacks, and is then removed from play.`,
    },
  ],
};
