import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const warpstrikeChampions: DetachmentData = {
  name: "Warpstrike Champions",
  faction: "Chaos - Chaos Space Marines",
  rules: [
    {
      name: "Warp Portals",
      text: `At the end of your opponent’s turn, you can select a number of ^^**Heretic Astartes Terminator, Obliterators**^^ and ^^**Mutilators^^** units from your army (excluding units that are within Engagement Range of one or more enemy units). The maximum number of units you can select depends on the battle size, as follows:


Incursion - Up to 1 unit
Strike Force - Up to 2 units
Onslaught - Up to 3 units


Once you have made your selections, remove those units from the battlefield and place them into Strategic Reserves.`,
    },
  ],
  stratagems: [
    {
      name: "Portal Of Spite",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Charge phase",
      text: `TARGET: One HERETIC ASTARTES unit from your army that was set up using the Deep Strike ability this turn and has not declared a charge this phase.

EFFECT: Until the end of the phase, each time your unit declares a charge, if the closest eligible enemy unit is selected as one of the targets of that charge, add 2 to the Charge roll.`,
    },
    {
      name: "Empyric Dislocation",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase or the Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One HERETIC ASTARTES unit from your army (excluding Damned units) that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the attacking unit has finished making its attacks, each time an attack targets your unit, worsen the Armour Penetration characteristic of that attack by 1.

RESTRICTIONS: You cannot target the same unit with the Empyric Dislocation and Armour of Corruption Stratagems in the same phase.`,
    },
    {
      name: "Siegebreaker Strike",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Shooting phase",
      text: `TARGET: Up to two HERETIC ASTARTES units from your army that were set up using the Deep Strike ability this turn and have not been selected to shoot this phase.

EFFECT: Until the end of the phase, ranged weapons equipped by models in your units have the [IGNORES COVER] ability.`,
    },
    {
      name: "Warp Flicker",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One Heretic Astartes Terminator, Obliterators or Mutilators unit from your army.

EFFECT: Until the end of the turn, your unit is eligible to shoot and declare a charge in a turn in which it Advanced.`,
    },
    {
      name: "Warp-Tainted",
      cost: 1,
      type: "Strategic Ploy",
      phase: "Your Movement phase",
      text: `TARGET: One Heretic Astartes Terminator, Obliterators or Mutilators unit from your army, within range of an objective marker you control.

EFFECT: That objective marker remains under your control until your opponent's Level of Control over that objective marker is greater than yours at the end of a phase.`,
    },
    {
      name: "Armour Of Corruption",
      cost: 2,
      type: "Strategic Ploy",
      phase: "Fight phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Heretic Astartes Terminator, Obliterators or Mutilators unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the turn, each time an attack is allocated to a model in your unit, subtract 1 from the Damage characteristic of that attack.

RESTRICTIONS: You cannot target the same unit with the Armour of Corruption and Empyric Dislocation Stratagems in the same phase.`,
    },
  ],
};
