import type { DetachmentData } from "./types";

// Generated by scripts/sync-stratagems.mjs. Do not edit by hand.
export const warpbaneTaskForce: DetachmentData = {
  name: "Warpbane Task Force",
  faction: "Imperium - Grey Knights",
  rules: [
    {
      name: "Hallowed Ground",
      text: `Certain areas of the battlefield are within your army's Hallowed Ground, as follows:

- Your deployment zone is always within your army's Hallowed Ground.

- The area of the battlefield within 6" of one or more **^^Purifier Squad^^** units from your army is within your army’s Hallowed Ground.

- At the start of any phase, if you control at least half of the objective markers within No Man’s Land, until the end of that phase, No Man’s Land is within your army’s Hallowed Ground.

- At the start of any phase, if you control at least half of the objective markers within your opponent’s deployment zone, until the end of that phase, your opponent’s deployment zone is within your army’s Hallowed Ground.

Each time a model in a **^^Grey Knights^^** unit from your army makes a ranged attack that targets a visible target or makes a melee attack, re-roll a Hit roll of 1. If that unit is a **^^Purifier Squad^^** and/or is wholly within your army’s Hallowed Ground, you can re-roll the Hit roll instead.`,
    },
  ],
  stratagems: [
    {
      name: "Repelling Sphere",
      cost: 1,
      type: "Battle Tactic",
      phase: "Start of your opponent's Charge phase",
      text: `TARGET: One Grey Knights Infantry unit from your army.

EFFECT: Until the end of the phase, each time an enemy unit declares a charge and your unit is one of the targets of that charge, subtract 1 from the Charge roll, or subtract 2 instead if your unit is wholly within your army's Hallowed Ground.`,
    },
    {
      name: "Fires Of Covenant",
      cost: 1,
      type: "Battle Tactic",
      phase: "Start of your opponent's Movement phase",
      text: `TARGET: One Grey Knights Infantry unit from your army.

EFFECT: Until the end of the phase, each time an enemy unit is set up or ends a Normal, Advance or Fall Back move within 6" of your unit, roll one D6, adding 2 to the result if your unit is wholly within your army's Hallowed Ground: on a 4+, that enemy unit suffers D3 mortal wounds.`,
    },
    {
      name: "Aegis Eternal",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your opponent's Shooting phase, just after an enemy unit has selected its targets",
      text: `TARGET: One Grey Knights Infantry unit from your army that was selected as the target of one or more of the attacking unit's attacks.

EFFECT: Until the end of the phase, models in your unit that are wholly within your Hallowed Ground have a 4+ invulnerable save.`,
    },
    {
      name: "Hallowed Beacon",
      cost: 1,
      type: "Battle Tactic",
      phase: "Reinforcements step of your Movement phase",
      text: `TARGET: One Grey Knights Infantry unit (excluding Terminator units) that is arriving using the Deep Strike ability this phase.

EFFECT: Set up your unit wholly within your army's Hallowed Ground and more than 6" horizontally away from all enemy units.`,
    },
    {
      name: "Sanctified Kill Zone",
      cost: 1,
      type: "Battle Tactic",
      phase: "Your Shooting phase or the Fight phase",
      text: `TARGET: One GREY KNIGHTS unit from your army that has not been selected to shoot or fight this phase and that is wholly within your army's Hallowed Ground.

EFFECT: Until the end of the phase, each time a model in your unit makes an attack, re-roll a Wound roll of 1, or, re-roll the Wound roll instead if your unit is a Purifier Squad.`,
    },
    {
      name: "Flames Of Sanctity",
      cost: 1,
      type: "Strategic Ploy",
      phase: "End of the Fight phase",
      text: `TARGET: One Purifier Squad unit from your army that was eligible to fight this phase.

EFFECT: Roll one D6 for each enemy unit within 6" of your unit, adding 1 to the result if your unit includes Castellan Crowe: on a 4+, that enemy unit suffers D3 mortal wounds.`,
    },
  ],
};
