// Pure helpers that turn pdftotext output into citable markdown sections.

const REF_HEADING = /^((?:\d+\.\s+)?[A-Z][A-Z0-9 ,'/&()-]*?)\s+(\d{2}\.\d{2})$/;

// pdftotext separates pages with a form feed.
export function splitPages(text) {
  const pages = text.split("\f");
  if (pages.length > 1 && pages[pages.length - 1].trim() === "") pages.pop();
  return pages;
}

function tidy(lines) {
  return lines
    .map((l) => l.replace(/\s+$/, ""))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

// 11th edition: every rule has a printed reference such as "FALL-BACK MOVE 09.07".
// Text before the first reference is returned as { id: "front", title: "Front matter" }.
// A reference printed twice (a stratagem card shown twice) gets a "-2" suffix.
export function splitByReference(pages) {
  const sections = [];
  const seen = new Map();
  let current = { id: "front", title: "Front matter", page: 1, lines: [] };
  pages.forEach((page, i) => {
    for (const line of page.split("\n")) {
      const m = REF_HEADING.exec(line.trim());
      if (m) {
        sections.push(current);
        const n = (seen.get(m[2]) ?? 0) + 1;
        seen.set(m[2], n);
        current = { id: n === 1 ? m[2] : `${m[2]}-${n}`, title: m[1].trim(), page: i + 1, lines: [] };
      } else {
        current.lines.push(line);
      }
    }
  });
  sections.push(current);
  return sections
    .map((s) => ({ id: s.id, title: s.title, page: s.page, body: tidy(s.lines) }))
    .filter((s) => s.body !== "" || s.id !== "front");
}

// 10th edition: the printed rules carry no reference numbers, so a page is the unit.
export function splitByPage(pages) {
  return pages.map((p, i) => ({
    id: `p${i + 1}`,
    title: `Page ${i + 1}`,
    page: i + 1,
    body: tidy(p.split("\n")),
  }));
}

export function toMarkdown({ edition, doc, source, mode, sections }) {
  const head = [
    `<!-- generated by pdf-to-md.mjs from ${source}; do not edit by hand -->`,
    `# ${edition} ${doc}`,
    "",
    mode === "ref"
      ? "Cite as `§<reference>` (the printed rule number, e.g. §09.07)."
      : "Cite as `p.<page>` (PDF page number; the printed rules have no reference numbers).",
    "",
  ];
  const body = sections.map((s) => {
    const label = mode === "ref" && s.id !== "front" ? `${s.title} (§${s.id})` : s.title;
    return `## ${label}\n<!-- id: ${s.id}, pdf page ${s.page} -->\n\n${s.body}\n`;
  });
  return [...head, ...body].join("\n");
}
