// Short definitions of the general 10th-edition unit keywords, for the
// keyword row on a unit card. Rosters export unit keywords as bare names
// with no rule text, so this is the text a keyword expands to when
// clicked. Datasheet names ("Warboss") and faction-specific keywords with
// no core rule of their own have no entry and render as plain text.
//
// Keys are the keyword as it appears on datasheets; lookup is
// case-insensitive. The text goes through the same i18n dictionary as
// ability text, so translations live in src/i18n/<lang>.ts (generated by
// .claude/skills/translate-army).
export const KEYWORD_GLOSSARY = {
  Infantry:
    "Foot troops. Infantry models can move through the walls of Ruins and are among the few unit types that can occupy their upper floors. Most Transport capacities, and many stratagems and abilities, apply only to Infantry units.",
  Character:
    "A hero that can lead other units. A Character with the Leader ability can be attached to a Bodyguard unit; while attached it cannot be picked out by attacks unless the attacker has Precision or every Bodyguard model has been destroyed. Characters are normally the only models that can be given Enhancements or be your Warlord.",
  "Epic Hero":
    "A named, unique character. Only one of each Epic Hero can be included in your army, and Epic Heroes cannot be given Enhancements.",
  Vehicle:
    "A tank, walker or other war machine. Vehicles can shoot while within Engagement Range of enemy units (Big Guns Never Tire), at -1 to hit with weapons other than Pistols, and they cannot end a move on the upper floors of Ruins. Many stratagems and abilities either single out or exclude Vehicles.",
  Walker:
    "A Vehicle that moves on legs. Walkers can move through the walls of Ruins like Infantry, and they are the only Vehicles that can use the Heroic Intervention stratagem.",
  Monster:
    "A large creature. Like Vehicles, Monsters can shoot while within Engagement Range of enemy units (Big Guns Never Tire) and cannot end a move on the upper floors of Ruins. Many stratagems and abilities either single out or exclude Monsters.",
  Mounted:
    "Cavalry and bikers. Mounted units cannot end a move on the upper floors of Ruins, and Transport capacities normally exclude them.",
  Battleline:
    "A core troop choice. Battleline units can be taken up to six times in a Strike Force-size army instead of three, and many missions, detachment rules and stratagems single them out, typically when holding objectives.",
  Transport:
    "A unit that can carry other units. Its transport capacity lists which models can embark. Embarked units cannot be targeted, and cannot move or shoot unless the Transport's rules allow it (for example Firing Deck). If the Transport is destroyed, its passengers disembark and each model must roll a D6: on a 1 it is destroyed.",
  "Dedicated Transport":
    "A Transport that is taken alongside the units it carries: for every Infantry unit in your army you can include one Dedicated Transport, over and above the normal datasheet limits.",
  Psyker:
    "A model that can manifest psychic powers. Psykers can use Psychic weapons and abilities, and suffer Perils of the Warp if a Hazardous psychic weapon misfires. Anti-Psyker weapons and abilities single them out.",
  Grenades:
    "The unit can use the Grenade stratagem: in your Shooting phase, one Grenades unit that is not within Engagement Range of enemy units can throw grenades at a visible enemy unit within 8\", rolling six D6 and inflicting 1 mortal wound for each 4+.",
  Fly:
    "The unit can fly. When it moves it can pass over other models and terrain, measuring the distance across the battlefield rather than up and over, though it cannot end its move on top of other models. Anti-Fly weapons single out units that can fly.",
  Smoke:
    "The unit can use the Smokescreen stratagem: in your opponent's Shooting phase, when it is selected as a target, it gains the Benefit of Cover and the Stealth ability until the end of the phase.",
  Titanic:
    "The largest war engines. Titanic units cannot be selected to fire Overwatch, and are excluded from many stratagems and abilities that affect ordinary Vehicles and Monsters.",
  Towering:
    "A model so tall that Ruins do not block line of sight to or from it: a Towering model can shoot over Ruins, and can be shot over them.",
  Terminator:
    "Wearing Tactical Dreadnought armour. Terminator units usually have Deep Strike, and Transport capacities as well as several stratagems and abilities treat them separately from other Infantry.",
  "Jump Pack":
    "Equipped with a jump pack. Jump Pack units usually have Fly and Deep Strike, and take up more space in Transports or are excluded from them.",
  "Mega Armour":
    "Ork mega armour. A Mega Armour model takes up the space of 2 models in a Transport.",
  Gravis:
    "Space Marine Gravis armour. Transport capacities and some abilities refer to it; Gravis models cannot embark in a Rhino.",
  Phobos:
    "Space Marine Phobos armour, worn by reconnaissance units. Transport capacities and some abilities refer to it; Phobos models cannot embark in a Rhino.",
  Tacticus:
    "Space Marine Tacticus armour, worn by most Primaris infantry. Transport capacities and some abilities refer to it.",
  Daemon:
    "A daemonic unit. Several stratagems and abilities exclude or single out Daemon units.",
  "Allied Units":
    "A unit taken as an ally from another faction, such as Imperial Knights Armigers in an Imperium army. Allied units do not benefit from your army's detachment rule and cannot be given Enhancements or be your Warlord.",
  Imperium:
    "Faction keyword shared by every army of the Imperium of Man (Space Marines, Adeptus Custodes, Grey Knights and others). Rules that refer to an Imperium unit apply to all of them, and it governs which allied units may be included.",
  Chaos:
    "Faction keyword shared by every Chaos army (Heretic Astartes, Chaos Daemons, Chaos Knights and others). Rules that refer to a Chaos unit apply to all of them, and it governs which allied units may be included.",
};

const byLowerCase = new Map(
  Object.entries(KEYWORD_GLOSSARY).map(([kw, text]) => [kw.toLowerCase(), text]),
);

/** The glossary text for a unit keyword, or null when the keyword has no
 * general rule of its own (datasheet names, faction sub-keywords). */
export function keywordDefinition(keyword: string): string | null {
  return byLowerCase.get(keyword.trim().toLowerCase()) ?? null;
}
